Update star build script

diff --git a/recipes/star/patches/0003-create-simd-dispatch.patch b/recipes/star/patches/0003-create-simd-dispatch.patch
--- a/recipes/star/patches/0003-create-simd-dispatch.patch
+++ b/recipes/star/patches/0003-create-simd-dispatch.patch
@@ -1,7 +1,7 @@
 new file mode 100755
 --- /dev/null
 +++ simd-dispatch.sh
-@@ -0,0 +1,21 @@
+@@ -0,0 +1,31 @@
 +#!/bin/bash
 +
 +SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
@@ -9,18 +9,30 @@ new file mode 100755
 +BASE=${DIR}/$(basename "$0")
 +CMDARGS="$@"
 +
++# Normalize CPU flags to ensure consistent detection
++cpu_flags=$(grep -oP 'flags\s+:\s+\K.*' /proc/cpuinfo | sort | uniq | tr '\n' ' ')
++cpu_flags=${cpu_flags//_/}
++
 +function test_and_run () {
-+	if grep -q "$1" /proc/cpuinfo && [ -x "${BASE}-$1" ]; then
-+		cmd="${BASE}-$1"
-+		shift
-+		# echo "${cmd}" "$@"
-+		"${cmd}" "$@"
-+		exit
-+	fi
++    if [[ $cpu_flags == *"$1"* ]] && [ -x "${BASE}-$1" ]; then
++        cmd="${BASE}-$1"
++        shift
++        # echo "${cmd}" "$@"
++        "${cmd}" "$@"
++        exit
++    fi
 +}
 +
-+for SIMD in avx2 avx sse4.1 ssse3 sse3 sse2 sse; do test_and_run ${SIMD} "$@"; done
++# Test for SIMD levels in order of preference
++for SIMD in avx2 avx sse4.1 sse4_1 ssse3 sse3; do
++    test_and_run ${SIMD} "$@"
++done
 +
-+# fallback to plain option
-+$BASE-plain "$@"
++# Fallback to plain option if no SIMD level matches
++if [ -x "$BASE-plain" ]; then
++    "$BASE-plain" "$@"
++else
++    echo "Error: No suitable STAR binary found for SIMD level." >&2
++    exit 1
++fi
 +
