[ci skip] add build failure record for recipe recipes/crux-toolkit

diff --git a/recipes/crux-toolkit/build_failure.linux-64.yaml b/recipes/crux-toolkit/build_failure.linux-64.yaml
--- a/recipes/crux-toolkit/build_failure.linux-64.yaml
+++ b/recipes/crux-toolkit/build_failure.linux-64.yaml
@@ -1,4 +1,4 @@
-recipe_sha: 1dde5f24a67d2917d62da32ddefe5291bde7ce339d1254e51dfbeb2e21155169  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 0eda127a05fc6ad33ece7a26c5ce04889b5ef8f51e91ce22e8a04b8c01fd4b8a  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
     commands:
@@ -21,14 +21,14 @@ log: |2-
       - should_be_noarch_generic
 
 
-  source tree in: /opt/conda/conda-bld/crux-toolkit_1735069847310/work
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735069847310/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735069847310/work
+  source tree in: /opt/conda/conda-bld/crux-toolkit_1735070936312/work
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735070936312/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735070936312/work
 
   Resource usage statistics from building crux-toolkit:
      Process count: 1
      CPU time: Sys=-, User=-
-     Memory: -
+     Memory: 384.0K
      Disk usage: 120.9K
      Time elapsed: 0:00:02.0
 
@@ -51,17 +51,17 @@ log: |2-
   .. is this binary repackaging?
   Fixing permissions
   INFO :: Time taken to mark (prefix)
-          0 replacements in 0 files was 0.03 seconds
+          0 replacements in 0 files was 0.02 seconds
   WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
   TEST START: /opt/conda/conda-bld/linux-64/crux-toolkit-4.2-h9ee0642_0.tar.bz2
-  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1735069847310/work' to '/opt/conda/conda-bld/crux-toolkit_1735069847310/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
-  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1735069847310/work, dest=/opt/conda/conda-bld/crux-toolkit_1735069847310/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
+  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1735070936312/work' to '/opt/conda/conda-bld/crux-toolkit_1735070936312/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
+  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1735070936312/work, dest=/opt/conda/conda-bld/crux-toolkit_1735070936312/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
   Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
   Solving environment (_test_env): ...working... done
 
   ## Package Plan ##
 
-    environment location: /opt/conda/conda-bld/crux-toolkit_1735069847310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+    environment location: /opt/conda/conda-bld/crux-toolkit_1735070936312/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
 
 
   The following NEW packages will be INSTALLED:
@@ -71,8 +71,8 @@ log: |2-
   Preparing transaction: ...working... done
   Verifying transaction: ...working... done
   Executing transaction: ...working... done
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735069847310/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735069847310/test_tmp
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735070936312/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735070936312/test_tmp
    crux version
   crux: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
   WARNING: Tests failed for crux-toolkit-4.2-h9ee0642_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
@@ -83,7 +83,7 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1735069847310/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1735070936312/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
 
   During handling of the above exception, another exception occurred:
 
