[ci skip] add build failure record for recipe recipes/crux-toolkit

diff --git a/recipes/crux-toolkit/build_failure.linux-64.yaml b/recipes/crux-toolkit/build_failure.linux-64.yaml
--- a/recipes/crux-toolkit/build_failure.linux-64.yaml
+++ b/recipes/crux-toolkit/build_failure.linux-64.yaml
@@ -1,47 +1,89 @@
-recipe_sha: 685acca39f6bfa12fe31008606a8e33bfc8e1a01e367f5e9c2cf104428ffc5a1  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: b39fc4df7a88032f7d6745efb35a1b3c7d635a72887767149e8be58865d91340  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      new_conflicts = self._maybe_raise_for_problems(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
-      self._maybe_raise_for_conda_build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("c_linux-64")}
-  Encountered problems while solving:
-    - nothing provides requested c_linux-64
+      - crux-toolkit >=4.2,<4.3.0a0
+    script: mkdir -p $PREFIX/bin; chmod ax bin/*; cp bin/* $PREFIX/bin
+  requirements:
+    build: []
+    run: []
+  test:
+    commands:
+      - crux version
+  about:
+    dev_url: https://github.com/crux-toolkit/crux-toolkit
+    home: http://crux.ms
+    license: Apache-2.0
+    license_family: Apache
+    summary: A cross-platform suite of analysis tools for interpreting protein mass
+      spectrometry data
+  extra:
+    copy_test_source_files: true
+    final: true
+    recipe-maintainers:
+      - CharlesEGrant
+      - wsnoble
+      - acquayefrank
+    skip-lints:
+      - should_be_noarch_generic
 
-  Could not solve for environment specs
-  The following package could not be installed
-   [31mc_linux-64[0m does not exist (perhaps a typo or a missing channel).
 
-  During handling of the above exception, another exception occurred:
+  source tree in: /opt/conda/conda-bld/crux-toolkit_1734673063059/work
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1734673063059/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1734673063059/work
 
+  Resource usage statistics from building crux-toolkit:
+     Process count: 1
+     CPU time: Sys=-, User=-
+     Memory: 384.0K
+     Disk usage: 120.9K
+     Time elapsed: 0:00:02.0
+
+
+  Packaging crux-toolkit
+  Packaging crux-toolkit-4.2-h9ee0642_0
+  number of files: 1
+  Skipping binary relocation logic
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libpthread.so.0 found in the whitelist
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libstdc.so.6 found in the whitelist
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libm.so.6 found in the whitelist
+     INFO (crux-toolkit,bin/crux): Needed DSO $RPATH/libgomp.so.1 found in the whitelist
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libgcc_s.so.1 found in the whitelist
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libc.so.6 found in the whitelist
+  Fixing permissions
+  INFO :: Time taken to mark (prefix)
+          0 replacements in 0 files was 0.02 seconds
+  WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
+  TEST START: /opt/conda/conda-bld/linux-64/crux-toolkit-4.2-h9ee0642_0.tar.bz2
+  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1734673063059/work' to '/opt/conda/conda-bld/crux-toolkit_1734673063059/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
+  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1734673063059/work, dest=/opt/conda/conda-bld/crux-toolkit_1734673063059/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
+  Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
+  Solving environment (_test_env): ...working... done
+
+  ## Package Plan ##
+
+    environment location: /opt/conda/conda-bld/crux-toolkit_1734673063059/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+
+
+  The following NEW packages will be INSTALLED:
+
+      crux-toolkit: 4.2-h9ee0642_0 local
+
+  Preparing transaction: ...working... done
+  Verifying transaction: ...working... done
+  Executing transaction: ...working... done
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1734673063059/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1734673063059/test_tmp
+   crux version
+  crux: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
+  WARNING: Tests failed for crux-toolkit-4.2-h9ee0642_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
   Traceback (most recent call last):
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 891, in get_install_actions
-      _actions = _install_actions(prefix, index, specs, subdir=subdir)
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1307, in install_actions
-      txn = solver.solve_for_transaction(prune=False, ignore_pinned=False)
-    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
-      unlink_precs, link_precs = self.solve_for_diff(
-    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 221, in solve_for_diff
-      final_precs = self.solve_final_state(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 223, in solve_final_state
-      out_state = self._solving_loop(in_state, out_state, index)
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 303, in _solving_loop
-      solved = self._solve_attempt(in_state, out_state, index, attempt=attempt)
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 414, in _solve_attempt
-      new_conflicts = self._maybe_raise_for_problems(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
-      self._maybe_raise_for_conda_build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("c_linux-64")}
-  Encountered problems while solving:
-    - nothing provides requested c_linux-64
-
-  Could not solve for environment specs
-  The following package could not be installed
-   [31mc_linux-64[0m does not exist (perhaps a typo or a missing channel).
+    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3523, in test
+      utils.check_call_env(
+    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1734673063059/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
 
   During handling of the above exception, another exception occurred:
 
@@ -52,53 +94,11 @@ log: |2-
       api.build(
     File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
       return build_tree(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
-      packages_from_this = build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2338, in build
-      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 916, in expand_outputs
-      for output_dict, m in deepcopy(_m).get_output_metadata_set(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 2658, in get_output_metadata_set
-      conda_packages = finalize_outputs_pass(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 1025, in finalize_outputs_pass
-      fm = finalize_metadata(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 650, in finalize_metadata
-      build_unsat, host_unsat = add_upstream_pins(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 491, in add_upstream_pins
-      host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 444, in _read_upstream_pin_files
-      deps, precs, unsat = get_env_dependencies(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 156, in get_env_dependencies
-      precs = environ.get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 938, in get_install_actions
-      precs = get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 938, in get_install_actions
-      precs = get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 938, in get_install_actions
-      precs = get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 891, in get_install_actions
-      _actions = _install_actions(prefix, index, specs, subdir=subdir)
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1307, in install_actions
-      txn = solver.solve_for_transaction(prune=False, ignore_pinned=False)
-    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
-      unlink_precs, link_precs = self.solve_for_diff(
-    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 221, in solve_for_diff
-      final_precs = self.solve_final_state(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 223, in solve_final_state
-      out_state = self._solving_loop(in_state, out_state, index)
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 303, in _solving_loop
-      solved = self._solve_attempt(in_state, out_state, index, attempt=attempt)
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 414, in _solve_attempt
-      new_conflicts = self._maybe_raise_for_problems(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
-      self._maybe_raise_for_conda_build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("c_linux-64")}
-  Encountered problems while solving:
-    - nothing provides requested c_linux-64
-
-  Could not solve for environment specs
-  The following package could not be installed
-   [31mc_linux-64[0m does not exist (perhaps a typo or a missing channel).
+    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3727, in build_tree
+      test(pkg, config=metadata.config.copy(), stats=stats)
+    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3537, in test
+      tests_failed(
+    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3584, in tests_failed
+      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
+  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: crux-toolkit-4.2-h9ee0642_0.tar.bz2
 # Last 100 lines of the build log.
