[ci skip] add build failure record for recipe recipes/crux-toolkit

diff --git a/recipes/crux-toolkit/build_failure.linux-64.yaml b/recipes/crux-toolkit/build_failure.linux-64.yaml
--- a/recipes/crux-toolkit/build_failure.linux-64.yaml
+++ b/recipes/crux-toolkit/build_failure.linux-64.yaml
@@ -1,6 +1,10 @@
-recipe_sha: 7ce35d81397431f78a331159af49a2f8a811cc6d95468b4817b4555bd3d871d2  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 67fccf1009de8020c5aff4578c9625730be30dab9af5f973863343fb1db5267a  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |-
+log: |2-
+      - libgomp >=13
+  test:
+    commands:
+      - crux version
   about:
     dev_url: https://github.com/crux-toolkit/crux-toolkit
     home: http://crux.ms
@@ -19,14 +23,14 @@ log: |-
       - should_be_noarch_generic
 
 
-  source tree in: /opt/conda/conda-bld/crux-toolkit_1735073781735/work
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735073781735/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735073781735/work
+  source tree in: /opt/conda/conda-bld/crux-toolkit_1735085375260/work
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735085375260/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735085375260/work
 
   Resource usage statistics from building crux-toolkit:
      Process count: 2
      CPU time: Sys=-, User=0:00:00.0
-     Memory: 10.9M
+     Memory: 11.8M
      Disk usage: 120.9K
      Time elapsed: 0:00:02.0
 
@@ -35,31 +39,27 @@ log: |-
   Packaging crux-toolkit-4.2-h9ee0642_0
   number of files: 1
   Skipping binary relocation logic
-  WARNING (crux-toolkit,bin/crux): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libpthread.so.0 found in the whitelist
   WARNING (crux-toolkit,bin/crux): /lib64/libstdc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
   .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libm.so.6 found in the whitelist
   WARNING (crux-toolkit,bin/crux): $RPATH/libgomp.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
   .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libgcc_s.so.1 found in the whitelist
+     INFO (crux-toolkit,bin/crux): Needed DSO /lib64/libc.so.6 found in the whitelist
   Fixing permissions
   INFO :: Time taken to mark (prefix)
-          0 replacements in 0 files was 0.01 seconds
+          0 replacements in 0 files was 0.03 seconds
   WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
   TEST START: /opt/conda/conda-bld/linux-64/crux-toolkit-4.2-h9ee0642_0.tar.bz2
-  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1735073781735/work' to '/opt/conda/conda-bld/crux-toolkit_1735073781735/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
-  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1735073781735/work, dest=/opt/conda/conda-bld/crux-toolkit_1735073781735/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
+  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1735085375260/work' to '/opt/conda/conda-bld/crux-toolkit_1735085375260/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
+  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1735085375260/work, dest=/opt/conda/conda-bld/crux-toolkit_1735085375260/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
   Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
   Solving environment (_test_env): ...working... done
 
   ## Package Plan ##
 
-    environment location: /opt/conda/conda-bld/crux-toolkit_1735073781735/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+    environment location: /opt/conda/conda-bld/crux-toolkit_1735085375260/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
 
 
   The following NEW packages will be INSTALLED:
@@ -71,8 +71,8 @@ log: |-
   Preparing transaction: ...working... done
   Verifying transaction: ...working... done
   Executing transaction: ...working... done
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735073781735/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735073781735/test_tmp
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1735085375260/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1735085375260/test_tmp
    crux version
   crux: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
   WARNING: Tests failed for crux-toolkit-4.2-h9ee0642_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
@@ -83,7 +83,7 @@ log: |-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1735073781735/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1735085375260/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
 
   During handling of the above exception, another exception occurred:
 
