[ci skip] add build failure record for recipe recipes/crux-toolkit

diff --git a/recipes/crux-toolkit/build_failure.linux-64.yaml b/recipes/crux-toolkit/build_failure.linux-64.yaml
--- a/recipes/crux-toolkit/build_failure.linux-64.yaml
+++ b/recipes/crux-toolkit/build_failure.linux-64.yaml
@@ -1,7 +1,8 @@
-recipe_sha: d608d53be38cd889ad0d8d9f58673af0c82c72a54f7e0d9edf2bc46318e93911  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 3ccf0ee1f0ff224268cc14f8b418c01ff85490ef4ad1f9d8b0c0e8d72e20901f  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      - crux version | grep -q 'Crux version'
+    commands:
+      - crux version
   about:
     dev_url: https://github.com/crux-toolkit/crux-toolkit
     home: http://crux.ms
@@ -20,9 +21,9 @@ log: |2-
       - should_be_noarch_generic
 
 
-  source tree in: /opt/conda/conda-bld/crux-toolkit_1733199061404/work
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733199061404/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733199061404/work
+  source tree in: /opt/conda/conda-bld/crux-toolkit_1733199465146/work
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733199465146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733199465146/work
 
   Resource usage statistics from building crux-toolkit:
      Process count: 1
@@ -35,7 +36,7 @@ log: |2-
   Packaging crux-toolkit
   Packaging crux-toolkit-4.2-h9ee0642_0
   number of files: 1
-  WARNING :: get_rpaths_raw()=[] and patchelf=[''] disagree for /opt/conda/conda-bld/crux-toolkit_1733199061404/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/crux ::
+  WARNING :: get_rpaths_raw()=[] and patchelf=[''] disagree for /opt/conda/conda-bld/crux-toolkit_1733199465146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/crux ::
   WARNING (crux-toolkit,bin/crux): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.
   .. is this binary repackaging?
   WARNING (crux-toolkit,bin/crux): /lib64/libstdc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
@@ -53,14 +54,14 @@ log: |2-
           0 replacements in 0 files was 0.05 seconds
   WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
   TEST START: /opt/conda/conda-bld/linux-64/crux-toolkit-4.2-h9ee0642_0.tar.bz2
-  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1733199061404/work' to '/opt/conda/conda-bld/crux-toolkit_1733199061404/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
-  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1733199061404/work, dest=/opt/conda/conda-bld/crux-toolkit_1733199061404/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
+  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1733199465146/work' to '/opt/conda/conda-bld/crux-toolkit_1733199465146/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
+  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1733199465146/work, dest=/opt/conda/conda-bld/crux-toolkit_1733199465146/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
   Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
   Solving environment (_test_env): ...working... done
 
   ## Package Plan ##
 
-    environment location: /opt/conda/conda-bld/crux-toolkit_1733199061404/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+    environment location: /opt/conda/conda-bld/crux-toolkit_1733199465146/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
 
 
   The following NEW packages will be INSTALLED:
@@ -70,10 +71,9 @@ log: |2-
   Preparing transaction: ...working... done
   Verifying transaction: ...working... done
   Executing transaction: ...working... done
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733199061404/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733199061404/test_tmp
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733199465146/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733199465146/test_tmp
    crux version
-   grep -q 'Crux version'
   crux: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
   WARNING: Tests failed for crux-toolkit-4.2-h9ee0642_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
   Traceback (most recent call last):
@@ -83,7 +83,7 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1733199061404/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1733199465146/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
 
   During handling of the above exception, another exception occurred:
 
