[ci skip] add build failure record for recipe recipes/crux-toolkit

diff --git a/recipes/crux-toolkit/build_failure.linux-64.yaml b/recipes/crux-toolkit/build_failure.linux-64.yaml
--- a/recipes/crux-toolkit/build_failure.linux-64.yaml
+++ b/recipes/crux-toolkit/build_failure.linux-64.yaml
@@ -1,27 +1,24 @@
-recipe_sha: 8ae5a22f3b4c0ccd607f21e4a2e858ab70f9c6a1a6a52c8390fdb6a5744a8ce8  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: a5552ddb941918345285ba199c6cb464c3a16fe8ec021df499ce7c58041bcfbf  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |-
-  about:
-    dev_url: https://github.com/crux-toolkit/crux-toolkit
-    home: http://crux.ms
-    license: Apache-2.0
-    license_family: Apache
-    summary: A cross-platform suite of analysis tools for interpreting protein mass
-      spectrometry data
-  extra:
-    copy_test_source_files: true
-    final: true
-    recipe-maintainers:
-      - CharlesEGrant
-      - wsnoble
-      - acquayefrank
-    skip-lints:
-      - should_be_noarch_generic
-
-
-  source tree in: /opt/conda/conda-bld/crux-toolkit_1733279250090/work
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733279250090/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733279250090/work
+  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
+  CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
+  DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/crux-toolkit-4.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
+  GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
+  GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
+  GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
+  GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
+  host_alias=x86_64-conda-linux-gnu
+  HOST=x86_64-conda-linux-gnu
+  LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
+  MESON_ARGS=-Dbuildtype=release --prefix=$PREFIX -Dlibdir=lib
+  INFO: activate-gxx_linux-64.sh made the following environmental changes:
+  CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/crux-toolkit-4.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
+  CXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
+  DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/crux-toolkit-4.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
 
   Resource usage statistics from building crux-toolkit:
      Process count: 2
@@ -32,50 +29,53 @@ log: |-
 
 
   Packaging crux-toolkit
-  Packaging crux-toolkit-4.2-h9ee0642_0
+  Packaging crux-toolkit-4.2-hdbdd923_0
   number of files: 1
-  WARNING :: get_rpaths_raw()=[] and patchelf=[''] disagree for /opt/conda/conda-bld/crux-toolkit_1733279250090/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/crux ::
-  WARNING (crux-toolkit,bin/crux): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): /lib64/libstdc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): /lib64/libm.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): $RPATH/libgomp.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): /lib64/libgcc_s.so.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
-  WARNING (crux-toolkit,bin/crux): /lib64/libc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
-  .. is this binary repackaging?
+  WARNING :: get_rpaths_raw()=[] and patchelf=[''] disagree for /opt/conda/conda-bld/crux-toolkit_1733283272878/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/crux ::
+     INFO: sysroot: '/opt/conda/conda-bld/crux-toolkit_1733283272878/_build_env/x86_64-conda-linux-gnu/sysroot/' files: '['usr/share/zoneinfo', 'usr/share/locale/zh_TW/LC_MESSAGES/libc.mo', 'usr/share/locale/zh_CN/LC_MESSAGES/libc.mo', 'usr/share/locale/vi/LC_MESSAGES/libc.mo']'
+     INFO (crux-toolkit,bin/crux): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libpthread.so.0 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.17=h4a8ded7_18
+     INFO (crux-toolkit,bin/crux): Needed DSO lib/libstdc.so.6 found in conda-forge/linux-64::libstdcxx==14.2.0=hc0a3c3a_1
+     INFO (crux-toolkit,bin/crux): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libm.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.17=h4a8ded7_18
+  WARNING (crux-toolkit,bin/crux): Needed DSO lib/libgomp.so.1 found in ['conda-forge/linux-64::_openmp_mutex==4.5=2_gnu']
+  WARNING (crux-toolkit,bin/crux): .. but ['conda-forge/linux-64::_openmp_mutex==4.5=2_gnu'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
+     INFO (crux-toolkit,bin/crux): Needed DSO lib/libgcc_s.so.1 found in conda-forge/linux-64::libgcc==14.2.0=h77fa898_1
+     INFO (crux-toolkit,bin/crux): Needed DSO x86_64-conda-linux-gnu/sysroot/lib64/libc.so.6 found in CDT/compiler package conda-forge/noarch::sysroot_linux-64==2.17=h4a8ded7_18
   Fixing permissions
   INFO :: Time taken to mark (prefix)
-          0 replacements in 0 files was 0.03 seconds
+          0 replacements in 0 files was 0.06 seconds
   WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
-  TEST START: /opt/conda/conda-bld/linux-64/crux-toolkit-4.2-h9ee0642_0.tar.bz2
-  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1733279250090/work' to '/opt/conda/conda-bld/crux-toolkit_1733279250090/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
-  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1733279250090/work, dest=/opt/conda/conda-bld/crux-toolkit_1733279250090/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
+  TEST START: /opt/conda/conda-bld/linux-64/crux-toolkit-4.2-hdbdd923_0.tar.bz2
+  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1733283272878/work' to '/opt/conda/conda-bld/crux-toolkit_1733283272878/work_moved_crux-toolkit-4.2-hdbdd923_0_linux-64'
+  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1733283272878/work, dest=/opt/conda/conda-bld/crux-toolkit_1733283272878/work_moved_crux-toolkit-4.2-hdbdd923_0_linux-64)
   Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
   Solving environment (_test_env): ...working... done
 
   ## Package Plan ##
 
-    environment location: /opt/conda/conda-bld/crux-toolkit_1733279250090/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+    environment location: /opt/conda/conda-bld/crux-toolkit_1733283272878/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
 
 
   The following NEW packages will be INSTALLED:
 
       _libgcc_mutex: 0.1-conda_forge   conda-forge
-      crux-toolkit:  4.2-h9ee0642_0    local
+      _openmp_mutex: 4.5-2_gnu         conda-forge
+      crux-toolkit:  4.2-hdbdd923_0    local
+      libgcc:        14.2.0-h77fa898_1 conda-forge
       libgomp:       14.2.0-h77fa898_1 conda-forge
+      libstdcxx:     14.2.0-hc0a3c3a_1 conda-forge
 
   Preparing transaction: ...working... done
   Verifying transaction: ...working... done
   Executing transaction: ...working... done
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733279250090/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733279250090/test_tmp
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733283272878/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733283272878/test_tmp
    crux version
-  crux: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
-  WARNING: Tests failed for crux-toolkit-4.2-h9ee0642_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
+  crux: /lib64/libm.so.6: version GLIBC_2.27' not found (required by crux)
+  crux: /lib64/libm.so.6: version GLIBC_2.29' not found (required by crux)
+  crux: /lib64/libc.so.6: version GLIBC_2.25' not found (required by crux)
+  crux: /lib64/libc.so.6: version GLIBC_2.27' not found (required by crux)
+  crux: /lib64/libc.so.6: version GLIBC_2.28' not found (required by crux)
+  WARNING: Tests failed for crux-toolkit-4.2-hdbdd923_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
   Traceback (most recent call last):
     File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3523, in test
       utils.check_call_env(
@@ -83,7 +83,7 @@ log: |-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1733279250090/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1733283272878/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
 
   During handling of the above exception, another exception occurred:
 
@@ -100,5 +100,5 @@ log: |-
       tests_failed(
     File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3584, in tests_failed
       raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
-  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: crux-toolkit-4.2-h9ee0642_0.tar.bz2
+  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: crux-toolkit-4.2-hdbdd923_0.tar.bz2
 # Last 100 lines of the build log.
