[ci skip] add build failure record for recipe recipes/crux-toolkit

diff --git a/recipes/crux-toolkit/build_failure.linux-64.yaml b/recipes/crux-toolkit/build_failure.linux-64.yaml
--- a/recipes/crux-toolkit/build_failure.linux-64.yaml
+++ b/recipes/crux-toolkit/build_failure.linux-64.yaml
@@ -1,8 +1,6 @@
-recipe_sha: 3ccf0ee1f0ff224268cc14f8b418c01ff85490ef4ad1f9d8b0c0e8d72e20901f  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 8ae5a22f3b4c0ccd607f21e4a2e858ab70f9c6a1a6a52c8390fdb6a5744a8ce8  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-    commands:
-      - crux version
+log: |-
   about:
     dev_url: https://github.com/crux-toolkit/crux-toolkit
     home: http://crux.ms
@@ -21,14 +19,14 @@ log: |2-
       - should_be_noarch_generic
 
 
-  source tree in: /opt/conda/conda-bld/crux-toolkit_1733199465146/work
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733199465146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733199465146/work
+  source tree in: /opt/conda/conda-bld/crux-toolkit_1733202137712/work
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733202137712/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733202137712/work
 
   Resource usage statistics from building crux-toolkit:
-     Process count: 1
-     CPU time: Sys=-, User=-
-     Memory: 192.0K
+     Process count: 2
+     CPU time: Sys=-, User=0:00:00.0
+     Memory: 10.9M
      Disk usage: 120.9K
      Time elapsed: 0:00:02.0
 
@@ -36,7 +34,7 @@ log: |2-
   Packaging crux-toolkit
   Packaging crux-toolkit-4.2-h9ee0642_0
   number of files: 1
-  WARNING :: get_rpaths_raw()=[] and patchelf=[''] disagree for /opt/conda/conda-bld/crux-toolkit_1733199465146/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/crux ::
+  WARNING :: get_rpaths_raw()=[] and patchelf=[''] disagree for /opt/conda/conda-bld/crux-toolkit_1733202137712/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/crux ::
   WARNING (crux-toolkit,bin/crux): /lib64/libpthread.so.0 not found in packages, sysroot(s) nor the missing_dso_whitelist.
   .. is this binary repackaging?
   WARNING (crux-toolkit,bin/crux): /lib64/libstdc.so.6 not found in packages, sysroot(s) nor the missing_dso_whitelist.
@@ -51,28 +49,30 @@ log: |2-
   .. is this binary repackaging?
   Fixing permissions
   INFO :: Time taken to mark (prefix)
-          0 replacements in 0 files was 0.05 seconds
+          0 replacements in 0 files was 0.04 seconds
   WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
   TEST START: /opt/conda/conda-bld/linux-64/crux-toolkit-4.2-h9ee0642_0.tar.bz2
-  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1733199465146/work' to '/opt/conda/conda-bld/crux-toolkit_1733199465146/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
-  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1733199465146/work, dest=/opt/conda/conda-bld/crux-toolkit_1733199465146/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
+  Renaming work directory '/opt/conda/conda-bld/crux-toolkit_1733202137712/work' to '/opt/conda/conda-bld/crux-toolkit_1733202137712/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64'
+  shutil.move(work)=/opt/conda/conda-bld/crux-toolkit_1733202137712/work, dest=/opt/conda/conda-bld/crux-toolkit_1733202137712/work_moved_crux-toolkit-4.2-h9ee0642_0_linux-64)
   Reloading output folder (local, file:///opt/host-conda-bld): ...working... done
   Solving environment (_test_env): ...working... done
 
   ## Package Plan ##
 
-    environment location: /opt/conda/conda-bld/crux-toolkit_1733199465146/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+    environment location: /opt/conda/conda-bld/crux-toolkit_1733202137712/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
 
 
   The following NEW packages will be INSTALLED:
 
-      crux-toolkit: 4.2-h9ee0642_0 local
+      _libgcc_mutex: 0.1-conda_forge   conda-forge
+      crux-toolkit:  4.2-h9ee0642_0    local
+      libgomp:       14.2.0-h77fa898_1 conda-forge
 
   Preparing transaction: ...working... done
   Verifying transaction: ...working... done
   Executing transaction: ...working... done
-  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733199465146/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733199465146/test_tmp
+  export PREFIX=/opt/conda/conda-bld/crux-toolkit_1733202137712/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export SRC_DIR=/opt/conda/conda-bld/crux-toolkit_1733202137712/test_tmp
    crux version
   crux: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory
   WARNING: Tests failed for crux-toolkit-4.2-h9ee0642_0.tar.bz2 - moving package to /opt/conda/conda-bld/broken
@@ -83,7 +83,7 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1733199465146/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/crux-toolkit_1733202137712/test_tmp/conda_test_runner.sh']' returned non-zero exit status 127.
 
   During handling of the above exception, another exception occurred:
 
