[ci skip] add build failure record for recipe recipes/pegasuspy

diff --git a/recipes/pegasuspy/build_failure.linux-64.yaml b/recipes/pegasuspy/build_failure.linux-64.yaml
--- a/recipes/pegasuspy/build_failure.linux-64.yaml
+++ b/recipes/pegasuspy/build_failure.linux-64.yaml
@@ -1,30 +1,29 @@
-recipe_sha: 5572602fd0167b318f20c569dc773ff917aa2215099fa41022569746cc3dcd1e  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: a78f413d7ca12be42eccc00326a8d19d2868fb530d5c166729fe80ac3bf58b37  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      pthread-stubs:             0.4-hb9d3cd8_1002                 conda-forge
       pybind11:                  3.0.2-pyh7a1b43c_0                conda-forge
       pybind11-abi:              11-hc364b38_1                     conda-forge
       pybind11-global:           3.0.2-pyhc7ab6ef_0                conda-forge
-      pyfit-sne:                 1.2.1-py310h6fadb43_5             conda-forge
+      pyfit-sne:                 1.2.1-py311h5819cc7_5             conda-forge
       pynndescent:               0.5.13-pyhd8ed1ab_1               conda-forge
       pyparsing:                 3.3.2-pyhcf101f3_0                conda-forge
-      python:                    3.10.19-h3c07f61_3_cpython        conda-forge
+      python:                    3.11.14-hd63d673_3_cpython        conda-forge
       python-dateutil:           2.9.0.post0-pyhe01879c_2          conda-forge
-      python-igraph:             0.11.9-py310hea6c23e_3            conda-forge
+      python-igraph:             0.11.9-py311h1ddb823_3            conda-forge
       python-tzdata:             2025.3-pyhd8ed1ab_0               conda-forge
-      python_abi:                3.10-8_cp310                      conda-forge
-      pytorch:                   2.10.0-cpu_mkl_py310_hf1dacaf_102 conda-forge
+      python_abi:                3.11-8_cp311                      conda-forge
+      pytorch:                   2.10.0-cpu_mkl_py311_h3da180d_102 conda-forge
       pytz:                      2025.2-pyhd8ed1ab_0               conda-forge
       qhull:                     2020.2-h434a139_5                 conda-forge
       readline:                  8.3-h853b02a_0                    conda-forge
-      scikit-learn:              1.7.2-py310h228f341_0             conda-forge
-      scikit-misc:               0.5.2-py310h18bf74c_0             conda-forge
-      scipy:                     1.15.2-py310h1d65ade_0            conda-forge
+      scikit-learn:              1.8.0-np2py311ha15b03d_1          conda-forge
+      scikit-misc:               0.5.2-py311h262f814_0             conda-forge
+      scipy:                     1.16.3-py311hbe70eeb_2            conda-forge
       seaborn-base:              0.13.2-pyhd8ed1ab_3               conda-forge
       setuptools:                82.0.0-pyh332efcf_0               conda-forge
       six:                       1.17.0-pyhe01879c_1               conda-forge
       sleef:                     3.9.0-ha0421bc_0                  conda-forge
-      statsmodels:               0.14.6-py310hf779ad0_0            conda-forge
+      statsmodels:               0.14.6-py311h0372a8f_0            conda-forge
       sympy:                     1.14.0-pyh2585a3b_105             conda-forge
       tbb:                       2022.3.0-hb700be7_2               conda-forge
       texttable:                 1.7.0-pyhd8ed1ab_1                conda-forge
@@ -34,10 +33,11 @@ log: |2-
       typing-extensions:         4.15.0-h396c80c_0                 conda-forge
       typing_extensions:         4.15.0-pyhcf101f3_0               conda-forge
       tzdata:                    2025c-hc9c84f9_1                  conda-forge
-      umap-learn:                0.5.11-py310hff52083_0            conda-forge
-      unicodedata2:              17.0.1-py310h7c4b9e2_0            conda-forge
+      umap-learn:                0.5.11-py311h38be061_0            conda-forge
+      unicodedata2:              17.0.1-py311h49ec1c0_0            conda-forge
       wheel:                     0.46.3-pyhd8ed1ab_0               conda-forge
-      wordcloud:                 1.9.6-py310h7c4b9e2_0             conda-forge
+      wordcloud:                 1.9.6-py311h49ec1c0_0             conda-forge
+      wrapt:                     2.1.1-py311h49ec1c0_0             conda-forge
       xlsxwriter:                3.2.9-pyhd8ed1ab_0                conda-forge
       xorg-libice:               1.1.2-hb9d3cd8_0                  conda-forge
       xorg-libsm:                1.2.6-he73a12e_0                  conda-forge
@@ -51,7 +51,7 @@ log: |2-
       xorg-libxrender:           0.9.12-hb9d3cd8_0                 conda-forge
       xorg-libxt:                1.3.1-hb9d3cd8_0                  conda-forge
       xorg-libxtst:              1.2.5-hb9d3cd8_3                  conda-forge
-      zarr:                      2.18.3-pyhd8ed1ab_1               conda-forge
+      zarr:                      2.18.7-pyhd8ed1ab_0               conda-forge
       zipp:                      3.23.0-pyhcf101f3_1               conda-forge
       zlib-ng:                   2.3.3-hceb46e0_1                  conda-forge
       zstd:                      1.5.7-hb78ec9c_6                  conda-forge
@@ -59,20 +59,20 @@ log: |2-
   Preparing transaction: ...working... done
   Verifying transaction: ...working... done
   Executing transaction: ...working... done
-  export PREFIX=/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
-  export SRC_DIR=/opt/conda/conda-bld/pegasuspy_1771625559930/test_tmp
-  import: 'pegasus'
+  export PREFIX=/opt/conda/conda-bld/pegasuspy_1771869491367/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
+  export SRC_DIR=/opt/conda/conda-bld/pegasuspy_1771869491367/test_tmp
   Traceback (most recent call last):
-    File "/opt/conda/conda-bld/pegasuspy_1771625559930/test_tmp/run_test.py", line 2, in <module>
+    File "/opt/conda/conda-bld/pegasuspy_1771869491367/test_tmp/run_test.py", line 2, in <module>
+  import: 'pegasus'
       import pegasus
-    File "/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/pegasus/__init__.py", line 27, in <module>
+    File "/opt/conda/conda-bld/pegasuspy_1771869491367/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.11/site-packages/pegasus/__init__.py", line 27, in <module>
       from .tools import (
-    File "/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/pegasus/tools/__init__.py", line 1, in <module>
+    File "/opt/conda/conda-bld/pegasuspy_1771869491367/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.11/site-packages/pegasus/tools/__init__.py", line 1, in <module>
       from .utils import (
-    File "/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/pegasus/tools/utils.py", line 195, in <module>
+    File "/opt/conda/conda-bld/pegasuspy_1771869491367/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.11/site-packages/pegasus/tools/utils.py", line 195, in <module>
       import pkg_resources
   ModuleNotFoundError: No module named 'pkg_resources'
-  WARNING: Tests failed for pegasuspy-1.10.2-py310h7c10099_1.conda - moving package to /opt/conda/conda-bld/broken
+  WARNING: Tests failed for pegasuspy-1.10.2-py311h26ae33e_1.conda - moving package to /opt/conda/conda-bld/broken
   Traceback (most recent call last):
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3497, in test
       utils.check_call_env(
@@ -81,7 +81,7 @@ log: |2-
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/pegasuspy_1771625559930/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/pegasuspy_1771869491367/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
 
   During handling of the above exception, another exception occurred:
 
@@ -100,5 +100,5 @@ log: |2-
       tests_failed(
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3558, in tests_failed
       raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
-  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: pegasuspy-1.10.2-py310h7c10099_1.conda
+  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: pegasuspy-1.10.2-py311h26ae33e_1.conda
 # Last 100 lines of the build log.
