[ci skip] add build failure record for recipe recipes/pegasuspy

diff --git a/recipes/pegasuspy/build_failure.linux-64.yaml b/recipes/pegasuspy/build_failure.linux-64.yaml
--- a/recipes/pegasuspy/build_failure.linux-64.yaml
+++ b/recipes/pegasuspy/build_failure.linux-64.yaml
@@ -1,104 +1,104 @@
-recipe_sha: 05082896c9d683a434792cca2bd6d16d300fc5b53d6394f597ea86b8740add13  # The hash of the recipe's meta.yaml at which this recipe failed to build.
-skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
+recipe_sha: 5572602fd0167b318f20c569dc773ff917aa2215099fa41022569746cc3dcd1e  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("scikit-misc==0.1.4=py310h19f2f35_1"), MatchSpec("python_abi=3.10[build=*_cp310]")}
-  Encountered problems while solving:
-    - package scikit-misc-0.1.4-py310h19f2f35_1 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
+      pthread-stubs:             0.4-hb9d3cd8_1002                 conda-forge
+      pybind11:                  3.0.2-pyh7a1b43c_0                conda-forge
+      pybind11-abi:              11-hc364b38_1                     conda-forge
+      pybind11-global:           3.0.2-pyhc7ab6ef_0                conda-forge
+      pyfit-sne:                 1.2.1-py310h6fadb43_5             conda-forge
+      pynndescent:               0.5.13-pyhd8ed1ab_1               conda-forge
+      pyparsing:                 3.3.2-pyhcf101f3_0                conda-forge
+      python:                    3.10.19-h3c07f61_3_cpython        conda-forge
+      python-dateutil:           2.9.0.post0-pyhe01879c_2          conda-forge
+      python-igraph:             0.11.9-py310hea6c23e_3            conda-forge
+      python-tzdata:             2025.3-pyhd8ed1ab_0               conda-forge
+      python_abi:                3.10-8_cp310                      conda-forge
+      pytorch:                   2.10.0-cpu_mkl_py310_hf1dacaf_102 conda-forge
+      pytz:                      2025.2-pyhd8ed1ab_0               conda-forge
+      qhull:                     2020.2-h434a139_5                 conda-forge
+      readline:                  8.3-h853b02a_0                    conda-forge
+      scikit-learn:              1.7.2-py310h228f341_0             conda-forge
+      scikit-misc:               0.5.2-py310h18bf74c_0             conda-forge
+      scipy:                     1.15.2-py310h1d65ade_0            conda-forge
+      seaborn-base:              0.13.2-pyhd8ed1ab_3               conda-forge
+      setuptools:                82.0.0-pyh332efcf_0               conda-forge
+      six:                       1.17.0-pyhe01879c_1               conda-forge
+      sleef:                     3.9.0-ha0421bc_0                  conda-forge
+      statsmodels:               0.14.6-py310hf779ad0_0            conda-forge
+      sympy:                     1.14.0-pyh2585a3b_105             conda-forge
+      tbb:                       2022.3.0-hb700be7_2               conda-forge
+      texttable:                 1.7.0-pyhd8ed1ab_1                conda-forge
+      threadpoolctl:             3.6.0-pyhecae5ae_0                conda-forge
+      tk:                        8.6.13-noxft_h366c992_103         conda-forge
+      tqdm:                      4.67.3-pyh8f84b5b_0               conda-forge
+      typing-extensions:         4.15.0-h396c80c_0                 conda-forge
+      typing_extensions:         4.15.0-pyhcf101f3_0               conda-forge
+      tzdata:                    2025c-hc9c84f9_1                  conda-forge
+      umap-learn:                0.5.11-py310hff52083_0            conda-forge
+      unicodedata2:              17.0.1-py310h7c4b9e2_0            conda-forge
+      wheel:                     0.46.3-pyhd8ed1ab_0               conda-forge
+      wordcloud:                 1.9.6-py310h7c4b9e2_0             conda-forge
+      xlsxwriter:                3.2.9-pyhd8ed1ab_0                conda-forge
+      xorg-libice:               1.1.2-hb9d3cd8_0                  conda-forge
+      xorg-libsm:                1.2.6-he73a12e_0                  conda-forge
+      xorg-libx11:               1.8.13-he1eb515_0                 conda-forge
+      xorg-libxau:               1.0.12-hb03c661_1                 conda-forge
+      xorg-libxdmcp:             1.1.5-hb03c661_1                  conda-forge
+      xorg-libxext:              1.3.7-hb03c661_0                  conda-forge
+      xorg-libxfixes:            6.0.2-hb03c661_0                  conda-forge
+      xorg-libxi:                1.8.2-hb9d3cd8_0                  conda-forge
+      xorg-libxrandr:            1.5.5-hb03c661_0                  conda-forge
+      xorg-libxrender:           0.9.12-hb9d3cd8_0                 conda-forge
+      xorg-libxt:                1.3.1-hb9d3cd8_0                  conda-forge
+      xorg-libxtst:              1.2.5-hb9d3cd8_3                  conda-forge
+      zarr:                      2.18.3-pyhd8ed1ab_1               conda-forge
+      zipp:                      3.23.0-pyhcf101f3_1               conda-forge
+      zlib-ng:                   2.3.3-hceb46e0_1                  conda-forge
+      zstd:                      1.5.7-hb78ec9c_6                  conda-forge
 
-  Could not solve for environment specs
-  The following packages are incompatible
-   [32mpython_abi 3.12.* *_cp312[0m is requested and can be installed;
-   [31mscikit-misc[0m is not installable because there are no viable options
-      [31mscikit-misc 0.1.3[0m would require
-        [31mpython_abi 3.6 *_pypy36_pp73[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.3[0m would require
-        [31mpython_abi 3.6.* *_cp36m[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.7.* *_cp37m[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.7 *_pypy37_pp73[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.8.* *_cp38[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.9.* *_cp39[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-        [31mpython_abi 3.10.* *_cp310[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-        [31mpython_abi 3.11.* *_cp311[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-        [31mpython_abi 3.8 *_pypy38_pp73[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-         [31mpython_abi 3.9 *_pypy39_pp73[0m, which conflicts with any installable versions previously reported.
+  Preparing transaction: ...working... done
+  Verifying transaction: ...working... done
+  Executing transaction: ...working... done
+  export PREFIX=/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
+  export SRC_DIR=/opt/conda/conda-bld/pegasuspy_1771625559930/test_tmp
+  import: 'pegasus'
+  Traceback (most recent call last):
+    File "/opt/conda/conda-bld/pegasuspy_1771625559930/test_tmp/run_test.py", line 2, in <module>
+      import pegasus
+    File "/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/pegasus/__init__.py", line 27, in <module>
+      from .tools import (
+    File "/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/pegasus/tools/__init__.py", line 1, in <module>
+      from .utils import (
+    File "/opt/conda/conda-bld/pegasuspy_1771625559930/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.10/site-packages/pegasus/tools/utils.py", line 195, in <module>
+      import pkg_resources
+  ModuleNotFoundError: No module named 'pkg_resources'
+  WARNING: Tests failed for pegasuspy-1.10.2-py310h7c10099_1.conda - moving package to /opt/conda/conda-bld/broken
+  Traceback (most recent call last):
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3497, in test
+      utils.check_call_env(
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 411, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/pegasuspy_1771625559930/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
 
   During handling of the above exception, another exception occurred:
 
   Traceback (most recent call last):
     File "/opt/conda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
+               ^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
       api.build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
       return build_tree(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
-      packages_from_this = build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2409, in build
-      create_build_envs(top_level_pkg, notest)
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2247, in create_build_envs
-      raise e
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2220, in create_build_envs
-      environ.get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 937, in get_install_actions
-      precs = get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 937, in get_install_actions
-      precs = get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 937, in get_install_actions
-      precs = get_package_records(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 891, in get_install_actions
-      precs = _install_actions(prefix, index, specs)["LINK"]
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1301, in install_actions
-      txn = solver.solve_for_transaction(prune=False, ignore_pinned=False)
-    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 153, in solve_for_transaction
-      unlink_precs, link_precs = self.solve_for_diff(
-    File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 222, in solve_for_diff
-      final_precs = self.solve_final_state(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 223, in solve_final_state
-      out_state = self._solving_loop(in_state, out_state, index)
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 303, in _solving_loop
-      solved = self._solve_attempt(in_state, out_state, index, attempt=attempt)
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 414, in _solve_attempt
-      new_conflicts = self._maybe_raise_for_problems(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
-      self._maybe_raise_for_conda_build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("scikit-misc==0.1.4=py310h19f2f35_1"), MatchSpec("python_abi=3.10[build=*_cp310]")}
-  Encountered problems while solving:
-    - package scikit-misc-0.1.4-py310h19f2f35_1 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
-
-  Could not solve for environment specs
-  The following packages are incompatible
-   [32mpython_abi 3.12.* *_cp312[0m is requested and can be installed;
-   [31mscikit-misc[0m is not installable because there are no viable options
-      [31mscikit-misc 0.1.3[0m would require
-        [31mpython_abi 3.6 *_pypy36_pp73[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.3[0m would require
-        [31mpython_abi 3.6.* *_cp36m[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.7.* *_cp37m[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.7 *_pypy37_pp73[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.8.* *_cp38[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc [0.1.3|0.1.4][0m would require
-        [31mpython_abi 3.9.* *_cp39[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-        [31mpython_abi 3.10.* *_cp310[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-        [31mpython_abi 3.11.* *_cp311[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-        [31mpython_abi 3.8 *_pypy38_pp73[0m, which conflicts with any installable versions previously reported;
-      [31mscikit-misc 0.1.4[0m would require
-         [31mpython_abi 3.9 *_pypy39_pp73[0m, which conflicts with any installable versions previously reported.
+             ^^^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3684, in build_tree
+      test(pkg, config=metadata.config.copy(), stats=stats)
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3511, in test
+      tests_failed(
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3558, in tests_failed
+      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
+  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: pegasuspy-1.10.2-py310h7c10099_1.conda
 # Last 100 lines of the build log.
