[ci skip] add build failure record for recipe recipes/pegasuspy

diff --git a/recipes/pegasuspy/build_failure.osx-64.yaml b/recipes/pegasuspy/build_failure.osx-64.yaml
--- a/recipes/pegasuspy/build_failure.osx-64.yaml
+++ b/recipes/pegasuspy/build_failure.osx-64.yaml
@@ -1,104 +1,104 @@
-recipe_sha: 05082896c9d683a434792cca2bd6d16d300fc5b53d6394f597ea86b8740add13  # The hash of the recipe's meta.yaml at which this recipe failed to build.
-skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
+recipe_sha: 5572602fd0167b318f20c569dc773ff917aa2215099fa41022569746cc3dcd1e  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {MatchSpec("python_abi=3.10[build=*_cp310]"), MatchSpec("scikit-misc==0.1.4=py310h50c80d6_2")}
-  Encountered problems while solving:
-    - package scikit-misc-0.1.4-py310h50c80d6_2 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
+      patsy:                     1.0.2-pyhcf101f3_0                  conda-forge
+      pegasusio:                 0.10.0-py311h3d978dd_0              bioconda
+      pegasuspy:                 1.10.2-py311h90b0f9e_1              local
+      pillow:                    12.1.1-py311h127dec8_0              conda-forge
+      pip:                       26.0.1-pyh8b19718_0                 conda-forge
+      psutil:                    7.2.2-py311ha332486_0               conda-forge
+      pthread-stubs:             0.4-h00291cd_1002                   conda-forge
+      pybind11:                  3.0.2-pyh7a1b43c_0                  conda-forge
+      pybind11-abi:              11-hc364b38_1                       conda-forge
+      pybind11-global:           3.0.2-pyhc7ab6ef_0                  conda-forge
+      pyfit-sne:                 1.2.1-py311h17bf195_5               conda-forge
+      pynndescent:               0.5.13-pyhd8ed1ab_1                 conda-forge
+      pyparsing:                 3.3.2-pyhcf101f3_0                  conda-forge
+      python:                    3.11.14-h74c2667_3_cpython          conda-forge
+      python-dateutil:           2.9.0.post0-pyhe01879c_2            conda-forge
+      python-igraph:             0.11.9-py311h11ccb26_3              conda-forge
+      python-tzdata:             2025.3-pyhd8ed1ab_0                 conda-forge
+      python_abi:                3.11-8_cp311                        conda-forge
+      pytorch:                   2.10.0-cpu_generic_py311_hb8101d3_2 conda-forge
+      pytz:                      2025.2-pyhd8ed1ab_0                 conda-forge
+      qhull:                     2020.2-h3c5361c_5                   conda-forge
+      readline:                  8.3-h68b038d_0                      conda-forge
+      scikit-learn:              1.8.0-np2py311heeb2b4f_1            conda-forge
+      scikit-misc:               0.5.2-py311hf0ce567_0               conda-forge
+      scipy:                     1.16.3-py311hd77d3c2_2              conda-forge
+      seaborn-base:              0.13.2-pyhd8ed1ab_3                 conda-forge
+      setuptools:                82.0.0-pyh332efcf_0                 conda-forge
+      six:                       1.17.0-pyhe01879c_1                 conda-forge
+      sleef:                     3.9.0-h289094c_0                    conda-forge
+      statsmodels:               0.14.6-py311ha837bc1_0              conda-forge
+      sympy:                     1.14.0-pyh2585a3b_105               conda-forge
+      tbb:                       2022.3.0-h06b67a2_2                 conda-forge
+      texttable:                 1.7.0-pyhd8ed1ab_1                  conda-forge
+      threadpoolctl:             3.6.0-pyhecae5ae_0                  conda-forge
+      tk:                        8.6.13-h7142dee_3                   conda-forge
+      tqdm:                      4.67.3-pyh8f84b5b_0                 conda-forge
+      typing-extensions:         4.15.0-h396c80c_0                   conda-forge
+      typing_extensions:         4.15.0-pyhcf101f3_0                 conda-forge
+      tzdata:                    2025c-hc9c84f9_1                    conda-forge
+      umap-learn:                0.5.11-py311h6eed73b_0              conda-forge
+      unicodedata2:              17.0.1-py311hc71d4c3_0              conda-forge
+      wheel:                     0.46.3-pyhd8ed1ab_0                 conda-forge
+      wordcloud:                 1.9.6-py311hc71d4c3_0               conda-forge
+      wrapt:                     2.1.1-py311hc71d4c3_0               conda-forge
+      xlsxwriter:                3.2.9-pyhd8ed1ab_0                  conda-forge
+      xorg-libxau:               1.0.12-h8616949_1                   conda-forge
+      xorg-libxdmcp:             1.1.5-h8616949_1                    conda-forge
+      zarr:                      2.18.7-pyhd8ed1ab_0                 conda-forge
+      zipp:                      3.23.0-pyhcf101f3_1                 conda-forge
+      zlib-ng:                   2.3.3-h8bce59a_1                    conda-forge
+      zstd:                      1.5.7-h3eecb57_6                    conda-forge
 
-  Could not solve for environment specs
-  The following packages are incompatible
-   python_abi 3.12.* *_cp312 is requested and can be installed;
-   scikit-misc is not installable because there are no viable options
-      scikit-misc 0.1.3 would require
-        python_abi 3.6 *_pypy36_pp73, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.3 would require
-        python_abi 3.6.* *_cp36m, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.7 *_pypy37_pp73, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-        python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-        python_abi 3.11.* *_cp311, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-        python_abi 3.8 *_pypy38_pp73, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-         python_abi 3.9 *_pypy39_pp73, which conflicts with any installable versions previously reported.
+  Preparing transaction: ...working... done
+  Verifying transaction: ...working... done
+  Executing transaction: ...working... done
+  /opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/environ.py:545: UserWarning: The environment variable 'SETUPTOOLS_SCM_PRETEND_VERSION' is being passed through with value '1.10.2'.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
+    warnings.warn(
+  Matplotlib is building the font cache; this may take a moment.
+  Traceback (most recent call last):
+    File "/opt/mambaforge/envs/bioconda/conda-bld/pegasuspy_1771629159537/test_tmp/run_test.py", line 2, in <module>
+      import pegasus
+    File "/opt/mambaforge/envs/bioconda/conda-bld/pegasuspy_1771629159537/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pegasus/__init__.py", line 27, in <module>
+      from .tools import (
+    File "/opt/mambaforge/envs/bioconda/conda-bld/pegasuspy_1771629159537/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pegasus/tools/__init__.py", line 1, in <module>
+      from .utils import (
+    File "/opt/mambaforge/envs/bioconda/conda-bld/pegasuspy_1771629159537/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pegasus/tools/utils.py", line 195, in <module>
+      import pkg_resources
+  ModuleNotFoundError: No module named 'pkg_resources'
+  WARNING: Tests failed for pegasuspy-1.10.2-py311h90b0f9e_1.conda - moving package to /opt/mambaforge/envs/bioconda/conda-bld/broken
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pegasuspy_1771629159537/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/pegasuspy_1771629159537/test_tmp
+  import: 'pegasus'
+  Traceback (most recent call last):
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3497, in test
+      utils.check_call_env(
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/utils.py", line 411, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/pegasuspy_1771629159537/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
 
   During handling of the above exception, another exception occurred:
 
   Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
+               ^^^^^^^^^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
       api.build(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
       return build_tree(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
-      packages_from_this = build(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2409, in build
-      create_build_envs(top_level_pkg, notest)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2247, in create_build_envs
-      raise e
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2220, in create_build_envs
-      environ.get_package_records(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/environ.py", line 937, in get_install_actions
-      precs = get_package_records(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/environ.py", line 937, in get_install_actions
-      precs = get_package_records(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/environ.py", line 937, in get_install_actions
-      precs = get_package_records(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/environ.py", line 891, in get_install_actions
-      precs = _install_actions(prefix, index, specs)["LINK"]
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/environ.py", line 1301, in install_actions
-      txn = solver.solve_for_transaction(prune=False, ignore_pinned=False)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda/core/solve.py", line 153, in solve_for_transaction
-      unlink_precs, link_precs = self.solve_for_diff(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda/core/solve.py", line 222, in solve_for_diff
-      final_precs = self.solve_final_state(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 223, in solve_final_state
-      out_state = self._solving_loop(in_state, out_state, index)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 303, in _solving_loop
-      solved = self._solve_attempt(in_state, out_state, index, attempt=attempt)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 414, in _solve_attempt
-      new_conflicts = self._maybe_raise_for_problems(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 712, in _maybe_raise_for_problems
-      self._maybe_raise_for_conda_build(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_libmamba_solver/solver.py", line 805, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: {MatchSpec("python_abi=3.10[build=*_cp310]"), MatchSpec("scikit-misc==0.1.4=py310h50c80d6_2")}
-  Encountered problems while solving:
-    - package scikit-misc-0.1.4-py310h50c80d6_2 requires python_abi 3.10.* *_cp310, but none of the providers can be installed
-
-  Could not solve for environment specs
-  The following packages are incompatible
-   python_abi 3.12.* *_cp312 is requested and can be installed;
-   scikit-misc is not installable because there are no viable options
-      scikit-misc 0.1.3 would require
-        python_abi 3.6 *_pypy36_pp73, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.3 would require
-        python_abi 3.6.* *_cp36m, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.7 *_pypy37_pp73, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.7.* *_cp37m, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
-      scikit-misc [0.1.3|0.1.4] would require
-        python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-        python_abi 3.10.* *_cp310, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-        python_abi 3.11.* *_cp311, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-        python_abi 3.8 *_pypy38_pp73, which conflicts with any installable versions previously reported;
-      scikit-misc 0.1.4 would require
-         python_abi 3.9 *_pypy39_pp73, which conflicts with any installable versions previously reported.
+             ^^^^^^^^^^^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3684, in build_tree
+      test(pkg, config=metadata.config.copy(), stats=stats)
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3511, in test
+      tests_failed(
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3558, in tests_failed
+      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
+  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: pegasuspy-1.10.2-py311h90b0f9e_1.conda
 # Last 100 lines of the build log.
