[ci skip] add build failure record for recipe recipes/primer3/1.1.4

diff --git a/recipes/primer3/1.1.4/build_failure.osx-64.yaml b/recipes/primer3/1.1.4/build_failure.osx-64.yaml
--- a/recipes/primer3/1.1.4/build_failure.osx-64.yaml
+++ b/recipes/primer3/1.1.4/build_failure.osx-64.yaml
@@ -1,49 +1,14 @@
-recipe_sha: eaf9d4523d645136c03e982cab06b7cdfd2b22f60c0904529a1481b40ff43aba  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 93dfcf7db4a226bcb2607e890ceb7098ad878d40e1669fefedc3f263a7abefdb  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
-      raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/primer3_1773690279865/work/conda_build.sh']' returned non-zero exit status 2.
-
-  The above exception was the direct cause of the following exception:
-
-  Traceback (most recent call last):
-      - cctools_impl_osx-64 1030.6.3 llvm19_1_h7d82c7c_4
-      - cctools 1030.6.3 llvm19_1_h67a6458_4
-    File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
-      sys.exit(execute())
-               ^^^^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
-      api.build(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
-      return build_tree(
-             ^^^^^^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3669, in build_tree
-      packages_from_this = build(
-                           ^^^^^^
-      - cctools_osx-64 1030.6.3 llvm19_1_h8f0d4bb_4
-      - compiler-rt_osx-64 19.1.7 h138dee1_1
-      - clang 19.1.7 default_h1323312_8
-      - compiler-rt 19.1.7 he914875_1
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
-      raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/primer3_1773690279865/work/conda_build.sh']' returned non-zero exit status 2.
-      - clang_impl_osx-64 19.1.7 default_ha1a018a_8
-      - clang_osx-64 19.1.7 h8a78ed7_31
-    run:
-      - perl
-  test:
-    commands:
-      - primer3_core --help 2>&1 | grep -F 'This is primer3'
-      - test -x "${PREFIX}/bin/long_seq_tm_test"
-      - test -x "${PREFIX}/bin/ntdpal"
-      - test -x "${PREFIX}/bin/oligotm"
-  about:
     home: http://primer3.sourceforge.net/
     license: GPLv2
     license_file: COPYING.txt
-    summary: Design PCR primers from DNA sequence. From mispriming libraries to sequence
-      quality data to the generation of internal oligos, primer3 does it.
+    summary: PCR primer design software
+    description: Design PCR primers from DNA sequence. From mispriming libraries to
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/utils.py", line 411, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+      sequence quality data to the generation of internal oligos, primer3 does it.
   extra:
     identifiers:
       - biotools:primer3
@@ -52,26 +17,61 @@ log: |2-
     copy_test_source_files: true
 
 
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/primer3_1773690279865/work
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/primer3_1773690279865/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/primer3_1773690279865/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/primer3_1773690279865/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/primer3_1776761438338/work
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/primer3_1776761438338/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/primer3_1776761438338/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/primer3_1776761438338/work
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/primer3_1776761438338/work/conda_build.sh']' returned non-zero exit status 2.
+
+  The above exception was the direct cause of the following exception:
+
   INFO: activate_cctools_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
   AS=x86_64-apple-darwin13.4.0-as
   CHECKSYMS=x86_64-apple-darwin13.4.0-checksyms
   INSTALL_NAME_TOOL=x86_64-apple-darwin13.4.0-install_name_tool
+  Traceback (most recent call last):
+    File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 10, in <module>
+      sys.exit(execute())
+               ~~~~~~~^^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/cli/main_build.py", line 639, in execute
+      api.build(
+      ~~~~~~~~~^
+          parsed.recipe,
+          ^^^^^^^^^^^^^^
+      ...<8 lines>...
+          cache_dir=parsed.cache_dir,
+          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+      )
+      ^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/api.py", line 211, in build
+      return build_tree(
+          recipes,
+      ...<7 lines>...
+          variants=variants,
+      )
   LD=x86_64-apple-darwin13.4.0-ld
   LIBTOOL=x86_64-apple-darwin13.4.0-libtool
   LIPO=x86_64-apple-darwin13.4.0-lipo
   NM=x86_64-apple-darwin13.4.0-nm
   NMEDIT=x86_64-apple-darwin13.4.0-nmedit
   OTOOL=x86_64-apple-darwin13.4.0-otool
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 3675, in build_tree
+      packages_from_this = build(
+          metadata,
+      ...<5 lines>...
   PAGESTUFF=x86_64-apple-darwin13.4.0-pagestuff
+          notest=notest,
+      )
   RANLIB=x86_64-apple-darwin13.4.0-ranlib
   REDO_PREBINDING=x86_64-apple-darwin13.4.0-redo_prebinding
   SEG_ADDR_TABLE=x86_64-apple-darwin13.4.0-seg_addr_table
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 2584, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
   SEG_HACK=x86_64-apple-darwin13.4.0-seg_hack
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/primer3_1776761438338/work/conda_build.sh']' returned non-zero exit status 2.
   SEGEDIT=x86_64-apple-darwin13.4.0-segedit
   SIZE=x86_64-apple-darwin13.4.0-size
   STRINGS=x86_64-apple-darwin13.4.0-strings
