[ci skip] add build failure record for recipe recipes/alignlib-lite

diff --git a/recipes/alignlib-lite/build_failure.osx-64.yaml b/recipes/alignlib-lite/build_failure.osx-64.yaml
--- a/recipes/alignlib-lite/build_failure.osx-64.yaml
+++ b/recipes/alignlib-lite/build_failure.osx-64.yaml
@@ -15,29 +15,36 @@ log: |2-
         static PyObject *__pyx_f_13alignlib_lite__forceBytes(PyObject *__pyx_v_s) {
                          ^
         4 warnings generated.
-        x86_64-apple-darwin13.4.0-clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/work=/usr/local/src/conda/alignlib-lite-0.3 -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -mmacosx-version-min=10.9 -Ialignlib_src -I/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.11 -c alignlib_src/*.cpp -o build/temp.macosx-10.9-x86_64-cpython-311/alignlib_src/*.o
+        x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/work=/usr/local/src/conda/alignlib-lite-0.3 -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -mmacosx-version-min=10.9 -Ialignlib_src -I/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.9 -c alignlib_src/*.cpp -o build/temp.macosx-10.9-x86_64-cpython-39/alignlib_src/*.o
         clang-16: error: no such file or directory: 'alignlib_src/*.cpp'
         clang-16: error: no input files
-        error: command '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_build_env/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
+        error: command '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_build_env/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
         [end of output]
 
     note: This error originates from a subprocess, and is likely not a problem with pip.
     ERROR: Failed building wheel for alignlib-lite
   ERROR: Could not build wheels for alignlib-lite, which is required to install pyproject.toml-based projects
+  Extracting download
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/work
   Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
-  Extracting download
       sys.exit(execute())
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/work
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
       api.build(
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
       return build_tree(
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
       packages_from_this = build(
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/work
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
+      utils.check_call_env(
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/work/conda_build.sh']' returned non-zero exit status 1.
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717534863291/work
   INFO: activate_clang_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
   AS=x86_64-apple-darwin13.4.0-as
@@ -49,14 +56,7 @@ log: |2-
   CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-strip -DCMAKE_INSTALL_NAME_TOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-install_name_tool -DCMAKE_LIBTOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_FIND_APPBUNDLE=LAST -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
   CMAKE_PREFIX_PATH=:$PREFIX
   CONDA_TOOLCHAIN_BUILD=x86_64-apple-darwin13.4.0
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
-      utils.check_call_env(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
-      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
-      raise subprocess.CalledProcessError(proc.returncode, _args)
   CONDA_TOOLCHAIN_HOST=x86_64-apple-darwin13.4.0
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717513698635/work/conda_build.sh']' returned non-zero exit status 1.
   CPPFLAGS=-D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9
   DEBUG_CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/alignlib-lite-0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
   HOST=x86_64-apple-darwin13.4.0
