[ci skip] add build failure record for recipe recipes/alignlib-lite

diff --git a/recipes/alignlib-lite/build_failure.osx-64.yaml b/recipes/alignlib-lite/build_failure.osx-64.yaml
--- a/recipes/alignlib-lite/build_failure.osx-64.yaml
+++ b/recipes/alignlib-lite/build_failure.osx-64.yaml
@@ -1,58 +1,58 @@
 recipe_sha: 2ddf24065fcdbf61d820063dc1db8ed110b38b66740e2bedb79abf6f9f9008df  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-                             ^
-        In file included from alignlib_lite.cpp:1413:
-        In file included from alignlib_src/alignlib.h:38:
-        In file included from alignlib_src/alignlib_functions.h:54:
-        alignlib_src/MultipleAlignmentFormat.h:159:15: warning: 'alignlib::MultipleAlignmentFormatHTML::fill' hides overloaded virtual function [-Woverloaded-virtual]
-                virtual void fill( const HMultipleAlignment & src, const HPalette & palette);
-                             ^
-        alignlib_src/MultipleAlignmentFormat.h:75:15: note: hidden overloaded virtual function 'alignlib::MultipleAlignmentFormat::fill' declared here: different number of parameters (1 vs 2)
-                virtual void fill( const HMultipleAlignment & src);
-                             ^
+                                                                                /* DISABLES CODE */ ( )
+        alignlib_lite.cpp:16616:5: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
+            0,
+            ^
+        /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
+            Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
+            ^
+        /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
+        #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
+                                                             ^
         alignlib_lite.cpp:4490:18: warning: unused function '__pyx_f_13alignlib_lite__forceBytes' [-Wunused-function]
         static PyObject *__pyx_f_13alignlib_lite__forceBytes(PyObject *__pyx_v_s) {
                          ^
-        4 warnings generated.
-        x86_64-apple-darwin13.4.0-clang -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/work=/usr/local/src/conda/alignlib-lite-0.3 -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -mmacosx-version-min=10.9 -Ialignlib_src -I/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.12 -c alignlib_src/*.cpp -o build/temp.macosx-10.9-x86_64-cpython-312/alignlib_src/*.o
+        11 warnings generated.
+        x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fPIC -O2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/work=/usr/local/src/conda/alignlib-lite-0.3 -fdebug-prefix-map=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include -mmacosx-version-min=10.9 -Ialignlib_src -I/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/include/python3.8 -c alignlib_src/*.cpp -o build/temp.macosx-10.9-x86_64-cpython-38/alignlib_src/*.o
         clang-16: error: no such file or directory: 'alignlib_src/*.cpp'
         clang-16: error: no input files
-        error: command '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_build_env/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
+        error: command '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_build_env/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
         [end of output]
 
     note: This error originates from a subprocess, and is likely not a problem with pip.
     ERROR: Failed building wheel for alignlib-lite
   ERROR: Could not build wheels for alignlib-lite, which is required to install pyproject.toml-based projects
   Extracting download
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/work
   Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
       api.build(
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/work
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/work
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
+      return build_tree(
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/work
   INFO: activate_clang_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
   AS=x86_64-apple-darwin13.4.0-as
   CC=x86_64-apple-darwin13.4.0-clang
   CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
-  CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/alignlib-lite-0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  CHECKSYMS=x86_64-apple-darwin13.4.0-checksyms
-  CLANG=x86_64-apple-darwin13.4.0-clang
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
-      return build_tree(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
       packages_from_this = build(
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
       utils.check_call_env(
+  CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/alignlib-lite-0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CHECKSYMS=x86_64-apple-darwin13.4.0-checksyms
+  CLANG=x86_64-apple-darwin13.4.0-clang
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717780151808/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/alignlib-lite_1717795808954/work/conda_build.sh']' returned non-zero exit status 1.
   CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-strip -DCMAKE_INSTALL_NAME_TOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-install_name_tool -DCMAKE_LIBTOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_FIND_APPBUNDLE=LAST -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
   CMAKE_PREFIX_PATH=:$PREFIX
   CONDA_TOOLCHAIN_BUILD=x86_64-apple-darwin13.4.0
