[ci skip] add build failure record for recipe recipes/interproscan

diff --git a/recipes/interproscan/build_failure.linux-64.yaml b/recipes/interproscan/build_failure.linux-64.yaml
--- a/recipes/interproscan/build_failure.linux-64.yaml
+++ b/recipes/interproscan/build_failure.linux-64.yaml
@@ -1,4 +1,4 @@
-recipe_sha: 3deb00b429ee7feec0b19595eb875ae7f90b929e69dc71fbf1a5574d504402a4  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: e33bd8a6c26500a71f00c00b7ae173878074b84bac6936f6bfa66de67d2ff72d  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
     summary: InterPro integrates together predictive information about proteins function
@@ -13,10 +13,10 @@ log: |2-
     copy_test_source_files: true
 
 
-  source tree in: /opt/conda/conda-bld/interproscan_1772561026811/work
-  export PREFIX=/opt/conda/conda-bld/interproscan_1772561026811/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export BUILD_PREFIX=/opt/conda/conda-bld/interproscan_1772561026811/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/interproscan_1772561026811/work
+  source tree in: /opt/conda/conda-bld/interproscan_1772612497798/work
+  export PREFIX=/opt/conda/conda-bld/interproscan_1772612497798/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export BUILD_PREFIX=/opt/conda/conda-bld/interproscan_1772612497798/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/interproscan_1772612497798/work
   INFO: activate-binutils_linux-64.sh made the following environmental changes:
   ADDR2LINE=x86_64-conda-linux-gnu-addr2line
   AR=x86_64-conda-linux-gnu-ar
@@ -82,7 +82,7 @@ log: |2-
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/interproscan_1772561026811/work/conda_build.sh']' returned non-zero exit status 2.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/interproscan_1772612497798/work/conda_build.sh']' returned non-zero exit status 2.
 
   The above exception was the direct cause of the following exception:
 
@@ -100,5 +100,5 @@ log: |2-
                            ^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/interproscan_1772561026811/work/conda_build.sh']' returned non-zero exit status 2.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/interproscan_1772612497798/work/conda_build.sh']' returned non-zero exit status 2.
 # Last 100 lines of the build log.
