[ci skip] add build failure record for recipe recipes/bam-tide

diff --git a/recipes/bam-tide/build_failure.linux-64.yaml b/recipes/bam-tide/build_failure.linux-64.yaml
--- a/recipes/bam-tide/build_failure.linux-64.yaml
+++ b/recipes/bam-tide/build_failure.linux-64.yaml
@@ -1,16 +1,16 @@
-recipe_sha: 9c3866db456f355924f21a18077dc9552699d0560c8c7fab326170c6a20d788b  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: b60b9339269f3bf9c654ea185f856a00f2adb891351e462cba0d38f1880b4616  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
       - c-ares 1.34.6 hb03c661_0
       - keyutils 1.6.3 hb9d3cd8_0
       - libdeflate 1.22 hb9d3cd8_0
       - libgcc-ng 15.2.0 h69a702a_18
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772614774902/work/conda_build.sh']' returned non-zero exit status 101.
       - liblzma 5.8.2 hb03c661_0
       - libstdcxx 15.2.0 h934c35e_18
       - libzlib 1.3.1 hb9d3cd8_2
       - ncurses 6.5 h2d0b736_3
       - openssl 3.6.1 h35e630c_1
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/work/conda_build.sh']' returned non-zero exit status 101.
       - libedit 3.1.20250104 pl5321h7949ede_0
       - libev 4.33 hd590300_2
       - libssh2 1.11.1 hcf80075_0
@@ -21,10 +21,10 @@ log: |2-
       - libcurl 8.18.0 hcf29cc6_1
       - htslib 1.23 h566b1c6_0
     run:
-      - libgcc >=13
-      - libzlib >=1.3.1,<2.0a0
       - htslib >=1.23,<1.24.0a0
+      - libzlib >=1.3.1,<2.0a0
       - zlib
+      - libgcc >=13
     run_constrained:
       - __glibc >=2.17
   test:
@@ -53,10 +53,10 @@ log: |2-
       - stela2502
 
 
-  source tree in: /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772614774902/work
-  export PREFIX=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772614774902/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
-  export BUILD_PREFIX=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772614774902/_build_env
-  export SRC_DIR=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772614774902/work
+  source tree in: /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/work
+  export PREFIX=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
+  export BUILD_PREFIX=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/_build_env
+  export SRC_DIR=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/work
   INFO: activate-binutils_linux-64.sh made the following environmental changes:
   ADDR2LINE=x86_64-conda-linux-gnu-addr2line
   AR=x86_64-conda-linux-gnu-ar
