[ci skip] add build failure record for recipe recipes/bam-tide

diff --git a/recipes/bam-tide/build_failure.linux-64.yaml b/recipes/bam-tide/build_failure.linux-64.yaml
--- a/recipes/bam-tide/build_failure.linux-64.yaml
+++ b/recipes/bam-tide/build_failure.linux-64.yaml
@@ -1,104 +1,104 @@
-recipe_sha: b60b9339269f3bf9c654ea185f856a00f2adb891351e462cba0d38f1880b4616  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 157c05013b9e1eb7bfbd57dfcdeb7acf995877594afe90e336fea8d2d3d8bf59  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      - c-ares 1.34.6 hb03c661_0
-      - keyutils 1.6.3 hb9d3cd8_0
-      - libdeflate 1.22 hb9d3cd8_0
-      - libgcc-ng 15.2.0 h69a702a_18
-      - liblzma 5.8.2 hb03c661_0
-      - libstdcxx 15.2.0 h934c35e_18
-      - libzlib 1.3.1 hb9d3cd8_2
-      - ncurses 6.5 h2d0b736_3
-      - openssl 3.6.1 h35e630c_1
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/work/conda_build.sh']' returned non-zero exit status 101.
-      - libedit 3.1.20250104 pl5321h7949ede_0
-      - libev 4.33 hd590300_2
-      - libssh2 1.11.1 hcf80075_0
-      - zlib 1.3.1 hb9d3cd8_2
-      - zstd 1.5.7 hb78ec9c_6
-      - krb5 1.22.2 ha1258a1_0
-      - libnghttp2 1.67.0 had1ee68_0
-      - libcurl 8.18.0 hcf29cc6_1
-      - htslib 1.23 h566b1c6_0
-    run:
-      - htslib >=1.23,<1.24.0a0
-      - libzlib >=1.3.1,<2.0a0
-      - zlib
-      - libgcc >=13
-    run_constrained:
-      - __glibc >=2.17
-  test:
-    commands:
-      - bam-coverage --help
-      - bam-subset-tag --help
-  about:
-    description: 'bam_tide provides a high-performance implementation of BAM coverage
+       |
+  1125 |             (*rec).l_text = l_text;
+       |                    ^^^^^^ unknown field
+       |
+       = note: available field is: _address
 
-      calculation and BigWig generation, serving as a fast alternative to
+  error[E0609]: no field text on type sam_hdr_t
+      --> /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/bam/mod.rs:1393:20
+       |
+  1393 |             (*rec).text = text as *mut c_char;
+       |                    ^^^^ unknown field
+       |
+       = note: available field is: _address
 
-      deepTools bamCoverage.
+  error[E0609]: no field l_text on type sam_hdr_t
+      --> /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/bam/mod.rs:1394:20
+       |
+  1394 |             (*rec).l_text = l_text;
+       |                    ^^^^^^ unknown field
+       |
+       = note: available field is: _address
 
-      '
-    dev_url: https://github.com/stela2502/bam_tide
-    home: https://github.com/stela2502/bam_tide
-    license: MIT
-    license_file:
-      - LICENSE
-      - THIRDPARTY.yml
-    summary: Fast BAM to BigWig coverage tool written in Rust
-  extra:
-    copy_test_source_files: true
-    final: true
-    recipe-maintainers:
-      - stela2502
+  error[E0609]: no field n_targets on type &sam_hdr_t
+      --> /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/bam/mod.rs:1443:22
+       |
+  1443 |         self.inner().n_targets as u32
+       |                      ^^^^^^^^^ unknown field
+       |
+       = note: available field is: _address
 
+  error[E0609]: no field target_name on type &sam_hdr_t
+      --> /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/bam/mod.rs:1448:48
+       |
+  1448 |             slice::from_raw_parts(self.inner().target_name, self.target_count() as usize)
+       |                                                ^^^^^^^^^^^ unknown field
+       |
+       = note: available field is: _address
 
-  source tree in: /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/work
-  export PREFIX=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
-  export BUILD_PREFIX=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/_build_env
-  export SRC_DIR=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772615196774/work
-  INFO: activate-binutils_linux-64.sh made the following environmental changes:
-  ADDR2LINE=x86_64-conda-linux-gnu-addr2line
-  AR=x86_64-conda-linux-gnu-ar
-  AS=x86_64-conda-linux-gnu-as
-  CXXFILT=x86_64-conda-linux-gnu-cfilt
-  ELFEDIT=x86_64-conda-linux-gnu-elfedit
-  GPROF=x86_64-conda-linux-gnu-gprof
-  LD=x86_64-conda-linux-gnu-ld
-  NM=x86_64-conda-linux-gnu-nm
-  OBJCOPY=x86_64-conda-linux-gnu-objcopy
-  OBJDUMP=x86_64-conda-linux-gnu-objdump
-  RANLIB=x86_64-conda-linux-gnu-ranlib
-  READELF=x86_64-conda-linux-gnu-readelf
-  SIZE=x86_64-conda-linux-gnu-size
-  STRINGS=x86_64-conda-linux-gnu-strings
-  STRIP=x86_64-conda-linux-gnu-strip
-  INFO: activate-gcc_linux-64.sh made the following environmental changes:
-  build_alias=x86_64-conda-linux-gnu
-  -BUILD=x86_64-conda_cos6-linux-gnu
-  BUILD=x86_64-conda-linux-gnu
-  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
-  CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
-  CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bam-tide-1.2.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
-  CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr
-  CONDA_BUILD_CROSS_COMPILATION=
-  -CONDA_BUILD_SYSROOT=
-  CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot
-  CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
-  CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
-  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
-  CPP_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
-  CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
-  DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bam-tide-1.2.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
-  GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
-  GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
-  GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
-  GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
-  host_alias=x86_64-conda-linux-gnu
-  HOST=x86_64-conda-linux-gnu
-  LDFLAGS_LD=-O2 --sort-common --as-needed -z relro -z now --disable-new-dtags --gc-sections --allow-shlib-undefined -rpath $PREFIX/lib -rpath-link $PREFIX/lib -L$PREFIX/lib
+  error[E0609]: no field n_targets on type sam_hdr_t
+      --> /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/bam/mod.rs:1458:33
+       |
+  1458 |         if (tid as i32) < inner.n_targets {
+       |                                 ^^^^^^^^^ unknown field
+       |
+       = note: available field is: _address
+
+  error[E0609]: no field target_len on type sam_hdr_t
+      --> /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/bam/mod.rs:1460:54
+       |
+  1460 |                 unsafe { slice::from_raw_parts(inner.target_len, inner.n_targets as usize) };
+       |                                                      ^^^^^^^^^^ unknown field
+       |
+       = note: available field is: _address
+
+  error[E0609]: no field n_targets on type sam_hdr_t
+      --> /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/bam/mod.rs:1460:72
+       |
+  1460 |                 unsafe { slice::from_raw_parts(inner.target_len, inner.n_targets as usize) };
+       |                                                                        ^^^^^^^^^ unknown field
+       |
+       = note: available field is: _address
+
+  For more information about this error, try rustc --explain E0609.
+  error: could not compile rust-htslib (lib) due to 11 previous errors
+
+  Caused by:
+    process didn't exit successfully: rustc --crate-name rust_htslib --edition=2018 /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rust-htslib-1.0.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="bzip2"' --cfg 'feature="curl"' --cfg 'feature="default"' --cfg 'feature="lzma"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("bindgen", "bzip2", "curl", "default", "gcs", "libdeflate", "lzma", "s3", "serde", "serde_bytes", "serde_feature", "static"))' -C metadata=3128b251e84c94bc -C extra-filename=-2c34f56e0be471ba --out-dir /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -C linker=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_build_env/bin/x86_64-conda-linux-gnu-cc -C strip=debuginfo -L dependency=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/release/deps --extern bio_types=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libbio_types-7418f9cb6632922f.rmeta --extern byteorder=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libbyteorder-8ea01ce9a9180e36.rmeta --extern custom_derive=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libcustom_derive-90c0d1ba5bd5ecb3.rmeta --extern derive_new=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/release/deps/libderive_new-fcd81bc236f3c8a3.so --extern hts_sys=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libhts_sys-556e76c3f11b003b.rmeta --extern ieee754=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libieee754-7e0547fd7be2bfd3.rmeta --extern lazy_static=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/liblazy_static-4761e16075f76a80.rmeta --extern libc=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/liblibc-31ff5c869fe4265f.rmeta --extern libz_sys=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/liblibz_sys-8d4c1c2ad8f420b2.rmeta --extern linear_map=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/liblinear_map-e0dcf24ea48b7034.rmeta --extern newtype_derive=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libnewtype_derive-361a48a1357509f4.rmeta --extern regex=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libregex-60056d9544372854.rmeta --extern thiserror=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/libthiserror-e2c720c570d16006.rmeta --extern url=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/deps/liburl-2a1f5f067ebb0d6c.rmeta --cap-lints allow -C link-arg=-Wl,-rpath-link,/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -C link-arg=-Wl,-rpath,/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -L native=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/build/hts-sys-e841052d52a43318/out -L native=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/build/bzip2-sys-86fbbc940f01d51d/out/lib -L native=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/build/curl-sys-ab9a4a3252f9924a/out/build -L native=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/build/libz-sys-3c0b0851f0f533ea/out/lib -L native=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/build/libz-sys-3c0b0851f0f533ea/out/lib -L native=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/build/openssl-sys-132450bcda792b71/out/openssl-build/install/lib -L native=/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target/x86_64-unknown-linux-gnu/release/build/lzma-sys-ddf2022fc7f971a7/out (exit status: 1)
+  error: failed to compile bam_tide v1.2.0 (/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work), intermediate artifacts can be found at /home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/target.
+  To reuse those artifacts with a future compilation, set the environment variable CARGO_TARGET_DIR to that path.
+  Traceback (most recent call last):
+    File "/home/med-sal/micromamba/envs/bc/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
+      utils.check_call_env(
   LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
   MESON_ARGS=-Dbuildtype=release --prefix=$PREFIX -Dlibdir=lib
+    File "/home/med-sal/micromamba/envs/bc/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
+  INFO: activate-gxx_linux-64.sh made the following environmental changes:
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/home/med-sal/micromamba/envs/bc/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bam-tide-1.2.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
+  CXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/conda_build.sh']' returned non-zero exit status 101.
+
+  The above exception was the direct cause of the following exception:
+
+  Traceback (most recent call last):
+    File "/home/med-sal/micromamba/envs/bc/bin/conda-build", line 11, in <module>
+      sys.exit(execute())
+  DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bam-tide-1.2.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
+    File "/home/med-sal/micromamba/envs/bc/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
+      api.build(
+    File "/home/med-sal/micromamba/envs/bc/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
+      return build_tree(
+    File "/home/med-sal/micromamba/envs/bc/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
+      packages_from_this = build(
+    File "/home/med-sal/micromamba/envs/bc/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/home/med-sal/micromamba/envs/bc/conda-bld/bam-tide_1772617861468/work/conda_build.sh']' returned non-zero exit status 101.
 # Last 100 lines of the build log.
