[ci skip] add build failure record for recipe recipes/macs2

diff --git a/recipes/macs2/build_failure.osx-64.yaml b/recipes/macs2/build_failure.osx-64.yaml
--- a/recipes/macs2/build_failure.osx-64.yaml
+++ b/recipes/macs2/build_failure.osx-64.yaml
@@ -1,63 +1,12 @@
-recipe_sha: 256b582e16da5a4cbd23fdc9a6b471b86ad88c855a44c8d891b078d777256a6a  # The commit at which this recipe failed to build.
+recipe_sha: b01eab910a2503718f036814367f5dc4eb80e6d6f1d93320058cf5332693b941  # The commit at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      ca-certificates: 2023.5.7-h8857fd0_0       conda-forge
-      cython:          0.29.35-py39h840bb9f_0    conda-forge
-      libblas:         3.9.0-16_osx64_openblas   conda-forge
-      libcblas:        3.9.0-16_osx64_openblas   conda-forge
-      libcxx:          16.0.4-hd57cbcb_0         conda-forge
-      libffi:          3.4.2-h0d85af4_5          conda-forge
-      libgfortran:     5.0.0-11_3_0_h97931a8_31  conda-forge
-      libgfortran5:    12.2.0-he409387_31        conda-forge
-      liblapack:       3.9.0-16_osx64_openblas   conda-forge
-      libopenblas:     0.3.21-openmp_h429af6e_3  conda-forge
-      libsqlite:       3.42.0-h58db7d2_0         conda-forge
-      libzlib:         1.2.13-hfd90126_4         conda-forge
-      llvm-openmp:     16.0.4-hff08bdf_0         conda-forge
-      ncurses:         6.3-h96cf925_1            conda-forge
-      numpy:           1.24.3-py39h892e69a_0     conda-forge
-      openssl:         3.1.1-h8a1eda9_0          conda-forge
-      pip:             23.1.2-pyhd8ed1ab_0       conda-forge
-      python:          3.9.16-h709bd14_0_cpython conda-forge
-      python_abi:      3.9-3_cp39                conda-forge
-      readline:        8.2-h9e318b2_1            conda-forge
-      setuptools:      67.7.2-pyhd8ed1ab_0       conda-forge
-      tk:              8.6.12-h5dbffcc_0         conda-forge
-      tzdata:          2023c-h71feb2d_0          conda-forge
-      wheel:           0.40.0-pyhd8ed1ab_0       conda-forge
-      xz:              5.2.6-h775f41a_0          conda-forge
-
-  Preparing transaction: ...working... done
-  Verifying transaction: ...working... done
-  Executing transaction: ...working... done
-  Reloading output folder: /opt/mambaforge/envs/bioconda/conda-bld
-  Reloading output folder: /opt/mambaforge/envs/bioconda/conda-bld
-
-  ## Package Plan ##
-
-    environment location: /opt/mambaforge/envs/bioconda/conda-bld/macs2_1685481773580/_build_env
-
-
-  The following NEW packages will be INSTALLED:
-
-      ca-certificates:    2023.5.7-h8857fd0_0       conda-forge
-      cctools_osx-64:     973.0.1-h48a5a9d_13       conda-forge
-      clang:              15.0.7-h694c41f_2         conda-forge
-      clang-15:           15.0.7-default_hdb78580_2 conda-forge
-      clang_osx-64:       15.0.7-h03d6864_3         conda-forge
-      clangxx:            15.0.7-default_hdb78580_2 conda-forge
-      compiler-rt:        15.0.7-he1888fc_1         conda-forge
-      compiler-rt_osx-64: 15.0.7-he1888fc_1         conda-forge
-      icu:                72.1-h7336db1_0           conda-forge
-      ld64_osx-64:        609-h8ce0179_13           conda-forge
-      libclang-cpp15:     15.0.7-default_hdb78580_2 conda-forge
-      libcxx:             16.0.4-hd57cbcb_0         conda-forge
       libiconv:           1.17-hac89ed1_0           conda-forge
       libllvm15:          15.0.7-he4b1e75_2         conda-forge
       libxml2:            2.11.4-hd95e348_0         conda-forge
       libzlib:            1.2.13-hfd90126_4         conda-forge
       llvm-tools:         15.0.7-he4b1e75_2         conda-forge
-      openssl:            3.1.1-h8a1eda9_0          conda-forge
+      openssl:            3.1.1-h8a1eda9_1          conda-forge
       sigtool:            0.1.3-h88f4db0_0          conda-forge
       tapi:               1100.0.11-h9ce4665_0      conda-forge
       xz:                 5.2.6-h775f41a_0          conda-forge
@@ -67,24 +16,73 @@ log: |2-
   Verifying transaction: ...working... done
   Executing transaction: ...working... done
   Source cache directory is: /opt/mambaforge/envs/bioconda/conda-bld/src_cache
-  Downloading source to cache: MACS2-2.2.8_2a0a436ac8.tar.gz
-  Downloading https://pypi.io/packages/source/M/MACS2/MACS2-2.2.8.tar.gz
   INFO:conda_build.source:Source cache directory is: /opt/mambaforge/envs/bioconda/conda-bld/src_cache
   INFO:conda_build.source:Downloading source to cache: MACS2-2.2.8_2a0a436ac8.tar.gz
+  Downloading source to cache: MACS2-2.2.8_2a0a436ac8.tar.gz
+  Downloading https://pypi.io/packages/source/M/MACS2/MACS2-2.2.8.tar.gz
   INFO:conda_build.source:Downloading https://pypi.io/packages/source/M/MACS2/MACS2-2.2.8.tar.gz
   Success
   INFO:conda_build.source:Success
   Extracting download
-  Applying patch: /Users/runner/work/bioconda-recipes/bioconda-recipes/recipes/macs2/patch
-  Applying patch: /Users/runner/work/bioconda-recipes/bioconda-recipes/recipes/macs2/patch with args:
-  ['-Np0', '-i', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpcw1s9t1x/patch.native', '--binary']
-  checking file setup.py
-  Hunk #1 FAILED at 20.
-  Hunk #2 succeeded at 94 with fuzz 1 (offset 1 line).
-  1 out of 2 hunks FAILED
-  Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
-  Error was:
-  Command '['/opt/mambaforge/envs/bioconda/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np0', '-i', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpcw1s9t1x/patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/macs2_1685520008246/work
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/macs2_1685520008246/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/macs2_1685520008246/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/macs2_1685520008246/work
+  INFO: activate_clang_osx-64.sh made the following environmental changes:
+  AR=x86_64-apple-darwin13.4.0-ar
+  AS=x86_64-apple-darwin13.4.0-as
+  CC=x86_64-apple-darwin13.4.0-clang
+  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
+  CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/macs2-2.2.8 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CHECKSYMS=x86_64-apple-darwin13.4.0-checksyms
+  CLANG=x86_64-apple-darwin13.4.0-clang
+  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-strip -DCMAKE_INSTALL_NAME_TOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-install_name_tool -DCMAKE_LIBTOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_FIND_APPBUNDLE=LAST -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
+  CMAKE_PREFIX_PATH=:$PREFIX
+  CONDA_TOOLCHAIN_BUILD=x86_64-apple-darwin13.4.0
+  CONDA_TOOLCHAIN_HOST=x86_64-apple-darwin13.4.0
+  CPPFLAGS=-D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9
+  DEBUG_CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/macs2-2.2.8 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  HOST=x86_64-apple-darwin13.4.0
+  INSTALL_NAME_TOOL=x86_64-apple-darwin13.4.0-install_name_tool
+  LD=x86_64-apple-darwin13.4.0-ld
+  LDFLAGS=-Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib
+  LDFLAGS_LD=-pie -headerpad_max_install_names -dead_strip_dylibs -rpath $PREFIX/lib -L$PREFIX/lib
+  LIBTOOL=x86_64-apple-darwin13.4.0-libtool
+  LIPO=x86_64-apple-darwin13.4.0-lipo
+  MESON_ARGS=--buildtype release --prefix=$PREFIX -Dlibdir=lib
+  NM=x86_64-apple-darwin13.4.0-nm
+  NMEDIT=x86_64-apple-darwin13.4.0-nmedit
+  OBJC=x86_64-apple-darwin13.4.0-clang
+  OBJC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
+  OTOOL=x86_64-apple-darwin13.4.0-otool
+  PAGESTUFF=x86_64-apple-darwin13.4.0-pagestuff
+  RANLIB=x86_64-apple-darwin13.4.0-ranlib
+  REDO_PREBINDING=x86_64-apple-darwin13.4.0-redo_prebinding
+  SDKROOT=/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
+  SEGEDIT=x86_64-apple-darwin13.4.0-segedit
+  SEG_ADDR_TABLE=x86_64-apple-darwin13.4.0-seg_addr_table
+  SEG_HACK=x86_64-apple-darwin13.4.0-seg_hack
+  SIZE=x86_64-apple-darwin13.4.0-size
+  STRINGS=x86_64-apple-darwin13.4.0-strings
+  STRIP=x86_64-apple-darwin13.4.0-strip
+  _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_apple_darwin13_4_0
+  ac_cv_func_malloc_0_nonnull=yes
+  ac_cv_func_realloc_0_nonnull=yes
+  build_alias=x86_64-apple-darwin13.4.0
+  host_alias=x86_64-apple-darwin13.4.0
+  rm: MACS2/Prob.c: No such file or directory
+  rm: MACS2/IO/Parser.c: No such file or directory
+  rm: MACS2/Pileup.c: No such file or directory
+  rm: MACS2/PeakModel.c: No such file or directory
+  rm: MACS2/PeakDetect.c: No such file or directory
+  rm: MACS2/Signal.c: No such file or directory
+  rm: MACS2/IO/PeakIO.c: No such file or directory
+  rm: MACS2/IO/BedGraphIO.c: No such file or directory
+  rm: MACS2/IO/FixWidthTrack.c: No such file or directory
+  rm: MACS2/IO/PairedEndTrack.c: No such file or directory
+  rm: MACS2/IO/BedGraph.c: No such file or directory
+  rm: MACS2/IO/ScoreTrack.c: No such file or directory
+  rm: MACS2/IO/CallPeakUnit.c: No such file or directory
   Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-mambabuild", line 10, in <module>
       sys.exit(main())
@@ -96,9 +94,11 @@ log: |2-
       return build_tree(
     File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
       packages_from_this = build(metadata, stats,
-    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 2125, in build
-      try_download(m, no_download_source=False, raise_error=True)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/render.py", line 663, in try_download
-      raise RuntimeError("Failed to download or patch source. Please see build log for info.")
-  RuntimeError: Failed to download or patch source. Please see build log for info.
+    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 2198, in build
+      utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
+    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/utils.py", line 451, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/macs2_1685520008246/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
