[ci skip] add build failure record for recipe recipes/macs2

diff --git a/recipes/macs2/build_failure.linux-64.yaml b/recipes/macs2/build_failure.linux-64.yaml
--- a/recipes/macs2/build_failure.linux-64.yaml
+++ b/recipes/macs2/build_failure.linux-64.yaml
@@ -1,58 +1,6 @@
-recipe_sha: 256b582e16da5a4cbd23fdc9a6b471b86ad88c855a44c8d891b078d777256a6a  # The commit at which this recipe failed to build.
+recipe_sha: b01eab910a2503718f036814367f5dc4eb80e6d6f1d93320058cf5332693b941  # The commit at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      ld_impl_linux-64: 2.40-h41732ed_0            conda-forge
-      libblas:          3.9.0-16_linux64_openblas  conda-forge
-      libcblas:         3.9.0-16_linux64_openblas  conda-forge
-      libffi:           3.4.2-h7f98852_5           conda-forge
-      libgcc-ng:        12.2.0-h65d4601_19         conda-forge
-      libgfortran-ng:   12.2.0-h69a702a_19         conda-forge
-      libgfortran5:     12.2.0-h337968e_19         conda-forge
-      libgomp:          12.2.0-h65d4601_19         conda-forge
-      liblapack:        3.9.0-16_linux64_openblas  conda-forge
-      libnsl:           2.0.0-h7f98852_0           conda-forge
-      libopenblas:      0.3.21-pthreads_h78a6416_3 conda-forge
-      libsqlite:        3.42.0-h2797004_0          conda-forge
-      libstdcxx-ng:     12.2.0-h46fd767_19         conda-forge
-      libuuid:          2.38.1-h0b41bf4_0          conda-forge
-      libzlib:          1.2.13-h166bdaf_4          conda-forge
-      ncurses:          6.3-h27087fc_1             conda-forge
-      numpy:            1.24.3-py39h6183b62_0      conda-forge
-      openssl:          3.1.1-hd590300_0           conda-forge
-      pip:              23.1.2-pyhd8ed1ab_0        conda-forge
-      python:           3.9.16-h2782a2a_0_cpython  conda-forge
-      python_abi:       3.9-3_cp39                 conda-forge
-      readline:         8.2-h8228510_1             conda-forge
-      setuptools:       67.7.2-pyhd8ed1ab_0        conda-forge
-      tk:               8.6.12-h27826a3_0          conda-forge
-      tzdata:           2023c-h71feb2d_0           conda-forge
-      wheel:            0.40.0-pyhd8ed1ab_0        conda-forge
-      xz:               5.2.6-h166bdaf_0           conda-forge
-
-  Preparing transaction: ...working... done
-  Verifying transaction: ...working... done
-  Executing transaction: ...working... done
-  [34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
-  [?25l[2K[0G[] 0.0s
-  opt/conda/conda-bl..    [2K[1A[2K[0Gopt/conda/conda-bld/linux-64
-  opt/conda/conda-bld/noarch                         127.0 B @   3.8MB/s  0.0s
-  [?25h[34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
-  [?25l[2K[0G[] 0.0s
-  [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                       129.0 B @   2.5MB/s  0.0s
-  opt/conda/conda-bld/noarch                         127.0 B @   2.6MB/s  0.0s
-  [?25h
-  ## Package Plan ##
-
-    environment location: /opt/conda/conda-bld/macs2_1685480442457/_build_env
-
-
-  The following NEW packages will be INSTALLED:
-
-      _libgcc_mutex:           0.1-conda_forge    conda-forge
-      _openmp_mutex:           4.5-2_gnu          conda-forge
-      binutils_impl_linux-64:  2.39-he00db2b_1    conda-forge
-      binutils_linux-64:       2.39-h5fc0e48_13   conda-forge
-      gcc_impl_linux-64:       12.2.0-hcc96c02_19 conda-forge
       gcc_linux-64:            12.2.0-h4798a0e_13 conda-forge
       kernel-headers_linux-64: 2.6.32-he073ed8_15 conda-forge
       ld_impl_linux-64:        2.39-hcc3a1bd_1    conda-forge
@@ -75,16 +23,66 @@ log: |2-
   Success
   INFO:conda_build.source:Success
   Extracting download
-  Applying patch: /opt/recipe/patch
-  Applying patch: /opt/recipe/patch with args:
-  ['-Np0', '-i', '/tmp/tmpcj9l9asp/patch.native', '--binary']
-  checking file setup.py
-  Hunk #1 FAILED at 20.
-  Hunk #2 succeeded at 94 with fuzz 1 (offset 1 line).
-  1 out of 2 hunks FAILED
-  Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
-  Error was:
-  Command '['/opt/conda/bin/patch', '--no-backup-if-mismatch', '--batch', '-Np0', '-i', '/tmp/tmpcj9l9asp/patch.native', '--binary', '--dry-run']' returned non-zero exit status 1.
+  source tree in: /opt/conda/conda-bld/macs2_1685522748192/work
+  export PREFIX=/opt/conda/conda-bld/macs2_1685522748192/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
+  export BUILD_PREFIX=/opt/conda/conda-bld/macs2_1685522748192/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/macs2_1685522748192/work
+  INFO: activate-binutils_linux-64.sh made the following environmental changes:
+  ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-addr2line
+  AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar
+  AS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-as
+  CXXFILT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cfilt
+  ELFEDIT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-elfedit
+  GPROF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gprof
+  LD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld
+  LD_GOLD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld.gold
+  NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-nm
+  OBJCOPY=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objcopy
+  OBJDUMP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objdump
+  RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib
+  READELF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-readelf
+  SIZE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-size
+  STRINGS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strings
+  STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip
+  INFO: activate-gcc_linux-64.sh made the following environmental changes:
+  BUILD=x86_64-conda-linux-gnu
+  CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
+  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
+  CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/macs2-2.2.8 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
+  CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr
+  CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot
+  CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
+  CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
+  CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
+  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
+  DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/macs2-2.2.8 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
+  GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
+  GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
+  GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
+  GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
+  HOST=x86_64-conda-linux-gnu
+  LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
+  MESON_ARGS=--buildtype release --prefix=$PREFIX -Dlibdir=lib
+  _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
+  build_alias=x86_64-conda-linux-gnu
+  host_alias=x86_64-conda-linux-gnu
+  -BUILD=x86_64-conda_cos6-linux-gnu
+  -CONDA_BUILD_SYSROOT=
+  rm: cannot remove 'MACS2/Prob.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/Parser.c': No such file or directory
+  rm: cannot remove 'MACS2/Pileup.c': No such file or directory
+  rm: cannot remove 'MACS2/PeakModel.c': No such file or directory
+  rm: cannot remove 'MACS2/PeakDetect.c': No such file or directory
+  rm: cannot remove 'MACS2/Signal.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/PeakIO.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/BedGraphIO.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/FixWidthTrack.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/PairedEndTrack.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/BedGraph.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/ScoreTrack.c': No such file or directory
+  rm: cannot remove 'MACS2/IO/CallPeakUnit.c': No such file or directory
   Traceback (most recent call last):
     File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
       sys.exit(main())
@@ -96,9 +94,11 @@ log: |2-
       return build_tree(
     File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
       packages_from_this = build(metadata, stats,
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2125, in build
-      try_download(m, no_download_source=False, raise_error=True)
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 663, in try_download
-      raise RuntimeError("Failed to download or patch source. Please see build log for info.")
-  RuntimeError: Failed to download or patch source. Please see build log for info.
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2198, in build
+      utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 451, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/macs2_1685522748192/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
