[ci skip] add build failure record for recipe recipes/r-qorts

diff --git a/recipes/r-qorts/build_failure.linux-64.yaml b/recipes/r-qorts/build_failure.linux-64.yaml
--- a/recipes/r-qorts/build_failure.linux-64.yaml
+++ b/recipes/r-qorts/build_failure.linux-64.yaml
@@ -1,22 +1,6 @@
-recipe_sha: 34af700bbffca8263036dd2f300f1ccedf3013d23362e5920df8c73e63c9a848  # The commit at which this recipe failed to build.
+recipe_sha: 0b8fc5200c69be36797b07bf919ef71abaa81050c0f1c492735ee9259e9e6036  # The commit at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      libgfortran5:              13.1.0-h15d22d2_0          conda-forge
-      libglib:                   2.76.4-hebfc3b9_0          conda-forge
-      libgomp:                   13.1.0-he5830b7_0          conda-forge
-      libiconv:                  1.17-h166bdaf_0            conda-forge
-      libjpeg-turbo:             2.1.5.1-h0b41bf4_0         conda-forge
-      liblapack:                 3.9.0-17_linux64_openblas  conda-forge
-      libnghttp2:                1.52.0-h61bc06f_0          conda-forge
-      libopenblas:               0.3.23-pthreads_h80387f5_0 conda-forge
-      libpng:                    1.6.39-h753d276_0          conda-forge
-      libsanitizer:              13.1.0-hfd8a6a1_0          conda-forge
-      libssh2:                   1.11.0-h0841786_0          conda-forge
-      libstdcxx-devel_linux-64:  13.1.0-he3cc6c4_0          conda-forge
-      libstdcxx-ng:              13.1.0-hfd8a6a1_0          conda-forge
-      libtiff:                   4.5.1-h8b53f26_0           conda-forge
-      libuuid:                   2.38.1-h0b41bf4_0          conda-forge
-      libwebp-base:              1.3.1-hd590300_0           conda-forge
       libxcb:                    1.15-h0b41bf4_0            conda-forge
       libxml2:                   2.11.4-h0d562d8_0          conda-forge
       libzlib:                   1.2.13-hd590300_5          conda-forge
@@ -55,15 +39,15 @@ log: |2-
   [34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
   [?25l[2K[0G[] 0.0s
   [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                       129.0 B @ 324.9kB/s  0.0s
-  opt/conda/conda-bld/noarch                         127.0 B @ 472.1kB/s  0.0s
+  opt/conda/conda-bld/noarch                         127.0 B @ 326.5kB/s  0.0s
   [?25h[34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
   [?25l[2K[0G[] 0.0s
   opt/conda/conda-bl..    [2K[1A[2K[0Gopt/conda/conda-bld/linux-64
-  opt/conda/conda-bld/noarch                         127.0 B @   1.4MB/s  0.0s
+  opt/conda/conda-bld/noarch                         127.0 B @   2.3MB/s  0.0s
   [?25h
   ## Package Plan ##
 
-    environment location: /opt/conda/conda-bld/r-qorts_1689801254594/_build_env
+    environment location: /opt/conda/conda-bld/r-qorts_1689805765070/_build_env
 
 
   Source cache directory is: /opt/conda/conda-bld/src_cache
@@ -75,10 +59,26 @@ log: |2-
   Success
   INFO:conda_build.source:Success
   Extracting download
-  source tree in: /opt/conda/conda-bld/r-qorts_1689801254594/work
-  export PREFIX=/opt/conda/conda-bld/r-qorts_1689801254594/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export BUILD_PREFIX=/opt/conda/conda-bld/r-qorts_1689801254594/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/r-qorts_1689801254594/work
+  source tree in: /opt/conda/conda-bld/r-qorts_1689805765070/work
+  export PREFIX=/opt/conda/conda-bld/r-qorts_1689805765070/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export BUILD_PREFIX=/opt/conda/conda-bld/r-qorts_1689805765070/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/r-qorts_1689805765070/work
+  total 33052
+  -rw-rw-r-- 1 conda conda 3167527 Sep 25  2018 QoRTs-vignette.pdf
+  -rw-rw-r-- 1 conda conda 6983482 Sep 25  2018 QoRTs.jar
+  -rw-rw-r-- 1 conda conda 3620880 Sep 25  2018 QoRTs_1.2.25.tar.gz
+  -rw-rw-r-- 1 conda conda 3620601 Sep 25  2018 QoRTs_1.2.26.tar.gz
+  -rw-rw-r-- 1 conda conda 3620502 Sep 25  2018 QoRTs_1.2.37.tar.gz
+  -rw-rw-r-- 1 conda conda 3622377 Sep 25  2018 QoRTs_1.2.42.tar.gz
+  -rw-rw-r-- 1 conda conda 3622591 Sep 25  2018 QoRTs_1.3.0.tar.gz
+  -rw-rw-r-- 1 conda conda 3622228 Sep 25  2018 QoRTs_1.3.6.tar.gz
+  -rw-rw-r-- 1 conda conda    4243 Sep 25  2018 README.md
+  -rw-r--r-- 1 conda conda   11836 Jul 19 22:33 build_env_setup.sh
+  -rwxrw-rw- 1 conda conda     146 Jul 19 22:33 conda_build.sh
+  -rw-rw-r-- 1 conda conda 1910382 Sep 25  2018 example-walkthrough.pdf
+  -rw-r--r-- 1 conda conda     860 Jul 19 22:33 metadata_conda_debug.yaml
+  drwxrwxr-x 2 conda conda    4096 Sep 25  2018 scripts
+  drwxrwxr-x 4 conda conda    4096 Sep 25  2018 src
   During startup - Warning message:
   Setting LC_TIME failed, using "C"
   Warning: invalid package .
@@ -100,5 +100,5 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/r-qorts_1689801254594/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/r-qorts_1689805765070/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
