[ci skip] add build failure record for recipe recipes/spring

diff --git a/recipes/spring/build_failure.linux-aarch64.yaml b/recipes/spring/build_failure.linux-aarch64.yaml
--- a/recipes/spring/build_failure.linux-aarch64.yaml
+++ b/recipes/spring/build_failure.linux-aarch64.yaml
@@ -1,79 +1,79 @@
-recipe_sha: 5cb0d7d65980f94e1110a51bd5f3319debe2589c45219da8649a0b5bc9932d91  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: e01d17b3aa9eb2f84b7f00c76986649ff6d72391015081544efbb88dc04db501  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |-
-  [ 28%] Linking CXX static library libboost_filesystem.a
-  [ 28%] Built target Boost_filesystem
-  [ 28%] Building CXX object boost-cmake/CMakeFiles/Boost_iostreams.dir/boost/boost_1_67_0/libs/iostreams/src/file_descriptor.cpp.o
-  [ 33%] Building CXX object boost-cmake/CMakeFiles/Boost_iostreams.dir/boost/boost_1_67_0/libs/iostreams/src/mapped_file.cpp.o
-  [ 33%] Building CXX object boost-cmake/CMakeFiles/Boost_iostreams.dir/boost/boost_1_67_0/libs/iostreams/src/gzip.cpp.o
-  [ 33%] Building CXX object boost-cmake/CMakeFiles/Boost_iostreams.dir/boost/boost_1_67_0/libs/iostreams/src/zlib.cpp.o
-  [ 38%] Linking CXX static library libboost_iostreams.a
-  [ 38%] Built target Boost_iostreams
-  [ 38%] Building CXX object CMakeFiles/spring.dir/src/main.cpp.o
-  [ 38%] Building CXX object CMakeFiles/spring.dir/src/spring.cpp.o
-  [ 42%] Building CXX object CMakeFiles/spring.dir/src/util.cpp.o
-  In file included from /opt/conda/conda-bld/spring_1772558679423/work/src/util.cpp:15:
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:43:3: error: 'uint32_t' does not name a type
-     43 |   uint32_t num_reads;
-        |   ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:19:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-     18 | #include <fstream>
-     |#include <cstdint>
-     19 | #include <string>
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:44:3: error: 'uint32_t' does not name a type
-     44 |   uint32_t num_reads_clean[2];
-        |   ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:44:3: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:45:3: error: 'uint32_t' does not name a type
-     45 |   uint32_t max_readlen;
-        |   ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:45:3: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:46:3: error: 'uint8_t' does not name a type
-     46 |   uint8_t paired_id_code;
-        |   ^~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:46:3: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:53:1: error: 'uint32_t' does not name a type
-     53 | uint32_t read_fastq_block(std::istream *fin, std::string *id_array,
-        | ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:53:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:59:30: error: 'uint32_t' does not name a type
-     59 |                        const uint32_t &num_reads,
-        |                              ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:59:30: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:64:30: error: 'uint32_t' does not name a type
-     64 |                        const uint32_t &num_ids);
-        |                              ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:64:30: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:67:32: error: 'uint32_t' does not name a type
-     67 |                          const uint32_t &num_ids);
-        |                                ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:67:32: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:69:57: error: 'uint32_t' does not name a type
-     69 | void quantize_quality(std::string *quality_array, const uint32_t &num_lines,
-        |                                                         ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:69:57: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:72:61: error: 'uint32_t' does not name a type
-     72 | void quantize_quality_qvz(std::string *quality_array, const uint32_t &num_lines,
-        |                                                             ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:72:61: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:73:27: error: 'uint32_t' has not been declared
-     73 |                           uint32_t *str_len_array, double qv_ratio);
-        |                           ^~~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:82:1: error: 'uint8_t' does not name a type
-     82 | uint8_t find_id_pattern(const std::string &id_1, const std::string &id_2);
-        | ^~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:82:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:85:29: error: 'uint8_t' does not name a type
-     85 |                       const uint8_t paired_id_code);
-        |                             ^~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:85:29: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:87:39: error: 'uint8_t' does not name a type
-     87 | void modify_id(std::string &id, const uint8_t paired_id_code);
-        |                                       ^~~~~~~
-  /opt/conda/conda-bld/spring_1772558679423/work/src/util.h:87:39: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
-  make[2]: *** [CMakeFiles/spring.dir/build.make:107: CMakeFiles/spring.dir/src/util.cpp.o] Error 1
-  make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/spring.dir/all] Error 2
-  make: *** [Makefile:91: all] Error 2
+log: |2-
+      - libstdcxx >=14
+      - libgcc >=14
+  test:
+    commands:
+      - spring -h
+  about:
+    home: https://github.com/shubhamchandak94/Spring
+    license: Free for non-commercial use
+    license_file: license.pdf
+    summary: Spring is a compression tool for Fastq files.
+    dev_url: https://github.com/shubhamchandak94/Spring
+  extra:
+    additional-platforms:
+      - linux-aarch64
+    final: true
+    copy_test_source_files: true
+
+
+  source tree in: /opt/conda/conda-bld/spring_1772609455200/work
+  export PREFIX=/opt/conda/conda-bld/spring_1772609455200/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
+  export BUILD_PREFIX=/opt/conda/conda-bld/spring_1772609455200/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/spring_1772609455200/work
+  INFO: activate-binutils_linux-aarch64.sh made the following environmental changes:
+  ADDR2LINE=aarch64-conda-linux-gnu-addr2line
+  AR=aarch64-conda-linux-gnu-ar
+  AS=aarch64-conda-linux-gnu-as
+  CXXFILT=aarch64-conda-linux-gnu-cfilt
+  ELFEDIT=aarch64-conda-linux-gnu-elfedit
+  GPROF=aarch64-conda-linux-gnu-gprof
+  LD=aarch64-conda-linux-gnu-ld
+  NM=aarch64-conda-linux-gnu-nm
+  OBJCOPY=aarch64-conda-linux-gnu-objcopy
+  OBJDUMP=aarch64-conda-linux-gnu-objdump
+  RANLIB=aarch64-conda-linux-gnu-ranlib
+  READELF=aarch64-conda-linux-gnu-readelf
+  SIZE=aarch64-conda-linux-gnu-size
+  STRINGS=aarch64-conda-linux-gnu-strings
+  STRIP=aarch64-conda-linux-gnu-strip
+  INFO: activate-gcc_linux-aarch64.sh made the following environmental changes:
+  BUILD=aarch64-conda-linux-gnu
+  CC=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-cc
+  CC_FOR_BUILD=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-cc
+  CFLAGS=-ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/spring-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/aarch64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
+  CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/aarch64-conda-linux-gnu/sysroot/usr
+  CONDA_BUILD_CROSS_COMPILATION=
+  CONDA_BUILD_SYSROOT=$BUILD_PREFIX/aarch64-conda-linux-gnu/sysroot
+  CONDA_TOOLCHAIN_BUILD=aarch64-conda-linux-gnu
+  CONDA_TOOLCHAIN_HOST=aarch64-conda-linux-gnu
+  CPP=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-cpp
+  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
+  CPP_FOR_BUILD=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-cpp
+  DEBUG_CFLAGS=-ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/spring-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
+  GCC=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc
+  GCC_AR=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc-ar
+  GCC_NM=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc-nm
+  GCC_RANLIB=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-gcc-ranlib
+  HOST=aarch64-conda-linux-gnu
+  LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
+  LDFLAGS_LD=-O2 --sort-common --as-needed -z relro -z now --allow-shlib-undefined -rpath $PREFIX/lib -rpath-link $PREFIX/lib -L$PREFIX/lib
+  MESON_ARGS=-Dbuildtype=release --prefix=$PREFIX -Dlibdir=lib
+  build_alias=aarch64-conda-linux-gnu
+  host_alias=aarch64-conda-linux-gnu
+  -BUILD=aarch64-conda_cos7-linux-gnu
+  -CONDA_BUILD_SYSROOT=
+  INFO: activate-gxx_linux-aarch64.sh made the following environmental changes:
+  CXX=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-c
+  CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/spring-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CXX_FOR_BUILD=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-c
+  DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/spring-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  GXX=$BUILD_PREFIX/bin/aarch64-conda-linux-gnu-g
+  sed: can't read src/util.h: No such file or directory
   Traceback (most recent call last):
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2570, in build
       utils.check_call_env(
@@ -82,7 +82,7 @@ log: |-
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/spring_1772558679423/work/conda_build.sh']' returned non-zero exit status 2.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/spring_1772609455200/work/conda_build.sh']' returned non-zero exit status 2.
 
   The above exception was the direct cause of the following exception:
 
@@ -100,5 +100,5 @@ log: |-
                            ^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/spring_1772558679423/work/conda_build.sh']' returned non-zero exit status 2.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/spring_1772609455200/work/conda_build.sh']' returned non-zero exit status 2.
 # Last 100 lines of the build log.
