[ci skip] add build failure record for recipe recipes/pasa

diff --git a/recipes/pasa/build_failure.osx-64.yaml b/recipes/pasa/build_failure.osx-64.yaml
--- a/recipes/pasa/build_failure.osx-64.yaml
+++ b/recipes/pasa/build_failure.osx-64.yaml
@@ -1,17 +1,17 @@
-recipe_sha: e36fc004df4bd34c0a06e946a0d4cbf455f7e56ba263084d1530037aa42daea0  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 3ee1eedd4261115d101f0a6c8cd2dc235a3937c15a5a4a025490861cd4e7edf0  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-    license_file: LICENSE
-    summary: PASA, acronym for Program to Assemble Spliced Alignments (and pronounced
+          notest=notest,
+      )
+    description: PASA, acronym for Program to Assemble Spliced Alignments (and pronounced
       'pass-uh'), is a eukaryotic genome annotation tool that exploits spliced alignments
-                           ^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 2584, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
       of expressed transcript sequences to automatically model gene structures, and
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/pasa_1773695044737/work/conda_build.sh']' returned non-zero exit status 2.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/pasa_1776760633627/work/conda_build.sh']' returned non-zero exit status 2.
       to maintain gene structure annotation consistent with the most recently available
       experimental sequence data. PASA also identifies and classifies all splicing variations
-      supported by the transcript alignments.
+      supported by the transcript alignments."
     doc_url: https://github.com/PASApipeline/PASApipeline/wiki
     dev_url: https://github.com/PASApipeline/PASApipeline
   extra:
@@ -23,10 +23,10 @@ log: |2-
     copy_test_source_files: true
 
 
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/pasa_1773695044737/work
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pasa_1773695044737/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pasa_1773695044737/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/pasa_1773695044737/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/pasa_1776760633627/work
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pasa_1776760633627/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pasa_1776760633627/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/pasa_1776760633627/work
   INFO: activate_cctools_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
   AS=x86_64-apple-darwin13.4.0-as
