[ci skip] add build failure record for recipe recipes/phanotate

diff --git a/recipes/phanotate/build_failure.osx-64.yaml b/recipes/phanotate/build_failure.osx-64.yaml
--- a/recipes/phanotate/build_failure.osx-64.yaml
+++ b/recipes/phanotate/build_failure.osx-64.yaml
@@ -1,104 +1,104 @@
-recipe_sha: 17c60de8e2f6dbef81350478df00c327c0975bdb606a48bbfae6bf7c76d9e477  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: fd35ac3ea06489788eb05650bb3c11f09b1671cc7fcafcfc031c83171bff1065  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-      libzlib:            1.3.1-hd23fc13_2           conda-forge
-      llvm-openmp:        22.1.0-h0d3cbff_0          conda-forge
-      matplotlib-base:    3.10.8-py310h2102b89_0     conda-forge
-      munkres:            1.1.4-pyhd8ed1ab_1         conda-forge
-      ncurses:            6.5-h0622a9a_3             conda-forge
-      numpy:              2.2.6-py310h07c5b4d_0      conda-forge
-      openjpeg:           2.5.4-h87e8dc5_0           conda-forge
-      openssl:            3.6.1-hb6871ef_1           conda-forge
-      packaging:          26.0-pyhcf101f3_0          conda-forge
-      pandas:             2.3.3-py310h39ce848_1      conda-forge
-      patsy:              1.0.2-pyhcf101f3_0         conda-forge
-      perl:               5.32.1-7_h10d778d_perl5    conda-forge
-      phanotate:          1.6.7-py310hb2740df_3      local
-      pillow:             12.1.1-py310hef2b012_0     conda-forge
-      pthread-stubs:      0.4-h00291cd_1002          conda-forge
-      pyparsing:          3.3.2-pyhcf101f3_0         conda-forge
-      python:             3.10.19-h988dfef_3_cpython conda-forge
-      python-dateutil:    2.9.0.post0-pyhe01879c_2   conda-forge
-      python-tzdata:      2025.3-pyhd8ed1ab_0        conda-forge
-      python_abi:         3.10-8_cp310               conda-forge
-      pytz:               2025.2-pyhd8ed1ab_0        conda-forge
-      qhull:              2020.2-h3c5361c_5          conda-forge
-      readline:           8.3-h68b038d_0             conda-forge
-      scipy:              1.15.2-py310hef62574_0     conda-forge
-      seaborn-base:       0.13.2-pyhd8ed1ab_3        conda-forge
-      setuptools:         82.0.0-pyh332efcf_0        conda-forge
-      six:                1.17.0-pyhe01879c_1        conda-forge
-      statsmodels:        0.14.6-py310h0bce67a_0     conda-forge
-      textwrap3:          0.9.2-py_0                 conda-forge
-      tk:                 8.6.13-h7142dee_3          conda-forge
-      trnascan-se:        2.0.12-pl5321h18d8cf3_2    bioconda
-      tzdata:             2025c-hc9c84f9_1           conda-forge
-      unicodedata2:       17.0.1-py310hf70ac88_0     conda-forge
-      xorg-libxau:        1.0.12-h8616949_1          conda-forge
-      xorg-libxdmcp:      1.1.5-h8616949_1           conda-forge
-      zlib-ng:            2.3.3-h8bce59a_1           conda-forge
-      zstd:               1.5.7-h3eecb57_6           conda-forge
-
-  Preparing transaction: ...working... done
-  ERROR:conda.stderr:
-  Verifying transaction: ...working... done
-  ClobberWarning: This transaction has incompatible packages due to a shared path.
-    packages: conda-forge/noarch::backports-1.0-pyhd8ed1ab_5, conda-forge/noarch::backports.tempfile-1.0-py_0
-    path: 'lib/python3.10/site-packages/backports/__init__.py'
-
-
-  ClobberWarning: This transaction has incompatible packages due to a shared path.
-    packages: conda-forge/noarch::backports-1.0-pyhd8ed1ab_5, conda-forge/noarch::backports.tempfile-1.0-py_0
-    path: 'lib/python3.10/site-packages/backports/__pycache__/__init__.cpython-310.pyc'
-
-
-
-  ERROR:conda.stderr:
-  ClobberWarning: Conda was asked to clobber an existing path.
-    source path: /opt/mambaforge/envs/bioconda/pkgs/backports.tempfile-1.0-py_0/site-packages/backports/__init__.py
-    target path: /opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772386238914/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/backports/__init__.py
-
-
-
-  Executing transaction: ...working... done
-   phanotate.py --version
+log: |-
+  SEG_ADDR_TABLE=x86_64-apple-darwin13.4.0-seg_addr_table
+  SEG_HACK=x86_64-apple-darwin13.4.0-seg_hack
+  SEGEDIT=x86_64-apple-darwin13.4.0-segedit
+  SIZE=x86_64-apple-darwin13.4.0-size
+  STRINGS=x86_64-apple-darwin13.4.0-strings
+  STRIP=x86_64-apple-darwin13.4.0-strip
+  INFO: activate_clang_osx-64.sh made the following environmental changes:
+  ac_cv_func_malloc_0_nonnull=yes
+  ac_cv_func_realloc_0_nonnull=yes
+  build_alias=x86_64-apple-darwin13.4.0
+  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
+  CC=x86_64-apple-darwin13.4.0-clang
+  CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/phanotate-1.6.7 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CLANG=x86_64-apple-darwin13.4.0-clang
+  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-strip -DCMAKE_INSTALL_NAME_TOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-install_name_tool -DCMAKE_LIBTOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET=11.3 -DCMAKE_OSX_SYSROOT=/Applications/Xcode_16.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_FIND_APPBUNDLE=LAST -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
+  CMAKE_PREFIX_PATH=:$PREFIX
+  CONDA_TOOLCHAIN_BUILD=x86_64-apple-darwin13.4.0
+  CONDA_TOOLCHAIN_HOST=x86_64-apple-darwin13.4.0
+  CPP_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang-cpp
+  CPP=x86_64-apple-darwin13.4.0-clang-cpp
+  CPPFLAGS=-D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=11.3
+  DEBUG_CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/phanotate-1.6.7 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  host_alias=x86_64-apple-darwin13.4.0
+  HOST=x86_64-apple-darwin13.4.0
+  LDFLAGS_LD=-headerpad_max_install_names -dead_strip_dylibs -rpath $PREFIX/lib -L$PREFIX/lib
+  LDFLAGS=-Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib
+  MESON_ARGS=-Dbuildtype=release --prefix=$PREFIX -Dlibdir=lib
+  OBJC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
+  OBJC=x86_64-apple-darwin13.4.0-clang
+  INFO: activate_clangxx_osx-64.sh made the following environmental changes:
+  CLANGXX=x86_64-apple-darwin13.4.0-clang
+  CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
+  CXX=x86_64-apple-darwin13.4.0-clang
+  CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/phanotate-1.6.7 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  DEBUG_CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc -fvisibility-inlines-hidden -fmessage-length=0 -Og -g -Wall -Wextra -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/phanotate-1.6.7 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  patching file phanotate_modules/file_handling.py
+  Using pip 26.0.1 from $PREFIX/lib/python3.11/site-packages/pip (python 3.11)
+  Non-user install because user site-packages disabled
+  Ignoring indexes: https://pypi.org/simple
+  Created temporary directory: /private/tmp/pip-build-tracker-334a9jbo
+  Initialized build tracking at /private/tmp/pip-build-tracker-334a9jbo
+  Created build tracker: /private/tmp/pip-build-tracker-334a9jbo
+  Entered build tracker: /private/tmp/pip-build-tracker-334a9jbo
+  Created temporary directory: /private/tmp/pip-install-tpje4ntz
+  Created temporary directory: /private/tmp/pip-ephem-wheel-cache-2rzh2ygm
+  Processing ./.
+    Added file://$SRC_DIR/fastpath-1.9 to build tracker '/private/tmp/pip-build-tracker-334a9jbo'
+    Created temporary directory: /private/tmp/pip-modern-metadata-0mjsulla
+    Preparing metadata (pyproject.toml): started
+    Preparing metadata (pyproject.toml): finished with status 'done'
   Traceback (most recent call last):
-    File "/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772386238914/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/phanotate.py", line 8, in <module>
-      from phanotate_modules.file import File
-    File "/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772386238914/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/phanotate_modules/__init__.py", line 2, in <module>
-      from .file_handling import read_fasta
-    File "/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772386238914/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/phanotate_modules/file_handling.py", line 15, in <module>
-      import pkg_resources
-  ModuleNotFoundError: No module named 'pkg_resources'
-  WARNING: Tests failed for phanotate-1.6.7-py310hb2740df_3.conda - moving package to /opt/mambaforge/envs/bioconda/conda-bld/broken
-  Traceback (most recent call last):
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3497, in test
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772386238914/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772386238914/test_tmp
+    Source in ./. has version 1.9, which satisfies requirement fastpath==1.9 from file://$SRC_DIR/fastpath-1.9
+    Removed fastpath==1.9 from file://$SRC_DIR/fastpath-1.9 from build tracker '/private/tmp/pip-build-tracker-334a9jbo'
+  Created temporary directory: /private/tmp/pip-unpack-1f2la42l
+  Building wheels for collected packages: fastpath
+    Destination directory: /private/tmp/pip-ephem-wheel-cache-2rzh2ygm/wheels/26/f8/c6/7addfd20154c94bcf8fb123b743d3ccb0056aa552be0c7040b/tmp3wkz00td
+    Building wheel for fastpath (pyproject.toml): started
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 2570, in build
       utils.check_call_env(
     File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/utils.py", line 411, in check_call_env
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772386238914/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772403423943/work/conda_build.sh']' returned non-zero exit status 1.
 
-  During handling of the above exception, another exception occurred:
+  The above exception was the direct cause of the following exception:
 
   Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
                ^^^^^^^^^
+    Building wheel for fastpath (pyproject.toml): finished with status 'error'
+  Failed to build fastpath
+  Exception information:
+  Traceback (most recent call last):
+    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 107, in _run_wrapper
+      status = _inner_run()
+               ^^^^^^^^^^^^
+    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 98, in _inner_run
+      return self.run(options, args)
+             ^^^^^^^^^^^^^^^^^^^^^^^
+    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 96, in wrapper
+      return func(self, options, args)
+             ^^^^^^^^^^^^^^^^^^^^^^^^^
+    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 444, in run
+      raise InstallWheelBuildError(build_failures)
+  pip._internal.exceptions.InstallWheelBuildError: <InstallWheelBuildError: failed-wheel-build-for-install>
+  Removed build tracker: '/private/tmp/pip-build-tracker-334a9jbo'
     File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
       api.build(
     File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
       return build_tree(
              ^^^^^^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3684, in build_tree
-      test(pkg, config=metadata.config.copy(), stats=stats)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3511, in test
-      tests_failed(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3558, in tests_failed
-      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
-  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: phanotate-1.6.7-py310hb2740df_3.conda
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3669, in build_tree
+      packages_from_this = build(
+                           ^^^^^^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/phanotate_1772403423943/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
