[ci skip] add build failure record for recipe recipes/bioconductor-interactivedisplay

diff --git a/recipes/bioconductor-interactivedisplay/build_failure.linux-64.yaml b/recipes/bioconductor-interactivedisplay/build_failure.linux-64.yaml
--- a/recipes/bioconductor-interactivedisplay/build_failure.linux-64.yaml
+++ b/recipes/bioconductor-interactivedisplay/build_failure.linux-64.yaml
@@ -1,50 +1,43 @@
-recipe_sha: 2e953b34550b7c2560316e98934f32e431666d1521470ee9f04b8e9bd3d68747  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 0a148c3357b26aadea915f47053a07d96b871a62dee8f9758cbf63b0a16bbc98  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      - r-bslib 0.8.0 r44hc72bb7e_0
-      - r-reshape2 1.4.4 r44h0d4f4ea_4
-      - r-rsqlite 2.3.9 r44h93ab643_0
-      - r-tibble 3.2.1 r44hdb488b9_3
-      - bioconductor-genomeinfodb 1.42.0 r44hdfd78af_0
-      - r-ggplot2 3.5.1 r44hc72bb7e_1
-      - r-rmarkdown 2.29 r44hc72bb7e_0
-      - r-shiny 1.10.0 r44h785f33e_0
-      - bioconductor-biostrings 2.74.0 r44h3df3fcb_0
-      - r-htmlwidgets 1.6.4 r44h785f33e_3
-      - bioconductor-keggrest 1.46.0 r44hdfd78af_0
-      - r-dt 0.33 r44hc72bb7e_1
-      - bioconductor-annotationdbi 1.68.0 r44hdfd78af_0
-      - bioconductor-interactivedisplaybase 1.44.0 r44hdfd78af_0
-      - bioconductor-annotate 1.84.0 r44hdfd78af_0
-      - bioconductor-genefilter 1.88.0 r44h81e381d_0
-      - bioconductor-gseabase 1.68.0 r44hdfd78af_0
-      - bioconductor-category 2.72.0 r44hdfd78af_0
+      - r-rsqlite 2.4.6 r45h3697838_0
+      - bioconductor-biostrings 2.78.0 r45h01b2380_0
+      - r-rmarkdown 2.30 r45hc72bb7e_0
+      - r-shiny 1.13.0 r45h785f33e_0
+      - bioconductor-keggrest 1.50.0 r45hdfd78af_0
+      - r-htmlwidgets 1.6.4 r45h785f33e_4
+      - bioconductor-annotationdbi 1.72.0 r45hdfd78af_0
+      - r-dt 0.34.0 r45hc72bb7e_1
+      - bioconductor-annotate 1.88.0 r45hdfd78af_0
+      - bioconductor-interactivedisplaybase 1.48.0 r45hdfd78af_0
+      - bioconductor-genefilter 1.92.0 r45h9e4a190_0
+      - bioconductor-gseabase 1.72.0 r45hdfd78af_0
+      - bioconductor-category 2.76.0 r45hdfd78af_0
     run:
-      - bioconductor-biocgenerics >=0.52.0,<0.53.0
-      - r-base >=4.4,<4.5.0a0
-      - r-base >=4.4,<4.5.0a0
-      - r-reshape2
-      - r-shiny
-      - r-rcolorbrewer
-      - bioconductor-category >=2.72.0,<2.73.0
-      - r-plyr
       - r-gridsvg
-      - bioconductor-interactivedisplaybase >=1.44.0,<1.45.0
-      - bioconductor-annotationdbi >=1.68.0,<1.69.0
+      - bioconductor-biocgenerics >=0.56.0,<0.57.0
+      - r-rcolorbrewer
+      - r-plyr
+      - r-shiny
       - r-ggplot2
+      - bioconductor-annotationdbi >=1.72.0,<1.73.0
+      - bioconductor-category >=2.76.0,<2.77.0
+      - r-base >=4.5,<4.6.0a0
+      - r-base >=4.5,<4.6.0a0
+      - r-reshape2
       - r-xml
+      - bioconductor-interactivedisplaybase >=1.48.0,<1.49.0
   test:
     commands:
       - $R -e "library('interactiveDisplay')"
   about:
-    description: The interactiveDisplay package contains the methods needed to generate
-      interactive Shiny based display methods for Bioconductor objects.
-    home: https://bioconductor.org/packages/3.20/bioc/html/interactiveDisplay.html
+    home: https://bioconductor.org/packages/3.22/bioc/html/interactiveDisplay.html
     license: Artistic-2.0
     summary: Package for enabling powerful shiny web displays of Bioconductor objects
+    description: The interactiveDisplay package contains the methods needed to generate
+      interactive Shiny based display methods for Bioconductor objects.
   extra:
-    copy_test_source_files: true
-    final: true
     identifiers:
       - biotools:interactivedisplay
       - doi:10.1038/nmeth.3252
@@ -52,16 +45,19 @@ log: |2-
       name: bioconductor-interactivedisplay
       path: recipes/bioconductor-interactivedisplay
       version: 1.18.0
+    final: true
+    copy_test_source_files: true
 
 
-  source tree in: /opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/work
-  export PREFIX=/opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
-  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/work
+  source tree in: /opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/work
+  export PREFIX=/opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/work
   During startup - Warning message:
   Setting LC_TIME failed, using "C"
-  * installing to library /opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library
+  * installing to library /opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library
   * installing *source* package interactiveDisplay ...
+  ** this is package interactiveDisplay version 1.48.0
   ** package interactiveDisplay successfully unpacked and MD5 sums checked
   ** using staged installation
   ** R
@@ -77,28 +73,32 @@ log: |2-
   Error: unable to load R code in package interactiveDisplay
   Execution halted
   ERROR: lazy loading failed for package interactiveDisplay
-  * removing /opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/interactiveDisplay
+  * removing /opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/library/interactiveDisplay
   Traceback (most recent call last):
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2570, in build
       utils.check_call_env(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 404, in check_call_env
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 411, in check_call_env
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
+             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/work/conda_build.sh']' returned non-zero exit status 1.
 
   The above exception was the direct cause of the following exception:
 
   Traceback (most recent call last):
     File "/opt/conda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
+               ^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
       api.build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
       return build_tree(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
+             ^^^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3669, in build_tree
       packages_from_this = build(
-    File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
+                           ^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-interactivedisplay_1735589677364/work/conda_build.sh']' returned non-zero exit status 1.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-interactivedisplay_1772483169679/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
