[ci skip] add build failure record for recipe recipes/tiptoft

diff --git a/recipes/tiptoft/build_failure.linux-64.yaml b/recipes/tiptoft/build_failure.linux-64.yaml
--- a/recipes/tiptoft/build_failure.linux-64.yaml
+++ b/recipes/tiptoft/build_failure.linux-64.yaml
@@ -1,104 +1,104 @@
-recipe_sha: d64eb0afcb957606c8a2582ee382b367d9e63af84cd27659d25ad04659e40a2d  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 2962775c713b2669a11e38effef9865a2beb6c5fb2ae7b6fc4762de5950e2fb7  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |-
-  bin/tiptoft (text): Patching
-  bin/tiptoft_database_downloader (text): Patching
-  WARNING: Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
-  TEST START: /opt/conda/conda-bld/linux-64/tiptoft-1.0.2-py310h7c10099_5.conda
-  Adding in variants from /tmp/tmpsy391e9o/info/recipe/conda_build_config.yaml
-  Adding in variants from config.variant
-  Renaming /opt/conda/conda-bld/tiptoft_1773661290988/_build_env prefix directory '/opt/conda/conda-bld/tiptoft_1773661290988/_build_env' to '/opt/conda/conda-bld/tiptoft_1773661290988/build_prefix_moved_tiptoft-1.0.2-py310h7c10099_5_linux-64'
-  shutil.move(/opt/conda/conda-bld/tiptoft_1773661290988/_build_env prefix)=/opt/conda/conda-bld/tiptoft_1773661290988/_build_env, dest=/opt/conda/conda-bld/tiptoft_1773661290988/build_prefix_moved_tiptoft-1.0.2-py310h7c10099_5_linux-64)
-  Renaming work directory '/opt/conda/conda-bld/tiptoft_1773661290988/work' to '/opt/conda/conda-bld/tiptoft_1773661290988/work_moved_tiptoft-1.0.2-py310h7c10099_5_linux-64'
-  shutil.move(work)=/opt/conda/conda-bld/tiptoft_1773661290988/work, dest=/opt/conda/conda-bld/tiptoft_1773661290988/work_moved_tiptoft-1.0.2-py310h7c10099_5_linux-64)
-  Reloading output folder: ...working... done
-  Solving environment (_test_env): ...working... done
+log: |2-
+    [31m   [0m /opt/conda/conda-bld/tiptoft_1776756960140/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.13/site-packages/setuptools/_distutils/dist.py:287: UserWarning: Unknown distribution option: 'tests_require'
+    [31m   [0m   warnings.warn(msg)
+    [31m   [0m /opt/conda/conda-bld/tiptoft_1776756960140/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.13/site-packages/setuptools/dist.py:765: SetuptoolsDeprecationWarning: License classifiers are deprecated.
+    [31m   [0m !!
+    [31m   [0m
+    [31m   [0m         ********************************************************************************
+    [31m   [0m         Please consider removing the following classifiers in favor of a SPDX license expression:
+    [31m   [0m
+    [31m   [0m         License :: OSI Approved :: GNU General Public License v3 (GPLv3)
+    [31m   [0m
+    [31m   [0m         See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
+    [31m   [0m         ********************************************************************************
+    [31m   [0m
+    [31m   [0m !!
+    [31m   [0m   self._finalize_license_expression()
+    [31m   [0m running bdist_wheel
+    [31m   [0m running build
+    [31m   [0m running build_py
+    [31m   [0m creating build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/__init__.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/Fastq.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/RefGenesGetter.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/InputTypes.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/Blocks.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/Kmers.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/Fasta.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/Gene.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/TipToftDatabaseDownloader.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/Read.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m copying tiptoft/TipToft.py -> build/lib.linux-x86_64-cpython-313/tiptoft
+    [31m   [0m creating build/lib.linux-x86_64-cpython-313/tiptoft/data
+    [31m   [0m copying tiptoft/data/plasmid_data.fa -> build/lib.linux-x86_64-cpython-313/tiptoft/data
+    [31m   [0m copying tiptoft/data/20180928.txt -> build/lib.linux-x86_64-cpython-313/tiptoft/data
+    [31m   [0m copying tiptoft/data/plasmid_data.tsv -> build/lib.linux-x86_64-cpython-313/tiptoft/data
+    [31m   [0m running build_ext
+    [31m   [0m building 'homopolymer_compression' extension
+    [31m   [0m creating build/temp.linux-x86_64-cpython-313
+    [31m   [0m /opt/conda/conda-bld/tiptoft_1776756960140/_build_env/bin/x86_64-conda-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/conda-bld/tiptoft_1776756960140/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/tiptoft_1776756960140/work=/usr/local/src/conda/tiptoft-1.0.2 -fdebug-prefix-map=/opt/conda/conda-bld/tiptoft_1776756960140/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/conda/conda-bld/tiptoft_1776756960140/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fPIC -I/opt/conda/conda-bld/tiptoft_1776756960140/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include/python3.13 -c homopolymer_compression.c -o build/temp.linux-x86_64-cpython-313/homopolymer_compression.o
+    [31m   [0m homopolymer_compression.c:193:12: fatal error: longintrepr.h: No such file or directory
+    [31m   [0m   193 |   #include "longintrepr.h"
+    [31m   [0m       |            ^~~~~~~~~~~~~~~
+    [31m   [0m compilation terminated.
+    [31m   [0m error: command '/opt/conda/conda-bld/tiptoft_1776756960140/_build_env/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
+    [31m   [0m [31m[end of output][0m
 
-  ## Package Plan ##
+    [1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
+  [31m  ERROR: Failed building wheel for tiptoft[0m[31m
+  [0mFailed to build tiptoft
+  [1;31merror[0m: [1mfailed-wheel-build-for-install[0m
 
-    environment location: /opt/conda/conda-bld/tiptoft_1773661290988/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-
-
-  The following NEW packages will be INSTALLED:
-
-      _openmp_mutex:    4.5-20_gnu                  conda-forge
-      biopython:        1.86-py310h7c4b9e2_1        conda-forge
-      bzip2:            1.0.8-hda65f42_9            conda-forge
-      ca-certificates:  2026.2.25-hbd8a1cb_0        conda-forge
-      cython:           3.2.4-py310ha58568a_0       conda-forge
-      icu:              78.2-h33c6efd_0             conda-forge
-      ld_impl_linux-64: 2.45.1-default_hbd61a6d_101 conda-forge
-      libblas:          3.11.0-5_h4a7cf45_openblas  conda-forge
-      libcblas:         3.11.0-5_h0358290_openblas  conda-forge
-      libexpat:         2.7.4-hecca717_0            conda-forge
-      libffi:           3.5.2-h3435931_0            conda-forge
-      libgcc:           15.2.0-he0feb66_18          conda-forge
-      libgcc-ng:        15.2.0-h69a702a_18          conda-forge
-      libgfortran:      15.2.0-h69a702a_18          conda-forge
-      libgfortran5:     15.2.0-h68bc16d_18          conda-forge
-      libgomp:          15.2.0-he0feb66_18          conda-forge
-      liblapack:        3.11.0-5_h47877c9_openblas  conda-forge
-      liblzma:          5.8.2-hb03c661_0            conda-forge
-      libnsl:           2.0.1-hb9d3cd8_1            conda-forge
-      libopenblas:      0.3.30-pthreads_h94d23a6_4  conda-forge
-      libsqlite:        3.52.0-hf4e2dac_0           conda-forge
-      libstdcxx:        15.2.0-h934c35e_18          conda-forge
-      libuuid:          2.41.3-h5347b49_0           conda-forge
-      libxcrypt:        4.4.36-hd590300_1           conda-forge
-      libzlib:          1.3.1-hb9d3cd8_2            conda-forge
-      ncurses:          6.5-h2d0b736_3              conda-forge
-      numpy:            2.2.6-py310hefbff90_0       conda-forge
-      openssl:          3.6.1-h35e630c_1            conda-forge
-      packaging:        26.0-pyhcf101f3_0           conda-forge
-      pip:              26.0.1-pyh8b19718_0         conda-forge
-      pyfastaq:         3.18.0-pyhdfd78af_0         bioconda
-      python:           3.10.20-h3c07f61_0_cpython  conda-forge
-      python_abi:       3.10-8_cp310                conda-forge
-      readline:         8.3-h853b02a_0              conda-forge
-      setuptools:       82.0.1-pyh332efcf_0         conda-forge
-      tiptoft:          1.0.2-py310h7c10099_5       local
-      tk:               8.6.13-noxft_h366c992_103   conda-forge
-      tzdata:           2025c-hc9c84f9_1            conda-forge
-      wheel:            0.46.3-pyhd8ed1ab_0         conda-forge
-      zstd:             1.5.7-hb78ec9c_6            conda-forge
-
-  Preparing transaction: ...working... done
-  Verifying transaction: ...working... done
-  Executing transaction: ...working... done
-  export PREFIX=/opt/conda/conda-bld/tiptoft_1773661290988/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export SRC_DIR=/opt/conda/conda-bld/tiptoft_1773661290988/test_tmp
-   tiptoft --help
+  [31m[0m Failed to build installable wheels for some pyproject.toml based projects
+  [31m>[0m tiptoft
   Traceback (most recent call last):
-    File "/opt/conda/conda-bld/tiptoft_1773661290988/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/tiptoft", line 6, in <module>
-      import pkg_resources
-  ModuleNotFoundError: No module named 'pkg_resources'
-  WARNING: Tests failed for tiptoft-1.0.2-py310h7c10099_5.conda - moving package to /opt/conda/conda-bld/broken
-  Traceback (most recent call last):
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3497, in test
-      utils.check_call_env(
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 411, in check_call_env
+    File [35m"/opt/conda/lib/python3.13/site-packages/conda_build/build.py"[0m, line [35m2576[0m, in [35mbuild[0m
+      [31mutils.check_call_env[0m[1;31m([0m
+      [31m~~~~~~~~~~~~~~~~~~~~[0m[1;31m^[0m
+          [1;31mcmd,[0m
+          [1;31m^^^^[0m
+      ...<3 lines>...
+          [1;31mstats=build_stats,[0m
+          [1;31m^^^^^^^^^^^^^^^^^^[0m
+      [1;31m)[0m
+      [1;31m^[0m
+    File [35m"/opt/conda/lib/python3.13/site-packages/conda_build/utils.py"[0m, line [35m411[0m, in [35mcheck_call_env[0m
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
-             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
+    File [35m"/opt/conda/lib/python3.13/site-packages/conda_build/utils.py"[0m, line [35m387[0m, in [35m_func_defaulting_env_to_os_environ[0m
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/tiptoft_1773661290988/test_tmp/conda_test_runner.sh']' returned non-zero exit status 1.
+  [1;35msubprocess.CalledProcessError[0m: [35mCommand '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/tiptoft_1776756960140/work/conda_build.sh']' returned non-zero exit status 1.[0m
 
-  During handling of the above exception, another exception occurred:
+  The above exception was the direct cause of the following exception:
 
   Traceback (most recent call last):
-    File "/opt/conda/bin/conda-build", line 11, in <module>
-      sys.exit(execute())
-               ^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
-      api.build(
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
+    File [35m"/opt/conda/bin/conda-build"[0m, line [35m10[0m, in [35m<module>[0m
+      sys.exit([31mexecute[0m[1;31m()[0m)
+               [31m~~~~~~~[0m[1;31m^^[0m
+    File [35m"/opt/conda/lib/python3.13/site-packages/conda_build/cli/main_build.py"[0m, line [35m639[0m, in [35mexecute[0m
+      [31mapi.build[0m[1;31m([0m
+      [31m~~~~~~~~~[0m[1;31m^[0m
+          [1;31mparsed.recipe,[0m
+          [1;31m^^^^^^^^^^^^^^[0m
+      ...<8 lines>...
+          [1;31mcache_dir=parsed.cache_dir,[0m
+          [1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
+      [1;31m)[0m
+      [1;31m^[0m
+    File [35m"/opt/conda/lib/python3.13/site-packages/conda_build/api.py"[0m, line [35m211[0m, in [35mbuild[0m
       return build_tree(
-             ^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3684, in build_tree
-      test(pkg, config=metadata.config.copy(), stats=stats)
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3511, in test
-      tests_failed(
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3558, in tests_failed
-      raise CondaBuildUserError("TESTS FAILED: "  os.path.basename(pkg))
-  conda_build.exceptions.CondaBuildUserError: TESTS FAILED: tiptoft-1.0.2-py310h7c10099_5.conda
+          recipes,
+      ...<7 lines>...
+          variants=variants,
+      )
+    File [35m"/opt/conda/lib/python3.13/site-packages/conda_build/build.py"[0m, line [35m3675[0m, in [35mbuild_tree[0m
+      packages_from_this = build(
+          metadata,
+      ...<5 lines>...
+          notest=notest,
+      )
+    File [35m"/opt/conda/lib/python3.13/site-packages/conda_build/build.py"[0m, line [35m2584[0m, in [35mbuild[0m
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  [1;35mconda_build.exceptions.BuildScriptException[0m: [35mCommand '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/tiptoft_1776756960140/work/conda_build.sh']' returned non-zero exit status 1.[0m
 # Last 100 lines of the build log.
