[ci skip] add build failure record for recipe recipes/maxentpy

diff --git a/recipes/maxentpy/build_failure.osx-64.yaml b/recipes/maxentpy/build_failure.osx-64.yaml
--- a/recipes/maxentpy/build_failure.osx-64.yaml
+++ b/recipes/maxentpy/build_failure.osx-64.yaml
@@ -1,9 +1,8 @@
-recipe_sha: 1d1ad5b3d69067f6869670bc6506348d64ac53eb1d36a4951067698f7340d69b  # The hash of the recipe's meta.yaml at which this recipe failed to build.
-skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-category: compiler error
+recipe_sha: 51a33edb249bbe7f0b567e6b5e0d6e6aa27af55c9f3d69af778be26468bb9805  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |-
   Extracting download
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1717952870501/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1718209249491/work
   Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
@@ -15,19 +14,19 @@ log: |-
       packages_from_this = build(
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
       utils.check_call_env(
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1717952870501/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1717952870501/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1717952870501/work
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1718209249491/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1718209249491/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1718209249491/work
   INFO: activate_clang_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
-  AS=x86_64-apple-darwin13.4.0-as
-  CC=x86_64-apple-darwin13.4.0-clang
-  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
+  AS=x86_64-apple-darwin13.4.0-as
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1717952870501/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/maxentpy_1718209249491/work/conda_build.sh']' returned non-zero exit status 1.
+  CC=x86_64-apple-darwin13.4.0-clang
+  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
   CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/maxentpy-0.0.3 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
   CHECKSYMS=x86_64-apple-darwin13.4.0-checksyms
   CLANG=x86_64-apple-darwin13.4.0-clang
@@ -65,41 +64,41 @@ log: |-
   ac_cv_func_realloc_0_nonnull=yes
   build_alias=x86_64-apple-darwin13.4.0
   host_alias=x86_64-apple-darwin13.4.0
-  Using pip 24.0 from $PREFIX/lib/python3.11/site-packages/pip (python 3.11)
+  Using pip 24.0 from $PREFIX/lib/python3.12/site-packages/pip (python 3.12)
   Non-user install because user site-packages disabled
   Ignoring indexes: https://pypi.org/simple
-  Created temporary directory: /private/tmp/pip-build-tracker-g65x0cd_
-  Initialized build tracking at /private/tmp/pip-build-tracker-g65x0cd_
-  Created build tracker: /private/tmp/pip-build-tracker-g65x0cd_
-  Entered build tracker: /private/tmp/pip-build-tracker-g65x0cd_
-  Created temporary directory: /private/tmp/pip-install-3nlqli9h
-  Created temporary directory: /private/tmp/pip-ephem-wheel-cache-i42r7nvk
+  Created temporary directory: /private/tmp/pip-build-tracker-8s2t6exr
+  Initialized build tracking at /private/tmp/pip-build-tracker-8s2t6exr
+  Created build tracker: /private/tmp/pip-build-tracker-8s2t6exr
+  Entered build tracker: /private/tmp/pip-build-tracker-8s2t6exr
+  Created temporary directory: /private/tmp/pip-install-sl7ce4go
+  Created temporary directory: /private/tmp/pip-ephem-wheel-cache-uyfkcu5k
   Processing $SRC_DIR
-    Added file://$SRC_DIR to build tracker '/private/tmp/pip-build-tracker-g65x0cd_'
+    Added file://$SRC_DIR to build tracker '/private/tmp/pip-build-tracker-8s2t6exr'
     Running setup.py (path:$SRC_DIR/setup.py) egg_info for package from file://$SRC_DIR
-    Created temporary directory: /private/tmp/pip-pip-egg-info-rcx5bs8b
+    Created temporary directory: /private/tmp/pip-pip-egg-info-670xeor4
     Preparing metadata (setup.py): started
     Preparing metadata (setup.py): finished with status 'done'
     Source in $SRC_DIR has version 0.0.3, which satisfies requirement maxentpy==0.0.3 from file://$SRC_DIR
-    Removed maxentpy==0.0.3 from file://$SRC_DIR from build tracker '/private/tmp/pip-build-tracker-g65x0cd_'
-  Created temporary directory: /private/tmp/pip-unpack-ng39aqsu
+    Removed maxentpy==0.0.3 from file://$SRC_DIR from build tracker '/private/tmp/pip-build-tracker-8s2t6exr'
+  Created temporary directory: /private/tmp/pip-unpack-2a7b86gw
   Building wheels for collected packages: maxentpy
-    Created temporary directory: /private/tmp/pip-wheel-_mks2_a4
+    Created temporary directory: /private/tmp/pip-wheel-t6fw4vwl
     Building wheel for maxentpy (setup.py): started
-    Destination directory: /private/tmp/pip-wheel-_mks2_a4
+    Destination directory: /private/tmp/pip-wheel-t6fw4vwl
     Building wheel for maxentpy (setup.py): finished with status 'error'
     Running setup.py clean for maxentpy
   Failed to build maxentpy
   Exception information:
   Traceback (most recent call last):
-    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
+    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
       status = run_func(*args)
                ^^^^^^^^^^^^^^^
-    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
+    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
       return func(self, options, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "$PREFIX/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 429, in run
+    File "$PREFIX/lib/python3.12/site-packages/pip/_internal/commands/install.py", line 429, in run
       raise InstallationError(
   pip._internal.exceptions.InstallationError: Could not build wheels for maxentpy, which is required to install pyproject.toml-based projects
-  Removed build tracker: '/private/tmp/pip-build-tracker-g65x0cd_'
+  Removed build tracker: '/private/tmp/pip-build-tracker-8s2t6exr'
 # Last 100 lines of the build log.
