Circleci fixes (#7684)
* circleci: explicitly install git, pip

* circleci: save config to workspace and cache

* circleci: early exit nightly uploads on forks

* circleci: avoid BASH_ENV, use custom script

* circleci: local: enable devtoolset-2

* circleci: go back to using BASH_ENV, but set PATH conditionally

* circleci: let builds fail if CI config is out of date

* circleci: use skip_fork for bulk and upload

* circleci: revert BASH_ENV changes

* circleci: abort master/bulk upload builds on forks

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -26,6 +26,23 @@ variables:
       LANG: en_US.UTF-8
   linux: &linux
     machine: true
+  skip_fork: &skip_fork
+    run:
+      name: Check for fork
+      command: |
+        [[ CIRCLE_PROJECT_USERNAME == bioconda ]] || (
+            echo "Skipping build for fork '$CIRCLE_PROJECT_USERNAME'"
+            circleci step halt
+        )
+  fail_fork: &fail_fork
+    run:
+      name: Check for fork
+      command: |
+        [[ CIRCLE_PROJECT_USERNAME == bioconda ]] || (
+            echo "Aborting build for fork '$CIRCLE_PROJECT_USERNAME'"
+            echo "Please use a branch other than 'master' or 'bulk' on your fork"
+            exit 1
+        )
 
 jobs:
   # When running CircleCI locally, we put everything in one job.
@@ -40,8 +57,8 @@ jobs:
             mkdir -p ~/.ssh
             ssh-keyscan -H github.com >> ~/.ssh/known_hosts
       - run: 
-          name: linking conda
-          command: ln -s /opt/conda $HOME/miniconda
+          name: Setup base system
+          command: echo '. /opt/docker/bin/entrypoint_source' >> $BASH_ENV
       - *common
       - *setup
       - run:
@@ -96,6 +113,7 @@ jobs:
   upload-linux:
     <<: *linux
     steps:
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
@@ -110,6 +128,7 @@ jobs:
   upload-macos:
     <<: *macos
     steps:
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
@@ -124,6 +143,7 @@ jobs:
   bulk-linux:
     <<: *linux
     steps:
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
@@ -138,6 +158,7 @@ jobs:
   bulk-macos:
     <<: *macos
     steps:
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
@@ -153,6 +174,7 @@ jobs:
   nightly-upload-linux:
     <<: *linux
     steps:
+      - *skip_fork
       - checkout
       - *common
       - *restore_cache
@@ -166,6 +188,7 @@ jobs:
   nightly-upload-macos:
     <<: *macos
     steps:
+      - *skip_fork
       - checkout
       - *common
       - *restore_cache
