circleci: abort master/bulk upload builds on forks

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -30,8 +30,19 @@ variables:
     run:
       name: Check for fork
       command: |
-        [[ CIRCLE_PROJECT_USERNAME == bioconda ]] || \
-        (echo "Skipping build for fork '$CIRCLE_PROJECT_USERNAME'" && circleci step halt)
+        [[ CIRCLE_PROJECT_USERNAME == bioconda ]] || (
+            echo "Skipping build for fork '$CIRCLE_PROJECT_USERNAME'"
+            circleci step halt
+        )
+  fail_fork: &fail_fork
+    run:
+      name: Check for fork
+      command: |
+        [[ CIRCLE_PROJECT_USERNAME == bioconda ]] || (
+            echo "Aborting build for fork '$CIRCLE_PROJECT_USERNAME'"
+            echo "Please use a branch other than 'master' or 'bulk' on your fork"
+            exit 1
+        )
 
 jobs:
   # When running CircleCI locally, we put everything in one job.
@@ -102,7 +113,7 @@ jobs:
   upload-linux:
     <<: *linux
     steps:
-      - *skip_fork
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
@@ -117,7 +128,7 @@ jobs:
   upload-macos:
     <<: *macos
     steps:
-      - *skip_fork
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
@@ -132,7 +143,7 @@ jobs:
   bulk-linux:
     <<: *linux
     steps:
-      - *skip_fork
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
@@ -147,7 +158,7 @@ jobs:
   bulk-macos:
     <<: *macos
     steps:
-      - *skip_fork
+      - *fail_fork
       - checkout
       - *common
       - *restore_cache
