[ci skip] add build failure record for recipe recipes/kmasker

diff --git a/recipes/kmasker/build_failure.linux-64.yaml b/recipes/kmasker/build_failure.linux-64.yaml
--- a/recipes/kmasker/build_failure.linux-64.yaml
+++ b/recipes/kmasker/build_failure.linux-64.yaml
@@ -1,29 +1,90 @@
-recipe_sha: 7c1d814e77e5ab3f47a0e47d15c3e3200b47a2390c509eaf5c51f8469ca64d9c  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: b0cffc0fd114b470af474187c778895e223cbac8305266afceca070b01bb932a  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-                    ^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 179, in solve_final_state
-      out_state = self._solving_loop(in_state, out_state, index)
-                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda/common/io.py", line 87, in decorated
-      return f(*args, **kwds)
-             ^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 305, in _solving_loop
-      solved, outcome = self._solve_attempt(in_state, out_state, index, attempt=attempt)
-                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 362, in _solve_attempt
-      new_conflicts = self._maybe_raise_for_problems(outcome, index, out_state, old_conflicts)
-                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 759, in _maybe_raise_for_problems
-      self._maybe_raise_for_conda_build(
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 849, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("jellyfish==2.2.10=h6bb024c_1")}
-  Encountered problems while solving:
-    - package jellyfish-2.2.10-h6bb024c_1 is excluded by strict repo priority
+log: |-
+  about:
+    home: https://kmasker.ipk-gatersleben.de/
+    license: GPL-3.0-or-later
+    license_file: LICENSE
+    summary: A tool for masking and exploring of sequences from plant species.
+    dev_url: https://github.com/tschmutzer/kmasker
+  extra:
+    identifiers:
+      - biotools:kmasker
+    final: true
+    copy_test_source_files: true
 
 
-  During handling of the above exception, another exception occurred:
+  source tree in: /opt/conda/conda-bld/kmasker_1772588427692/work
+  export PREFIX=/opt/conda/conda-bld/kmasker_1772588427692/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export BUILD_PREFIX=/opt/conda/conda-bld/kmasker_1772588427692/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/kmasker_1772588427692/work
+  INFO: activate-binutils_linux-64.sh made the following environmental changes:
+  ADDR2LINE=x86_64-conda-linux-gnu-addr2line
+  AR=x86_64-conda-linux-gnu-ar
+  AS=x86_64-conda-linux-gnu-as
+  CXXFILT=x86_64-conda-linux-gnu-cfilt
+  ELFEDIT=x86_64-conda-linux-gnu-elfedit
+  GPROF=x86_64-conda-linux-gnu-gprof
+  LD=x86_64-conda-linux-gnu-ld
+  NM=x86_64-conda-linux-gnu-nm
+  OBJCOPY=x86_64-conda-linux-gnu-objcopy
+  OBJDUMP=x86_64-conda-linux-gnu-objdump
+  RANLIB=x86_64-conda-linux-gnu-ranlib
+  READELF=x86_64-conda-linux-gnu-readelf
+  SIZE=x86_64-conda-linux-gnu-size
+  STRINGS=x86_64-conda-linux-gnu-strings
+  STRIP=x86_64-conda-linux-gnu-strip
+  INFO: activate-gcc_linux-64.sh made the following environmental changes:
+  BUILD=x86_64-conda-linux-gnu
+  CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
+  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
+  CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/kmasker-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
+  CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr
+  CONDA_BUILD_CROSS_COMPILATION=
+  CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot
+  CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
+  CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
+  CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
+  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
+  CPP_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
+  DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/kmasker-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
+  GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
+  GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
+  GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
+  GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
+  HOST=x86_64-conda-linux-gnu
+  LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
+  LDFLAGS_LD=-O2 --sort-common --as-needed -z relro -z now --disable-new-dtags --gc-sections --allow-shlib-undefined -rpath $PREFIX/lib -rpath-link $PREFIX/lib -L$PREFIX/lib
+  MESON_ARGS=-Dbuildtype=release --prefix=$PREFIX -Dlibdir=lib
+  build_alias=x86_64-conda-linux-gnu
+  host_alias=x86_64-conda-linux-gnu
+  -BUILD=x86_64-conda_cos6-linux-gnu
+  -CONDA_BUILD_SYSROOT=
+  INFO: activate-gxx_linux-64.sh made the following environmental changes:
+  CXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
+  CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/kmasker-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
+  DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/kmasker-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+  GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g -o src/masker.o -c -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/kmasker-1.1.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -std=c0x -Wall -I$PREFIX/include/jellyfish-2.2.10 src/masker.cc
+  src/masker.cc:21:10: fatal error: jellyfish/err.hpp: No such file or directory
+     21 | #include <jellyfish/err.hpp>
+        |          ^~~~~~~~~~~~~~~~~~~
+  compilation terminated.
+  scons: *** [src/masker.o] Error 1
+  Traceback (most recent call last):
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2570, in build
+      utils.check_call_env(
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 411, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/kmasker_1772588427692/work/conda_build.sh']' returned non-zero exit status 2.
+
+  The above exception was the direct cause of the following exception:
 
   Traceback (most recent call last):
     File "/opt/conda/bin/conda-build", line 11, in <module>
@@ -37,68 +98,7 @@ log: |2-
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3669, in build_tree
       packages_from_this = build(
                            ^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2350, in build
-      output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
-                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/render.py", line 1000, in expand_outputs
-      for output_dict, m in deepcopy(_m).get_output_metadata_set(
-                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/metadata.py", line 2781, in get_output_metadata_set
-      conda_packages = finalize_outputs_pass(
-                       ^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/metadata.py", line 1077, in finalize_outputs_pass
-      fm = finalize_metadata(
-           ^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/render.py", line 722, in finalize_metadata
-      build_unsat, host_unsat = add_upstream_pins(
-                                ^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/render.py", line 507, in add_upstream_pins
-      host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(
-                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/render.py", line 453, in _read_upstream_pin_files
-      deps, precs, unsat = get_env_dependencies(
-                           ^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/render.py", line 162, in get_env_dependencies
-      precs = environ.get_package_records(
-              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/environ.py", line 939, in get_install_actions
-      precs = get_package_records(
-              ^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/environ.py", line 939, in get_install_actions
-      precs = get_package_records(
-              ^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/environ.py", line 939, in get_install_actions
-      precs = get_package_records(
-              ^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/environ.py", line 890, in get_install_actions
-      _actions = _install_actions(prefix, index, specs, subdir=subdir)
-                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/environ.py", line 1310, in install_actions
-      txn = solver.solve_for_transaction(prune=False, ignore_pinned=False)
-            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda/core/solve.py", line 156, in solve_for_transaction
-      unlink_precs, link_precs = self.solve_for_diff(
-                                 ^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda/core/solve.py", line 225, in solve_for_diff
-      final_precs = self.solve_final_state(
-                    ^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 179, in solve_final_state
-      out_state = self._solving_loop(in_state, out_state, index)
-                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda/common/io.py", line 87, in decorated
-      return f(*args, **kwds)
-             ^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 305, in _solving_loop
-      solved, outcome = self._solve_attempt(in_state, out_state, index, attempt=attempt)
-                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 362, in _solve_attempt
-      new_conflicts = self._maybe_raise_for_problems(outcome, index, out_state, old_conflicts)
-                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 759, in _maybe_raise_for_problems
-      self._maybe_raise_for_conda_build(
-    File "/opt/conda/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 849, in _maybe_raise_for_conda_build
-      raise exc
-  conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("jellyfish==2.2.10=h6bb024c_1")}
-  Encountered problems while solving:
-    - package jellyfish-2.2.10-h6bb024c_1 is excluded by strict repo priority
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/kmasker_1772588427692/work/conda_build.sh']' returned non-zero exit status 2.
 # Last 100 lines of the build log.
