[ci skip] add build failure record for recipe recipes/bioconductor-methylkit

diff --git a/recipes/bioconductor-methylkit/build_failure.linux-64.yaml b/recipes/bioconductor-methylkit/build_failure.linux-64.yaml
--- a/recipes/bioconductor-methylkit/build_failure.linux-64.yaml
+++ b/recipes/bioconductor-methylkit/build_failure.linux-64.yaml
@@ -1,11 +1,8 @@
-recipe_sha: adca17bc7f6da666dc80f84c990193d17e8f0657616b08b6f385fb7b58660cf3  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 77f59bcb91c649b5405b44b56aa8eb082a055f60d88ff6326650dac2303b0611  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-
-  source tree in: /opt/conda/conda-bld/bioconductor-methylkit_1735294184482/work
-  export PREFIX=/opt/conda/conda-bld/bioconductor-methylkit_1735294184482/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-methylkit_1735294184482/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/bioconductor-methylkit_1735294184482/work
+log: |-
+  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-methylkit_1735316059809/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/bioconductor-methylkit_1735316059809/work
   INFO: activate-binutils_linux-64.sh made the following environmental changes:
   ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-addr2line
   AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar
@@ -58,7 +55,7 @@ log: |2-
   GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
   During startup - Warning message:
   Setting LC_TIME failed, using "C"
-  * installing to library /opt/conda/conda-bld/bioconductor-methylkit_1735294184482/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/library
+  * installing to library /opt/conda/conda-bld/bioconductor-methylkit_1735316059809/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/library
   * installing *source* package methylKit ...
   ** package methylKit successfully unpacked and MD5 sums checked
   ** using staged installation
@@ -71,13 +68,16 @@ log: |2-
   During startup - Warning message:
   Setting LC_TIME failed, using "C"
   $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c -std=gnu11 -I"$PREFIX/lib/R/include" -DNDEBUG -D_FILE_OFFSET_BITS=64 -I'$PREFIX/lib/R/library/Rcpp/include' -I'$PREFIX/lib/R/library/Rhtslib/include' -I'$PREFIX/lib/R/library/zlibbioc/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -fvisibility-inlines-hidden  -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/r-base-split_1734433466103/work=/usr/local/src/conda/r-base-4.4.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix   -c methCall.cpp -o methCall.o
-  methCall.cpp:17:10: fatal error: zlib.h: No such file or directory
-     17 | #include "zlib.h"
-        |          ^~~~~~~~
-  compilation terminated.
-  make: *** [/opt/conda/conda-bld/bioconductor-methylkit_1735294184482/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/etc/Makeconf:204: methCall.o] Error 1
+  During startup - Warning message:
+  Setting LC_TIME failed, using "C"
+  During startup - Warning message:
+  Setting LC_TIME failed, using "C"
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c -std=gnu11 -shared -L$PREFIX/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -o methylKit.so RcppExports.o methCall.o $PREFIX/lib/R/library/Rhtslib/usrlib/libhts.a -lcurl -lbz2 -llzma -lz -L$PREFIX/lib/R/lib -lR
+  /opt/conda/conda-bld/bioconductor-methylkit_1735316059809/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -llzma: No such file or directory
+  collect2: error: ld returned 1 exit status
+  make: *** [/opt/conda/conda-bld/bioconductor-methylkit_1735316059809/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/share/make/shlib.mk:10: methylKit.so] Error 1
   ERROR: compilation failed for package methylKit
-  * removing /opt/conda/conda-bld/bioconductor-methylkit_1735294184482/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/library/methylKit
+  * removing /opt/conda/conda-bld/bioconductor-methylkit_1735316059809/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/R/library/methylKit
   Traceback (most recent call last):
     File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
       utils.check_call_env(
@@ -85,7 +85,7 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-methylkit_1735294184482/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-methylkit_1735316059809/work/conda_build.sh']' returned non-zero exit status 1.
 
   The above exception was the direct cause of the following exception:
 
@@ -100,5 +100,5 @@ log: |2-
       packages_from_this = build(
     File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-methylkit_1735294184482/work/conda_build.sh']' returned non-zero exit status 1.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-methylkit_1735316059809/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
