[ci skip] add build failure record for recipe recipes/bioconductor-rbwa

diff --git a/recipes/bioconductor-rbwa/build_failure.linux-64.yaml b/recipes/bioconductor-rbwa/build_failure.linux-64.yaml
--- a/recipes/bioconductor-rbwa/build_failure.linux-64.yaml
+++ b/recipes/bioconductor-rbwa/build_failure.linux-64.yaml
@@ -1,83 +1,83 @@
-recipe_sha: 78c1827018acdddcc8cb91d2e991b0106120d031c3c8f867df2a48d3ff01fb8f  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: dbc816f95c68f94afff89dad399dfa8e8f1a5b55d6ae403e695ff0fe99d65ef7  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-      - $R -e "library('Rbwa')"
-  about:
-    description: Provides an R wrapper for BWA alignment algorithms. Both BWA-backtrack
-      and BWA-MEM are available. Convenience function to build a BWA index from a reference
-      genome is also provided. Currently not supported for Windows machines.
-    home: https://bioconductor.org/packages/3.20/bioc/html/Rbwa.html
-    license: MIT  file LICENSE
-    license_file: LICENSE
-    summary: R wrapper for BWA-backtrack and BWA-MEM aligners
-  extra:
-    copy_test_source_files: true
-    final: true
-
-
-  source tree in: /opt/conda/conda-bld/bioconductor-rbwa_1734292955961/work
-  export PREFIX=/opt/conda/conda-bld/bioconductor-rbwa_1734292955961/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-rbwa_1734292955961/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/bioconductor-rbwa_1734292955961/work
-  INFO: activate-binutils_linux-64.sh made the following environmental changes:
-  ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-addr2line
-  AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar
-  AS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-as
-  CXXFILT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cfilt
-  DWP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-dwp
-  ELFEDIT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-elfedit
-  GPROF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gprof
-  LD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld
-  LD_GOLD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld.gold
-  NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-nm
-  OBJCOPY=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objcopy
-  OBJDUMP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objdump
-  RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib
-  READELF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-readelf
-  SIZE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-size
-  STRINGS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strings
-  STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip
-  INFO: activate-gcc_linux-64.sh made the following environmental changes:
-  BUILD=x86_64-conda-linux-gnu
-  CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
-  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
-  CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bioconductor-rbwa-1.10.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
-  CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr
-  CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot
-  CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
-  CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
-  CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
-  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
-  DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/bioconductor-rbwa-1.10.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
-  GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
-  GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
-  GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
-  GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
-  HOST=x86_64-conda-linux-gnu
-  LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
-  MESON_ARGS=-Dbuildtype=release --prefix=$PREFIX -Dlibdir=lib
-  _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
-  build_alias=x86_64-conda-linux-gnu
-  host_alias=x86_64-conda-linux-gnu
-  -BUILD=x86_64-conda_cos6-linux-gnu
-  -CONDA_BUILD_SYSROOT=
-  During startup - Warning message:
-  Setting LC_TIME failed, using "C"
-  * installing to library /opt/conda/conda-bld/bioconductor-rbwa_1734292955961/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library
-  * installing *source* package Rbwa ...
-  ** package Rbwa successfully unpacked and MD5 sums checked
-  ** using staged installation
-  ** libs
-  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c utils.c -o utils.o
-  utils.c:33:10: fatal error: zlib.h: No such file or directory
-     33 | #include <zlib.h>
-        |          ^~~~~~~~
-  compilation terminated.
-  make: *** [/opt/conda/conda-bld/bioconductor-rbwa_1734292955961/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/etc/Makeconf:197: utils.o] Error 1
+log: |-
+  rope.c: In function 'rope_restore_node':
+  rope.c:282:9: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
+    282 |         fread(&is_bottom, 1, 1, fp);
+        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
+  rope.c:283:9: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
+    283 |         fread(&n, 2, 1, fp);
+        |         ^~~~~~~~~~~~~~~~~~~
+  rope.c:291:25: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
+    291 |                         fread(p[i].c, 8, 6, fp);
+        |                         ^~~~~~~~~~~~~~~~~~~~~~~
+  rope.c:292:25: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
+    292 |                         fread(q, 2, 1, fp);
+        |                         ^~~~~~~~~~~~~~~~~~
+  rope.c:293:25: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
+    293 |                         fread(q  1, 1, *q, fp);
+        |                         ^~~~~~~~~~~~~~~~~~~~~~~
+  rope.c: In function 'rope_restore':
+  rope.c:312:9: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
+    312 |         fread(&r->max_nodes, 4, 1, fp);
+        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  rope.c:313:9: warning: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Wunused-result]
+    313 |         fread(&r->block_len, 4, 1, fp);
+        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c rle.c -o rle.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c is.c -o is.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtindex.c -o bwtindex.o
+  ar -csru libbwa.a utils.o kthread.o kstring.o ksw.o bwt.o bntseq.o bwa.o bwamem.o bwamem_pair.o bwamem_extra.o malloc_wrap.o QSufSort.o bwt_gen.o rope.o rle.o is.o bwtindex.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwashm.c -o bwashm.o
+  bwashm.c: In function 'bwa_shm_stage':
+  bwashm.c:29:9: warning: ignoring return value of 'ftruncate' declared with attribute 'warn_unused_result' [-Wunused-result]
+     29 |         ftruncate(shmid, BWA_CTL_SIZE);
+        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  bwashm.c:66:9: warning: ignoring return value of 'ftruncate' declared with attribute 'warn_unused_result' [-Wunused-result]
+     66 |         ftruncate(shmid, idx->l_mem);
+        |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwase.c -o bwase.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwaseqio.c -o bwaseqio.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtgap.c -o bwtgap.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtaln.c -o bwtaln.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bamlite.c -o bamlite.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwape.c -o bwape.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c kopen.c -o kopen.o
+  In file included from /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/string.h:638,
+                   from kopen.c:6:
+  In function 'strncpy',
+      inlined from 'cmd2argv' at kopen.c:248:2,
+      inlined from 'kopen' at kopen.c:306:13:
+  /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/bits/string3.h:120:10: warning: '__builtin_strncpy' specified bound between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
+    120 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
+        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  In function 'cmd2argv',
+      inlined from 'kopen' at kopen.c:306:13:
+  kopen.c:247:32: warning: argument 1 range [18446744071562067969, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
+    247 |         argv[0] = str = (char*)calloc(end - beg  1, 1);
+        |                                ^~~~~~~~~~~~~~~~~~~~~~~~
+  In file included from /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/bits/string2.h:1296,
+                   from /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/string.h:633:
+  /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h: In function 'kopen':
+  /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_build_env/x86_64-conda-linux-gnu/sysroot/usr/include/stdlib.h:467:14: note: in a call to allocation function 'calloc' declared here
+    467 | extern void *calloc (size_t __nmemb, size_t __size)
+        |              ^~~~~~
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c pemerge.c -o pemerge.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c maxk.c -o maxk.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtsw2_core.c -o bwtsw2_core.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtsw2_main.c -o bwtsw2_main.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtsw2_aux.c -o bwtsw2_aux.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwt_lite.c -o bwt_lite.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtsw2_chain.c -o bwtsw2_chain.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c fastmap.c -o fastmap.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c bwtsw2_pair.c -o bwtsw2_pair.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -I"$PREFIX/lib/R/include" -DNDEBUG   -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib    -fpic  -g -Wall -O2 -c main.c -o main.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -g -Wall -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS bwashm.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o bwape.o kopen.o pemerge.o maxk.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread -lrt
+  /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lz: No such file or directory
+  collect2: error: ld returned 1 exit status
+  make: *** [Makefile:45: bwa] Error 1
   ERROR: compilation failed for package Rbwa
-  * removing /opt/conda/conda-bld/bioconductor-rbwa_1734292955961/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/Rbwa
+  * removing /opt/conda/conda-bld/bioconductor-rbwa_1734315802393/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/Rbwa
   Traceback (most recent call last):
     File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2558, in build
       utils.check_call_env(
@@ -85,7 +85,7 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-rbwa_1734292955961/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-rbwa_1734315802393/work/conda_build.sh']' returned non-zero exit status 1.
 
   The above exception was the direct cause of the following exception:
 
@@ -100,5 +100,5 @@ log: |2-
       packages_from_this = build(
     File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-rbwa_1734292955961/work/conda_build.sh']' returned non-zero exit status 1.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-rbwa_1734315802393/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
