update patch

diff --git a/recipes/dsk/install_paths.patch b/recipes/dsk/install_paths.patch
--- a/recipes/dsk/install_paths.patch
+++ b/recipes/dsk/install_paths.patch
@@ -1,31 +1,41 @@
---- CMakeLists.txt.org	2017-04-17 17:00:03.000000000 -0500
-+++ CMakeLists.txt	2017-04-17 17:11:53.000000000 -0500
-@@ -118,9 +118,9 @@
+diff --git a/CMakeLists.txt b/CMakeLists.txt
+index 3d1e223..aaa02cc 100644
+--- a/CMakeLists.txt
++++ b/CMakeLists.txt
+@@ -118,9 +118,9 @@ SET (CPACK_SOURCE_IGNORE_FILES
  
  # We copy some files to the binary archive
  INSTALL (TARGETS ${PROJECT_NAME} DESTINATION bin)
 -INSTALL (DIRECTORY "${PROJECT_SOURCE_DIR}/test/" DESTINATION test)
--INSTALL (FILES scripts/simple_test.sh DESTINATION test)
--INSTALL (FILES LICENSE README.md scripts/simple_test.sh DESTINATION bin/..)
-+INSTALL (DIRECTORY "${PROJECT_SOURCE_DIR}/test/" DESTINATION $ENV{SHARE_DIR}/test)
-+INSTALL (FILES scripts/simple_test.sh DESTINATION $ENV{SHARE_DIR}/test)
-+INSTALL (FILES LICENSE README.md DESTINATION $ENV{SHARE_DIR})
+-INSTALL (FILES scripts/simple_test.sh DESTINATION test/)
+-INSTALL (FILES LICENSE README.md DESTINATION bin/..)
++INSTALL (DIRECTORY "${PROJECT_SOURCE_DIR}/test/" DESTINATION $ENV{share_dir}/test)
++INSTALL (FILES scripts/simple_test.sh DESTINATION $ENV{share_dir}/test)
++INSTALL (FILES LICENSE README.md DESTINATION $ENV{share_dir})
  
  # We include the "bin" tag into binary archive file name
  set (CPACK_PACKAGE_FILE_NAME  ${PROJECT_NAME}-${CPACK_PACKAGE_VERSION}-bin-${CMAKE_SYSTEM_NAME})
---- scripts/simple_test.sh	2016-03-25 05:24:51.000000000 -0500
-+++ scripts/simple_test.sh.new	2017-04-17 17:22:50.000000000 -0500
-@@ -3,10 +3,10 @@
+diff --git a/scripts/simple_test.sh b/scripts/simple_test.sh
+index 4ecf1d7..3926faf 100755
+--- a/scripts/simple_test.sh
++++ b/scripts/simple_test.sh
+@@ -3,18 +3,7 @@
  
  # look for dsk binary. In devel mode, it's in ../build/bin directory.
  # In production mode, it's in ../bin directory.
 -if [ -f "../bin/dsk" ]
-+if [ -f "/opt/anaconda1anaconda2anaconda3/bin/dsk" ]
- then
+-then
 - bindir="../bin"
 - h5bindir="../bin"
-+ bindir="/opt/anaconda1anaconda2anaconda3/bin"
-+ h5bindir="/opt/anaconda1anaconda2anaconda3/bin"
- elif [ -f "../build/bin/dsk" ]
- then
-  bindir="../build/bin"
+-elif [ -f "../build/bin/dsk" ]
+-then
+- bindir="../build/bin"
+- h5bindir="../build/ext/gatb-core/bin"
+-else
+- echo "could not find a compiled dsk binary"
+- exit 1
+-fi
++indir="/opt/anaconda1anaconda2anaconda3/bin"
+ 
+ # look for test data directory. In devel mode, it's in ../test directory.
+ # In production mode, it's in . directory (relative to this script).
