[ci skip] add build failure record for recipe recipes/tgsgapcloser

diff --git a/recipes/tgsgapcloser/build_failure.osx-64.yaml b/recipes/tgsgapcloser/build_failure.osx-64.yaml
--- a/recipes/tgsgapcloser/build_failure.osx-64.yaml
+++ b/recipes/tgsgapcloser/build_failure.osx-64.yaml
@@ -1,35 +1,35 @@
-recipe_sha: 8abc92b06b9b2895fd9c362e5a3793140a552540930b87011913f68cef1b3a5b  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: c777d5ab57b801fb6169fcedc71981d53a534a3812a453cf49ff028b0c60b10d  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |-
   about:
     home: https://github.com/BGI-Qingdao/TGS-GapCloser
     license: GPL-3.0-only
-    license_file: LICENSE
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 589, in execute
       api.build(
-    summary: A gap-closing software tool that uses error-prone long reads generated
-      by third-generation-sequence techniques (Pacbio, Oxford Nanopore, etc.) or preassembled
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 209, in build
+    license_file: LICENSE
+    summary: A gap-closing software tool that uses error-prone long reads generated
+      return build_tree(
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
+      packages_from_this = build(
+      by third-generation-sequence techniques (Pacbio, Oxford Nanopore, etc.) or preassembled
       contigs to fill N-gap in the genome assembly.
   extra:
-      return build_tree(
     copy_test_source_files: true
     final: true
     recipe-maintainers:
       - cchd0001
 
 
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734754540632/work
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3712, in build_tree
-      packages_from_this = build(
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734796763069/work
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734754540632/work/conda_build.sh']' returned non-zero exit status 2.
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734754540632/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734754540632/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734754540632/work
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734796763069/work/conda_build.sh']' returned non-zero exit status 2.
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734796763069/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734796763069/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/tgsgapcloser_1734796763069/work
   INFO: activate_clang_osx-64.sh made the following environmental changes:
   AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar
   AS=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-as
