[ci skip] add build failure record for recipe recipes/lambda/1.0.3

diff --git a/recipes/lambda/1.0.3/build_failure.osx-64.yaml b/recipes/lambda/1.0.3/build_failure.osx-64.yaml
--- a/recipes/lambda/1.0.3/build_failure.osx-64.yaml
+++ b/recipes/lambda/1.0.3/build_failure.osx-64.yaml
@@ -1,27 +1,38 @@
-recipe_sha: b1465c444db93c5d16427e7cb402f933f7421eb8c4c37cbfd06beef445682283  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 8570291ade4d9f0ce1bce2440a5ea3185979bdffc073c48ca1340082f39608c3  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      - clang_osx-64 19.1.7 h8a78ed7_31
-      - rhash 1.4.6 h6e16a3a_1
-      - libcurl 8.19.0 h8f0b9e4_0
-      - cctools 1030.6.3 llvm19_1_h67a6458_4
-      - libuv 1.51.0 h58003a5_1
-      - libzlib 1.3.1 hd23fc13_2
-      - ca-certificates 2026.2.25 hbd8a1cb_0
-      - ld64 956.6 llvm19_1_hc3792c1_4
-    host:
-      - bzip2 1.0.8 h500dc9f_9
-      - libcxx 22.1.1 h19cb2f5_0
-      - llvm-openmp 22.1.0 h0d3cbff_0
-      - seqan-library 2.4.0 h694c41f_0
-      - libzlib 1.3.1 hd23fc13_2
-      - zlib 1.3.1 hd23fc13_2
+      ~~~~~~~~~^
+          parsed.recipe,
+          ^^^^^^^^^^^^^^
+      ...<8 lines>...
+          cache_dir=parsed.cache_dir,
+          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+      )
+      ^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/api.py", line 211, in build
+      return build_tree(
+          recipes,
+      ...<7 lines>...
+          variants=variants,
+      )
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 3675, in build_tree
+      packages_from_this = build(
+          metadata,
+      ...<5 lines>...
+      - libzlib 1.3.2 hbb4bfdb_2
+          notest=notest,
+      )
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 2584, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/lambda_1776760363664/work/conda_build.sh']' returned non-zero exit status 1.
+      - zlib 1.3.2 hbb4bfdb_2
     run:
-      - libcxx >=19
-      - bzip2 >=1.0.8,<2.0a0
+      - __osx >=10.13
       - llvm-openmp >=19.1.7
-      - llvm-openmp >=22.1.0
-      - libzlib >=1.3.1,<2.0a0
+      - llvm-openmp >=22.1.3
+      - bzip2 >=1.0.8,<2.0a0
+      - libzlib >=1.3.2,<2.0a0
+      - libcxx >=19
   test:
     commands:
       - lambda --help
@@ -36,20 +47,10 @@ log: |2-
     copy_test_source_files: true
 
 
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
-      api.build(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
-      return build_tree(
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/lambda_1773691498156/work
-             ^^^^^^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3669, in build_tree
-      packages_from_this = build(
-                           ^^^^^^
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/lambda_1773691498156/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
-      raise BuildScriptException(str(exc), caused_by=exc) from exc
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/lambda_1773691498156/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/lambda_1773691498156/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/lambda_1776760363664/work
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/lambda_1776760363664/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/lambda_1776760363664/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/lambda_1776760363664/work
   INFO: activate_cctools_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
   AS=x86_64-apple-darwin13.4.0-as
@@ -69,7 +70,6 @@ log: |2-
   SEGEDIT=x86_64-apple-darwin13.4.0-segedit
   SIZE=x86_64-apple-darwin13.4.0-size
   STRINGS=x86_64-apple-darwin13.4.0-strings
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/lambda_1773691498156/work/conda_build.sh']' returned non-zero exit status 1.
   STRIP=x86_64-apple-darwin13.4.0-strip
   INFO: activate_clang_osx-64.sh made the following environmental changes:
   ac_cv_func_malloc_0_nonnull=yes
