[ci skip] add build failure record for recipe recipes/hapcut2

diff --git a/recipes/hapcut2/build_failure.linux-64.yaml b/recipes/hapcut2/build_failure.linux-64.yaml
--- a/recipes/hapcut2/build_failure.linux-64.yaml
+++ b/recipes/hapcut2/build_failure.linux-64.yaml
@@ -1,4 +1,4 @@
-recipe_sha: 71b7688ad1468d78986914a4c1d40b9fb9c4735da38f193f24dde064415877a1  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: aee4171284b9b429ebbbd19ed510c6eb3b8336906a8c42d5822d3a4826af681f  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
       - HAPCUT2 | grep HapCUT2
@@ -16,10 +16,10 @@ log: |2-
     final: true
 
 
-  source tree in: /opt/conda/conda-bld/hapcut2_1734561800074/work
-  export PREFIX=/opt/conda/conda-bld/hapcut2_1734561800074/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export BUILD_PREFIX=/opt/conda/conda-bld/hapcut2_1734561800074/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/hapcut2_1734561800074/work
+  source tree in: /opt/conda/conda-bld/hapcut2_1734578615565/work
+  export PREFIX=/opt/conda/conda-bld/hapcut2_1734578615565/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export BUILD_PREFIX=/opt/conda/conda-bld/hapcut2_1734578615565/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/hapcut2_1734578615565/work
   INFO: activate-binutils_linux-64.sh made the following environmental changes:
   ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-addr2line
   AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar
@@ -75,7 +75,7 @@ log: |2-
   $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -c -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/hapcut2-1.3.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fcommon  -Ihtslib  hairs-src/readfasta.c -o build/readfasta.o
   $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -c -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/hapcut2-1.3.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fcommon  hairs-src/hapfragments.c -o build/hapfragments.o
   $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/hapcut2-1.3.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fcommon  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -L$PREFIX/lib -lhts -Ihtslib  -g build/bamread.o build/hapfragments.o build/hashtable.o build/readfasta.o build/readvariant.o -o build/extractHAIRS hairs-src/extracthairs.c -pthread -lhts -lm -lz -lcurl -llzma -lbz2
-  /opt/conda/conda-bld/hapcut2_1734561800074/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -llzma: No such file or directory
+  /opt/conda/conda-bld/hapcut2_1734578615565/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -llzma: No such file or directory
   collect2: error: ld returned 1 exit status
   make: *** [Makefile:21: build/extractHAIRS] Error 1
   Traceback (most recent call last):
@@ -85,7 +85,7 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 380, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/hapcut2_1734561800074/work/conda_build.sh']' returned non-zero exit status 2.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/hapcut2_1734578615565/work/conda_build.sh']' returned non-zero exit status 2.
 
   The above exception was the direct cause of the following exception:
 
@@ -100,5 +100,5 @@ log: |2-
       packages_from_this = build(
     File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2566, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/hapcut2_1734561800074/work/conda_build.sh']' returned non-zero exit status 2.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/hapcut2_1734578615565/work/conda_build.sh']' returned non-zero exit status 2.
 # Last 100 lines of the build log.
