[ci skip] add build failure record for recipe recipes/phylommand

diff --git a/recipes/phylommand/build_failure.osx-64.yaml b/recipes/phylommand/build_failure.osx-64.yaml
--- a/recipes/phylommand/build_failure.osx-64.yaml
+++ b/recipes/phylommand/build_failure.osx-64.yaml
@@ -1,28 +1,14 @@
-recipe_sha: a5a5009dfb0df231486148d0a60573a001823a142a2804a004fa2b0b38265332  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 35f59c0fec1fcc62ee8b485876a4ae62fd0deeb124e8da9cf57399f266c467f6  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      - libcblas 3.11.0 5_h9b27e0a_openblas
-      - liblapack 3.11.0 5_h859234e_openblas
-      - numpy 2.4.2 py314hfc4c462_1
-      - nlopt 2.10.1 np2py314h72ea864_2
-    run:
-      - nlopt >=2.10.1,<2.11.0a0
-      - libcxx >=19
-  test:
-    commands:
-      - contree --help
-      packages_from_this = build(
-                           ^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
-      raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1773691307776/work/conda_build.sh']' returned non-zero exit status 2.
-      - pairalign --help
+      ^
       - treebender --help
   about:
     home: https://github.com/mr-y/phylommand
     license: GPLv3
     license_file: LICENSE
     summary: Command-line phylogenetics tools.
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/api.py", line 211, in build
     description: Command-line tools to create, manipulate, and/or analyze phylogenetic
       trees or pairwise alignments. Does not include "rudisvg" svg viewer.
   extra:
@@ -30,10 +16,24 @@ log: |2-
     copy_test_source_files: true
 
 
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/phylommand_1773691307776/work
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1773691307776/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1773691307776/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1773691307776/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/phylommand_1776758328000/work
+      return build_tree(
+          recipes,
+      ...<7 lines>...
+          variants=variants,
+      )
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 3675, in build_tree
+      packages_from_this = build(
+          metadata,
+      ...<5 lines>...
+          notest=notest,
+      )
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 2584, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1776758328000/work/conda_build.sh']' returned non-zero exit status 2.
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1776758328000/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1776758328000/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/phylommand_1776758328000/work
   INFO: activate_cctools_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
   AS=x86_64-apple-darwin13.4.0-as
