[ci skip] add build failure record for recipe recipes/varlociraptor

diff --git a/recipes/varlociraptor/build_failure.osx-arm64.yaml b/recipes/varlociraptor/build_failure.osx-arm64.yaml
--- a/recipes/varlociraptor/build_failure.osx-arm64.yaml
+++ b/recipes/varlociraptor/build_failure.osx-arm64.yaml
@@ -1,79 +1,79 @@
-recipe_sha: e4fe85ec5439daaeb65ecefd6858e34e4d355514301ffde2abf7751e0fadb73d  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: c2841fb98f81e620204883602c8e33728b1aa6a818076c85a2df08d95f278a88  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      - libclang-cpp 22.1.0 default_hf3020a7_0
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1773683856994/work/conda_build.sh']' returned non-zero exit status 101.
-      - llvm-tools 22.1.0 hd34ed20_0
-      - cctools_impl_osx-arm64 1030.6.3 llvm22_1_hb5e89dc_4
-      - clang-format 22.1.0 default_hf3020a7_0
-      - libcblas 3.9.0 13_hd5b1ab5_netlib
-      - llvmdev 22.1.0 hb545844_0
-      - cctools 1030.6.3 llvm22_1_hbe26303_4
-      - clang-tools 22.1.0 default_hf3020a7_0
-      - clang_impl_osx-arm64 22.1.0 default_h17d1ed9_0
-      - gsl 2.7 h6e638da_0
-      - clang 22.1.0 default_cfg_hb78b91e_0
-      - clangxx_impl_osx-arm64 22.1.0 default_h17d1ed9_0
-      - clangxx 22.1.0 default_cfg_h76039ee_0
-      - clangdev 22.1.0 default_hf3020a7_0
-    run:
-      - libcblas >=3.9.0,<4.0a0
-      - gsl >=2.7,<2.8.0a0
-      - libzlib >=1.3.1,<2.0a0
-      - libcxx >=19
-      - liblzma >=5.8.2,<6.0a0
-      - bzip2 >=1.0.8,<2.0a0
-    run_constrained:
-      - __osx >=11.0
-  test:
-    commands:
-      - varlociraptor -h
-  about:
-    home: https://github.com/varlociraptor/varlociraptor
-    license: GPL-3.0-or-later
-    license_family: GPL3
-    license_file: LICENSE
-    summary: Flexible, uncertainty-aware variant calling with parameter free filtration
-      via FDR control.
-    dev_url: https://github.com/varlociraptor/varlociraptor
-    doc_url: https://varlociraptor.github.io
-  extra:
-    additional-platforms:
-      - linux-aarch64
-      - osx-arm64
-    identifiers:
-      - biotools:varlociraptor
-      - doi:10.1186/s13059-020-01993-6
-    final: true
+          cmd,
+          ^^^^
     copy_test_source_files: true
 
 
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1773683856994/work
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1773683856994/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1773683856994/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1773683856994/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1776445447451/work
+      ...<3 lines>...
+          stats=build_stats,
+          ^^^^^^^^^^^^^^^^^^
+      )
+      ^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/utils.py", line 411, in check_call_env
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1776445447451/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1776445447451/_build_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1776445447451/work
   INFO: activate_cctools_osx-arm64.sh made the following environmental changes:
   AR=arm64-apple-darwin20.0.0-ar
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1776445447451/work/conda_build.sh']' returned non-zero exit status 101.
+
+  The above exception was the direct cause of the following exception:
+
+  Traceback (most recent call last):
+    File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 10, in <module>
+      sys.exit(execute())
+               ~~~~~~~^^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/cli/main_build.py", line 639, in execute
+      api.build(
+      ~~~~~~~~~^
+          parsed.recipe,
   AS=arm64-apple-darwin20.0.0-as
   CHECKSYMS=arm64-apple-darwin20.0.0-checksyms
   INSTALL_NAME_TOOL=arm64-apple-darwin20.0.0-install_name_tool
   LD=arm64-apple-darwin20.0.0-ld
   LIBTOOL=arm64-apple-darwin20.0.0-libtool
+          ^^^^^^^^^^^^^^
+      ...<8 lines>...
+          cache_dir=parsed.cache_dir,
   LIPO=arm64-apple-darwin20.0.0-lipo
   NM=arm64-apple-darwin20.0.0-nm
   NMEDIT=arm64-apple-darwin20.0.0-nmedit
   OTOOL=arm64-apple-darwin20.0.0-otool
   PAGESTUFF=arm64-apple-darwin20.0.0-pagestuff
   RANLIB=arm64-apple-darwin20.0.0-ranlib
+          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+      )
+      ^
   REDO_PREBINDING=arm64-apple-darwin20.0.0-redo_prebinding
   SEGEDIT=arm64-apple-darwin20.0.0-segedit
   SEG_ADDR_TABLE=arm64-apple-darwin20.0.0-seg_addr_table
   SEG_HACK=arm64-apple-darwin20.0.0-seg_hack
   SIZE=arm64-apple-darwin20.0.0-size
   STRINGS=arm64-apple-darwin20.0.0-strings
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/api.py", line 211, in build
+      return build_tree(
   STRIP=arm64-apple-darwin20.0.0-strip
   INFO: activate_clang_osx-arm64.sh made the following environmental changes:
   CC=arm64-apple-darwin20.0.0-clang
+          recipes,
+      ...<7 lines>...
+          variants=variants,
+      )
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 3675, in build_tree
+      packages_from_this = build(
+          metadata,
+      ...<5 lines>...
+          notest=notest,
+      )
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 2584, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/varlociraptor_1776445447451/work/conda_build.sh']' returned non-zero exit status 101.
   CC_FOR_BUILD=$BUILD_PREFIX/bin/arm64-apple-darwin20.0.0-clang
   CFLAGS=-ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/varlociraptor-8.9.5 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
   CLANG=arm64-apple-darwin20.0.0-clang
