[ci skip] add build failure record for recipe recipes/bioconductor-ramr

diff --git a/recipes/bioconductor-ramr/build_failure.linux-64.yaml b/recipes/bioconductor-ramr/build_failure.linux-64.yaml
--- a/recipes/bioconductor-ramr/build_failure.linux-64.yaml
+++ b/recipes/bioconductor-ramr/build_failure.linux-64.yaml
@@ -1,28 +1,6 @@
-recipe_sha: 33123fbb1727902010beb861466697416aeae7e160fd3cb6caae495d78e7004c  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: b3ae65844a02602dd018f0aee2a5abd391a7f669dcb9339c6f222ac80dcc72dc  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-      functions to visualize found aberrantly methylated regions (AMRs), to generate
-      sets of all possible regions to be used as reference sets for enrichment analysis,
-      and to generate biologically relevant test data sets for performance evaluation
-      of AMR/DMR search algorithms.
-  extra:
-    final: true
-    copy_test_source_files: true
-
-
-  source tree in: /opt/conda/conda-bld/bioconductor-ramr_1772558718177/work
-  export PREFIX=/opt/conda/conda-bld/bioconductor-ramr_1772558718177/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-ramr_1772558718177/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/bioconductor-ramr_1772558718177/work
-  INFO: activate-binutils_linux-64.sh made the following environmental changes:
-  ADDR2LINE=x86_64-conda-linux-gnu-addr2line
-  AR=x86_64-conda-linux-gnu-ar
-  AS=x86_64-conda-linux-gnu-as
-  CXXFILT=x86_64-conda-linux-gnu-cfilt
-  ELFEDIT=x86_64-conda-linux-gnu-elfedit
-  GPROF=x86_64-conda-linux-gnu-gprof
-  LD=x86_64-conda-linux-gnu-ld
-  NM=x86_64-conda-linux-gnu-nm
+log: |-
   OBJCOPY=x86_64-conda-linux-gnu-objcopy
   OBJDUMP=x86_64-conda-linux-gnu-objdump
   RANLIB=x86_64-conda-linux-gnu-ranlib
@@ -66,14 +44,36 @@ log: |2-
   GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
   During startup - Warning message:
   Setting LC_TIME failed, using "C"
-  * installing to library /opt/conda/conda-bld/bioconductor-ramr_1772558718177/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library
+  * installing to library /opt/conda/conda-bld/bioconductor-ramr_1772587671778/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library
   * installing *source* package ramr ...
   ** this is package ramr version 1.18.0
   ** package ramr successfully unpacked and MD5 sums checked
   ** using staged installation
   ** libs
-  Error: C20 standard requested but CXX20 is not defined
-  * removing /opt/conda/conda-bld/bioconductor-ramr_1772558718177/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/ramr
+  using C compiler: x86_64-conda-linux-gnu-c (conda-forge gcc 14.3.0-18) 14.3.0
+  using C20
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c RcppExports.cpp -o RcppExports.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_compute_logp.cpp -o rcpp_compute_logp.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_compute_xiqr.cpp -o rcpp_compute_xiqr.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_create_granges.cpp -o rcpp_create_granges.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_filter_threshold.cpp -o rcpp_filter_threshold.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_fit_beta.cpp -o rcpp_fit_beta.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_fit_betabinom.cpp -o rcpp_fit_betabinom.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_fit_binom.cpp -o rcpp_fit_binom.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_generate_random_values.cpp -o rcpp_generate_random_values.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_get_iqr.cpp -o rcpp_get_iqr.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_get_meanvar.cpp -o rcpp_get_meanvar.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_helper_functions.cpp -o rcpp_helper_functions.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_prepare_data.cpp -o rcpp_prepare_data.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c  -I"$PREFIX/lib/R/include" -DNDEBUG  -I'$PREFIX/lib/R/library/Rcpp/include' -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -I$PREFIX/include -Wl,-rpath-link,$PREFIX/lib   -fopenmp     -c rcpp_test_omp.cpp -o rcpp_test_omp.o
+  $BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c -shared -L$PREFIX/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib -o ramr.so RcppExports.o rcpp_compute_logp.o rcpp_compute_xiqr.o rcpp_create_granges.o rcpp_filter_threshold.o rcpp_fit_beta.o rcpp_fit_betabinom.o rcpp_fit_binom.o rcpp_generate_random_values.o rcpp_get_iqr.o rcpp_get_meanvar.o rcpp_helper_functions.o rcpp_prepare_data.o rcpp_test_omp.o -fopenmp -L$PREFIX/lib/R/lib -lR
+  /opt/conda/conda-bld/bioconductor-ramr_1772587671778/_build_env/bin/../libexec/gcc/x86_64-conda-linux-gnu/14.3.0/ld: rcpp_test_omp.o: warning: relocation against _ZTVSt9basic_iosIcSt11char_traitsIcEE@@GLIBCXX_3.4' in read-only section .text.unlikely'
+  /opt/conda/conda-bld/bioconductor-ramr_1772587671778/_build_env/bin/../libexec/gcc/x86_64-conda-linux-gnu/14.3.0/ld: RcppExports.o: relocation R_X86_64_PC32 against symbol R_NilValue' can not be used when making a shared object; recompile with -fPIC
+  /opt/conda/conda-bld/bioconductor-ramr_1772587671778/_build_env/bin/../libexec/gcc/x86_64-conda-linux-gnu/14.3.0/ld: final link failed: bad value
+  collect2: error: ld returned 1 exit status
+  make: *** [/opt/conda/conda-bld/bioconductor-ramr_1772587671778/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/share/make/shlib.mk:10: ramr.so] Error 1
+  ERROR: compilation failed for package ramr
+  * removing /opt/conda/conda-bld/bioconductor-ramr_1772587671778/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/ramr
   Traceback (most recent call last):
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2570, in build
       utils.check_call_env(
@@ -82,7 +82,7 @@ log: |2-
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-ramr_1772558718177/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-ramr_1772587671778/work/conda_build.sh']' returned non-zero exit status 1.
 
   The above exception was the direct cause of the following exception:
 
@@ -100,5 +100,5 @@ log: |2-
                            ^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-ramr_1772558718177/work/conda_build.sh']' returned non-zero exit status 1.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-ramr_1772587671778/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
