[ci skip] add build failure record for recipe recipes/modle

diff --git a/recipes/modle/build_failure.linux-64.yaml b/recipes/modle/build_failure.linux-64.yaml
--- a/recipes/modle/build_failure.linux-64.yaml
+++ b/recipes/modle/build_failure.linux-64.yaml
@@ -1,88 +1,88 @@
-recipe_sha: bd3f27b19e4134d09f67ae1db018cfe2cbb8cde1782971efdd758a89acc3f21f  # The commit at which this recipe failed to build.
+recipe_sha: 251bacb41264d22c9c003d1390440d9f4ca356b10623ac2fbc0802978e083d6d  # The commit at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-      requests:                 2.31.0-pyhd8ed1ab_0       conda-forge
-      rhash:                    1.4.3-h166bdaf_0          conda-forge
-      setuptools:               67.7.2-pyhd8ed1ab_0       conda-forge
-      six:                      1.16.0-pyh6c4a22f_0       conda-forge
-      sysroot_linux-64:         2.12-he073ed8_15          conda-forge
-      tk:                       8.6.12-h27826a3_0         conda-forge
-      tzdata:                   2023c-h71feb2d_0          conda-forge
-      urllib3:                  1.26.15-pyhd8ed1ab_0      conda-forge
-      wheel:                    0.40.0-pyhd8ed1ab_0       conda-forge
-      xz:                       5.2.6-h166bdaf_0          conda-forge
-      yaml:                     0.2.5-h7f98852_2          conda-forge
-      zlib:                     1.2.13-h166bdaf_4         conda-forge
-      zstd:                     1.5.2-h3eb15da_6          conda-forge
-
-  Preparing transaction: ...working... done
-  Verifying transaction: ...working... done
-  Executing transaction: ...working... done
-  Source cache directory is: /opt/conda/conda-bld/src_cache
-  INFO:conda_build.source:Source cache directory is: /opt/conda/conda-bld/src_cache
-  Downloading source to cache: v1.0.0_dd9ea8c08f.tar.gz
-  INFO:conda_build.source:Downloading source to cache: v1.0.0_dd9ea8c08f.tar.gz
-  Downloading https://github.com/paulsengroup/MoDLE/archive/refs/tags/v1.0.0.tar.gz
-  INFO:conda_build.source:Downloading https://github.com/paulsengroup/MoDLE/archive/refs/tags/v1.0.0.tar.gz
-  Success
-  INFO:conda_build.source:Success
-  Extracting download
-  source tree in: /opt/conda/conda-bld/modle_1685351134350/work
-  export PREFIX=/opt/conda/conda-bld/modle_1685351134350/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
-  export BUILD_PREFIX=/opt/conda/conda-bld/modle_1685351134350/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/modle_1685351134350/work
-  INFO: activate-binutils_linux-64.sh made the following environmental changes:
-  ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-addr2line
-  AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar
-  AS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-as
-  CXXFILT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cfilt
-  ELFEDIT=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-elfedit
-  GPROF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gprof
-  LD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld
-  LD_GOLD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld.gold
-  NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-nm
-  OBJCOPY=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objcopy
-  OBJDUMP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-objdump
-  RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib
-  READELF=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-readelf
-  SIZE=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-size
-  STRINGS=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strings
-  STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip
-  INFO: activate-gcc_linux-64.sh made the following environmental changes:
-  BUILD=x86_64-conda-linux-gnu
-  CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
-  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc
-  CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/modle-1.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-strip -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH=$PREFIX;$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
-  CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot/usr
-  CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda-linux-gnu/sysroot
-  CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
-  CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
-  CPP=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cpp
-  CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
-  DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/modle-1.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
-  GCC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc
-  GCC_AR=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ar
-  GCC_NM=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-nm
-  GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gcc-ranlib
-  HOST=x86_64-conda-linux-gnu
-  LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
-  MESON_ARGS=--buildtype release --prefix=$PREFIX -Dlibdir=lib
-  _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
-  build_alias=x86_64-conda-linux-gnu
-  host_alias=x86_64-conda-linux-gnu
-  -BUILD=x86_64-conda_cos6-linux-gnu
-  -CONDA_BUILD_SYSROOT=
-  INFO: activate-gxx_linux-64.sh made the following environmental changes:
-  CXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
-  CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/modle-1.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  CXX_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-c
-  DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/modle-1.0.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
-  GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
-  [31mERROR: The default build profile '/home/conda/.conan2/profiles/default' doesn't exist.
-  You need to create a default profile (type 'conan profile detect' command)
-  or specify your own profile with '--profile:build=<myprofile>'[0m
+log: |-
+  bshoshany-thread-pool/3.3.0:[0m Checking remote: conancenter[0m
+  bshoshany-thread-pool/3.3.0:[0m Downloaded recipe revision 22e99aee6babc19e679754d95dad2de4[0m
+  catch2/3.3.2:[0m Not found in local cache, looking in remotes...[0m
+  catch2/3.3.2:[0m Checking remote: conancenter[0m
+  catch2/3.3.2:[0m Downloaded recipe revision be6a2f0225146ba4fd8573ee9013e5ae[0m
+  cli11/2.3.2:[0m Not found in local cache, looking in remotes...[0m
+  cli11/2.3.2:[0m Checking remote: conancenter[0m
+  cli11/2.3.2:[0m Downloaded recipe revision 8ccdf14fb1ad53532d498c16ae580b4b[0m
+  concurrentqueue/1.0.3:[0m Not found in local cache, looking in remotes...[0m
+  concurrentqueue/1.0.3:[0m Checking remote: conancenter[0m
+  concurrentqueue/1.0.3:[0m Downloaded recipe revision c1cb7d960d8b64073643b45fa63f0bd1[0m
+  cpp-sort/1.14.0:[0m Not found in local cache, looking in remotes...[0m
+  cpp-sort/1.14.0:[0m Checking remote: conancenter[0m
+  cpp-sort/1.14.0:[0m Downloaded recipe revision 3453aaaf83c1dae4214ca3b5c4c3a5c8[0m
+  fast_float/4.0.0:[0m Not found in local cache, looking in remotes...[0m
+  fast_float/4.0.0:[0m Checking remote: conancenter[0m
+  fast_float/4.0.0:[0m Downloaded recipe revision 90cac63d3ae321f6318b9abf8af9cbb1[0m
+  fmt/9.1.0:[0m Not found in local cache, looking in remotes...[0m
+  fmt/9.1.0:[0m Checking remote: conancenter[0m
+  fmt/9.1.0:[0m Downloaded recipe revision e747928f85b03f48aaf227ff897d9634[0m
+  hdf5/1.14.0:[0m Not found in local cache, looking in remotes...[0m
+  hdf5/1.14.0:[0m Checking remote: conancenter[0m
+  hdf5/1.14.0:[0m Downloaded recipe revision 011206975dc4c5ca80dd612d3a34cab3[0m
+  cmake/3.26.4:[0m Not found in local cache, looking in remotes...[0m
+  cmake/3.26.4:[0m Checking remote: conancenter[0m
+  cmake/3.26.4:[0m Downloaded recipe revision 0b40747e190e755932767f2ec4768ff5[0m
+  highfive/2.7.1:[0m Not found in local cache, looking in remotes...[0m
+  highfive/2.7.1:[0m Checking remote: conancenter[0m
+  highfive/2.7.1:[0m Downloaded recipe revision a73bc6937c9add30c9d47a7a70a466eb[0m
+  libarchive/3.6.2:[0m Not found in local cache, looking in remotes...[0m
+  libarchive/3.6.2:[0m Checking remote: conancenter[0m
+  libarchive/3.6.2:[0m Downloaded recipe revision b768ab8c0dcfb9e27b912a7f32fd02c1[0m
+  libiconv/1.17:[0m Not found in local cache, looking in remotes...[0m
+  libiconv/1.17:[0m Checking remote: conancenter[0m
+  libiconv/1.17:[0m Downloaded recipe revision fa54397801cd96911a8294bc5fc76335[0m
+  lz4/1.9.4:[0m Not found in local cache, looking in remotes...[0m
+  lz4/1.9.4:[0m Checking remote: conancenter[0m
+  lz4/1.9.4:[0m Downloaded recipe revision bce1f314775b83c195dffc8e177ff368[0m
+  lzo/2.10:[0m Not found in local cache, looking in remotes...[0m
+  lzo/2.10:[0m Checking remote: conancenter[0m
+  lzo/2.10:[0m Downloaded recipe revision 5725914235423c771cb1c6b607109b45[0m
+  libbigwig/0.4.7:[0m Not found in local cache, looking in remotes...[0m
+  libbigwig/0.4.7:[0m Checking remote: conancenter[0m
+  libbigwig/0.4.7:[0m Downloaded recipe revision 97113380bd925b2220b1d1e63c454d91[0m
+  zlib-ng/2.0.7:[0m Not found in local cache, looking in remotes...[0m
+  zlib-ng/2.0.7:[0m Checking remote: conancenter[0m
+  zlib-ng/2.0.7:[0m Downloaded recipe revision fbf3d453595da4be4245283c4ca065b8[0m
+  libcuckoo/0.3.1:[0m Not found in local cache, looking in remotes...[0m
+  libcuckoo/0.3.1:[0m Checking remote: conancenter[0m
+  libcuckoo/0.3.1:[0m Downloaded recipe revision 7e514d4c23a9aba3d8d80758824e9dc0[0m
+  [1m[33mGraph root[0m
+  [1m[36m    conanfile.txt: /opt/conda/conda-bld/modle_1686044039950/work/conanfile.txt[0m
+  [1m[33mRequirements[0m
+  [1m[36m    abseil/20230125.3#5431a4c609f5fb48bb8d8567e953243f - Downloaded (conancenter)[0m
+  [1m[36m    bitflags/1.5.0#626da9d1913161321841f30caf9b994e - Downloaded (conancenter)[0m
+  [1m[36m    boost/1.81.0#9bd7ae86a881631b6cc76590621e470b - Downloaded (conancenter)[0m
+  [1m[36m    bshoshany-thread-pool/3.3.0#22e99aee6babc19e679754d95dad2de4 - Downloaded (conancenter)[0m
+  [1m[36m    bzip2/1.0.8#411fc05e80d47a89045edc1ee6f23c1d - Downloaded (conancenter)[0m
+  [1m[36m    catch2/3.3.2#be6a2f0225146ba4fd8573ee9013e5ae - Downloaded (conancenter)[0m
+  [1m[36m    cli11/2.3.2#8ccdf14fb1ad53532d498c16ae580b4b - Downloaded (conancenter)[0m
+  [1m[36m    concurrentqueue/1.0.3#c1cb7d960d8b64073643b45fa63f0bd1 - Downloaded (conancenter)[0m
+  [1m[36m    cpp-sort/1.14.0#3453aaaf83c1dae4214ca3b5c4c3a5c8 - Downloaded (conancenter)[0m
+  [1m[36m    fast_float/4.0.0#90cac63d3ae321f6318b9abf8af9cbb1 - Downloaded (conancenter)[0m
+  [1m[36m    fmt/9.1.0#e747928f85b03f48aaf227ff897d9634 - Downloaded (conancenter)[0m
+  [1m[36m    hdf5/1.14.0#011206975dc4c5ca80dd612d3a34cab3 - Downloaded (conancenter)[0m
+  [1m[36m    highfive/2.7.1#a73bc6937c9add30c9d47a7a70a466eb - Downloaded (conancenter)[0m
+  [1m[36m    libarchive/3.6.2#b768ab8c0dcfb9e27b912a7f32fd02c1 - Downloaded (conancenter)[0m
+  [1m[36m    libbigwig/0.4.7#97113380bd925b2220b1d1e63c454d91 - Downloaded (conancenter)[0m
+  [1m[36m    libcuckoo/0.3.1#7e514d4c23a9aba3d8d80758824e9dc0 - Downloaded (conancenter)[0m
+  [1m[36m    libiconv/1.17#fa54397801cd96911a8294bc5fc76335 - Downloaded (conancenter)[0m
+  [1m[36m    lz4/1.9.4#bce1f314775b83c195dffc8e177ff368 - Downloaded (conancenter)[0m
+  [1m[36m    lzo/2.10#5725914235423c771cb1c6b607109b45 - Downloaded (conancenter)[0m
+  [1m[36m    xz_utils/5.4.2#b6ee8320403def553418874435445982 - Downloaded (conancenter)[0m
+  [1m[36m    zlib/1.2.13#e377bee636333ae348d51ca90874e353 - Downloaded (conancenter)[0m
+  [1m[36m    zlib-ng/2.0.7#fbf3d453595da4be4245283c4ca065b8 - Downloaded (conancenter)[0m
+  [1m[36m    zstd/1.5.5#93372fe14bb7883bd4de82914e0a1841 - Downloaded (conancenter)[0m
+  [1m[33mBuild requirements[0m
+  [1m[36m    b2/4.9.6#2e02945ad41739b8051247d14fe8297d - Downloaded (conancenter)[0m
+  [1m[36m    cmake/3.26.4#0b40747e190e755932767f2ec4768ff5 - Downloaded (conancenter)[0m
+  [1m[33mResolved version ranges[0m
+  [1m[36m    cmake/[>=3.18 <4]: cmake/3.26.4[0m
+  [31mERROR: Version conflict: None->lzo/2.10, None->lzo/2.10.[0m
   Traceback (most recent call last):
     File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
       sys.exit(main())
@@ -100,5 +100,5 @@ log: |2-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/modle_1685351134350/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/modle_1686044039950/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
