- Add licenses for FragPipe and components - Disallow DIA-NN as its license is not included - Do not pin JDK, IonQuant, or MSFragger versions - Update ionquant key

diff --git a/recipes/fragpipe/fragpipe b/recipes/fragpipe/fragpipe
--- a/recipes/fragpipe/fragpipe
+++ b/recipes/fragpipe/fragpipe
@@ -21,12 +21,27 @@ while [[ $# -gt 0 ]]; do
             shift
             ionquant_key=$1
             ;;
+        --workflow)
+            fragpipe_args+=("$1")
+            shift
+            workflow_file="$1"
+            fragpipe_args+=("$1")
+            ;;
         *)
             fragpipe_args+=("$1")
             ;;
     esac
     shift
 done
+
+if [[ ! -z "$workflow_file" ]]; then
+    # Because the DIA-NN license is incompatible with bioconda, we remove the feature.
+    grep 'diann.run-dia-nn=true' "$workflow_file" >/dev/null
+    if [[ $? -eq 0 ]]; then
+        echo "Error: DIA-NN is disabled in the FragPipe bioconda package."
+        exit 1
+    fi
+fi
 
 if [[ -z $msfragger_key || -z $ionquant_key ]]; then
     echo "$license_agreement_text"
