[ci skip] add build failure record for recipe recipes/clonalframeml/1.11

diff --git a/recipes/clonalframeml/1.11/build_failure.osx-64.yaml b/recipes/clonalframeml/1.11/build_failure.osx-64.yaml
--- a/recipes/clonalframeml/1.11/build_failure.osx-64.yaml
+++ b/recipes/clonalframeml/1.11/build_failure.osx-64.yaml
@@ -1,68 +1,68 @@
-recipe_sha: 04c71d3fd4df82a2993e0396e1d43d66de1eab9d58f676e02734dcb50dede7a1  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 09bbc257336386149366e22cce30e388bae8cc5288debdb07392f6758af17f35  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      - sdkroot_env_osx-64 26.0 h62b880e_7
-      - sigtool-codesign 0.1.3 hc0f2934_0
-      - libcxx-devel 19.1.7 h7c275be_2
-      - llvm-tools-19 19.1.7 h879f4bc_2
-      - ncurses 6.5 h0622a9a_3
-      - openssl 3.6.1 hb6871ef_1
-      - cctools_impl_osx-64 1030.6.3 llvm19_1_h7d82c7c_4
-      - libcxx 22.1.1 h19cb2f5_0
-      - llvm-tools 19.1.7 hb0207f0_2
-      - ld64_osx-64 956.6 llvm19_1_hcae3351_4
-    host:
-      - libcxx 22.1.1 h19cb2f5_0
-    run:
-      - libcxx >=19
-  test:
-    commands:
-      - ClonalFrameML 2>&1 | grep "ClonalFrameML"
-  about:
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/utils.py", line 411, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     home: https://github.com/xavierdidelot/ClonalFrameML
     license: GPLv3
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1773691616151/work/conda_build.sh']' returned non-zero exit status 2.
-
-  The above exception was the direct cause of the following exception:
-
     summary: Efficient inferencing of recombination in bacterial genomes
   extra:
     final: true
     copy_test_source_files: true
 
 
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1773691616151/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1776757444719/work
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1776757444719/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1776757444719/work/conda_build.sh']' returned non-zero exit status 2.
+
+  The above exception was the direct cause of the following exception:
+
   Traceback (most recent call last):
-    File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
+    File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 10, in <module>
       sys.exit(execute())
-               ^^^^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/cli/main_build.py", line 622, in execute
+               ~~~~~~~^^
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/cli/main_build.py", line 639, in execute
       api.build(
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1773691616151/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
+      ~~~~~~~~~^
+          parsed.recipe,
+          ^^^^^^^^^^^^^^
+      ...<8 lines>...
+          cache_dir=parsed.cache_dir,
+          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
+      )
+      ^
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1776757444719/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1776757444719/work
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/api.py", line 211, in build
       return build_tree(
-             ^^^^^^^^^^^
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1773691616151/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1773691616151/work
+          recipes,
+      ...<7 lines>...
+          variants=variants,
+      )
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 3675, in build_tree
+      packages_from_this = build(
+          metadata,
+      ...<5 lines>...
+          notest=notest,
+      )
   INFO: activate_cctools_osx-64.sh made the following environmental changes:
   AR=x86_64-apple-darwin13.4.0-ar
+    File "/opt/mambaforge/envs/bioconda/lib/python3.13/site-packages/conda_build/build.py", line 2584, in build
+      raise BuildScriptException(str(exc), caused_by=exc) from exc
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1776757444719/work/conda_build.sh']' returned non-zero exit status 2.
   AS=x86_64-apple-darwin13.4.0-as
   CHECKSYMS=x86_64-apple-darwin13.4.0-checksyms
   INSTALL_NAME_TOOL=x86_64-apple-darwin13.4.0-install_name_tool
   LD=x86_64-apple-darwin13.4.0-ld
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 3669, in build_tree
-      packages_from_this = build(
   LIBTOOL=x86_64-apple-darwin13.4.0-libtool
   LIPO=x86_64-apple-darwin13.4.0-lipo
   NM=x86_64-apple-darwin13.4.0-nm
   NMEDIT=x86_64-apple-darwin13.4.0-nmedit
-                           ^^^^^^
-    File "/opt/mambaforge/envs/bioconda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
-      raise BuildScriptException(str(exc), caused_by=exc) from exc
   OTOOL=x86_64-apple-darwin13.4.0-otool
   PAGESTUFF=x86_64-apple-darwin13.4.0-pagestuff
   RANLIB=x86_64-apple-darwin13.4.0-ranlib
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/clonalframeml_1773691616151/work/conda_build.sh']' returned non-zero exit status 2.
   REDO_PREBINDING=x86_64-apple-darwin13.4.0-redo_prebinding
   SEG_ADDR_TABLE=x86_64-apple-darwin13.4.0-seg_addr_table
   SEG_HACK=x86_64-apple-darwin13.4.0-seg_hack
@@ -100,5 +100,5 @@ log: |2-
   CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clonalframeml-1.11 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
   DEBUG_CXXFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc -fvisibility-inlines-hidden -fmessage-length=0 -Og -g -Wall -Wextra -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clonalframeml-1.11 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
   /bin/echo "#define ClonalFrameML_GITRevision \"git describe --tags\"" > version.h
-  x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clonalframeml-1.11 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=11.3 -O3 -I./ -I./myutils -I./coalesce -c -o main.o main.cpp
+  x86_64-apple-darwin13.4.0-clang -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/clonalframeml-1.11 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=11.3 -mmacosx-version-min=10.13 -O3 -I./ -I./myutils -I./coalesce -c -o main.o main.cpp
 # Last 100 lines of the build log.
