[ci skip] add build failure record for recipe recipes/bioconductor-systempiperdata

diff --git a/recipes/bioconductor-systempiperdata/build_failure.linux-64.yaml b/recipes/bioconductor-systempiperdata/build_failure.linux-64.yaml
--- a/recipes/bioconductor-systempiperdata/build_failure.linux-64.yaml
+++ b/recipes/bioconductor-systempiperdata/build_failure.linux-64.yaml
@@ -1,82 +1,80 @@
-recipe_sha: 798f8ea50df7150e89b1404d99c9fa08e9dfca017876ca34e61120320b0e8b47  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 318428af49bc000f4263a8e94d95cc3553a46507d08116985ab1db1b8aa5d957  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
-      libiconv:                  1.18-h3b78370_2               conda-forge
-      libjpeg-turbo:             3.1.2-hb03c661_0              conda-forge
-      liblapack:                 3.11.0-5_h47877c9_openblas    conda-forge
-      liblzma:                   5.8.2-hb03c661_0              conda-forge
-      libnghttp2:                1.67.0-had1ee68_0             conda-forge
-      libopenblas:               0.3.30-pthreads_h94d23a6_4    conda-forge
-      libpng:                    1.6.55-h421ea60_0             conda-forge
-      libsanitizer:              15.2.0-h90f66d4_18            conda-forge
-      libssh2:                   1.11.1-hcf80075_0             conda-forge
-      libstdcxx:                 15.2.0-h934c35e_18            conda-forge
-      libstdcxx-devel_linux-64:  15.2.0-hd446a21_118           conda-forge
-      libstdcxx-ng:              15.2.0-hdf11a46_18            conda-forge
-      libtiff:                   4.7.1-h9d88235_1              conda-forge
-      libuuid:                   2.41.3-h5347b49_0             conda-forge
-      libwebp-base:              1.6.0-hd42ef1d_0              conda-forge
-      libxcb:                    1.17.0-h8a09558_0             conda-forge
-      libzlib:                   1.3.1-hb9d3cd8_2              conda-forge
-      make:                      4.4.1-hb9d3cd8_2              conda-forge
-      ncurses:                   6.5-h2d0b736_3                conda-forge
-      openssl:                   3.6.1-h35e630c_1              conda-forge
-      pango:                     1.56.4-hadf4263_0             conda-forge
-      pcre2:                     10.47-haa7fec5_0              conda-forge
-      pixman:                    0.46.4-h54a6638_1             conda-forge
-      pthread-stubs:             0.4-hb9d3cd8_1002             conda-forge
-      r-base:                    4.5.2-h1fbe982_4              conda-forge
-      r-crayon:                  1.5.3-r45hc72bb7e_2           conda-forge
-      r-generics:                0.1.4-r45hc72bb7e_1           conda-forge
-      r-jsonlite:                2.0.0-r45h54b55ab_1           conda-forge
-      r-remotes:                 2.5.0-r45hc72bb7e_2           conda-forge
-      readline:                  8.3-h853b02a_0                conda-forge
-      sed:                       4.9-h6688a6e_0                conda-forge
-      sysroot_linux-64:          2.17-h0157908_18              conda-forge
-      tk:                        8.6.13-noxft_h366c992_103     conda-forge
-      tktable:                   2.10-h8d826fa_7               conda-forge
-      tzdata:                    2025c-hc9c84f9_1              conda-forge
-      xorg-libice:               1.1.2-hb9d3cd8_0              conda-forge
-      xorg-libsm:                1.2.6-he73a12e_0              conda-forge
-      xorg-libx11:               1.8.13-he1eb515_0             conda-forge
-      xorg-libxau:               1.0.12-hb03c661_1             conda-forge
-      xorg-libxdmcp:             1.1.5-hb03c661_1              conda-forge
-      xorg-libxext:              1.3.7-hb03c661_0              conda-forge
-      xorg-libxrender:           0.9.12-hb9d3cd8_0             conda-forge
-      xorg-libxt:                1.3.1-hb9d3cd8_0              conda-forge
-      zstd:                      1.5.7-hb78ec9c_6              conda-forge
+   for URL in '${URLS[@]}'
+   echo '"https://bioconductor.org/packages/3.22/data/experiment/src/contrib/systemPipeRdata_2.14.4.tar.gz"'
+   tr -d '"'
+   URL=https://bioconductor.org/packages/3.22/data/experiment/src/contrib/systemPipeRdata_2.14.4.tar.gz
+   echo '"9d556124a89abebfa6375fc4d5a38d9b"'
+   tr -d '"'
+   MD5=9d556124a89abebfa6375fc4d5a38d9b
+   curl -L https://bioconductor.org/packages/3.22/data/experiment/src/contrib/systemPipeRdata_2.14.4.tar.gz
+    % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
+                                   Dload  Upload  Total   Spent   Left   Speed
 
-  Preparing transaction: ...working... done
-  Verifying transaction: ...working... done
-  Executing transaction: ...working... done
-  Reloading output folder: ...working... done
-  Solving environment (_test_env): ...working... done
-  Source cache directory is: /opt/conda/conda-bld/src_cache
-  Downloading source to cache: systemPipeRdata_2.14.4_9d556124a8.tar.gz
-  Downloading https://bioconductor.org/packages/3.22/data/experiment/src/contrib/systemPipeRdata_2.14.4.tar.gz
-  WARNING: Error: HTTP 404 NOT FOUND for url <https://bioconductor.org/packages/3.22/data/experiment/src/contrib/systemPipeRdata_2.14.4.tar.gz>
-  Elapsed: 00:00.205061
+    0      0   0      0   0      0      0      0                              0
+  100  11526 100  11526   0      0 113.2k      0                              0
+  100  11526 100  11526   0      0 113.1k      0                              0
+  100  11526 100  11526   0      0 113.0k      0                              0
+   [[ 0 == 0 ]]
+   uname -s
+   [[ Linux == \L\i\n\u\x ]]
+   md5sum -c
+  md5sum: WARNING: 1 computed checksum did NOT match
+   for URL in '${URLS[@]}'
+   echo '"https://bioarchive.galaxyproject.org/systemPipeRdata_2.14.4.tar.gz"'
+   tr -d '"'
+   URL=https://bioarchive.galaxyproject.org/systemPipeRdata_2.14.4.tar.gz
+   echo 9d556124a89abebfa6375fc4d5a38d9b
+   tr -d '"'
+   MD5=9d556124a89abebfa6375fc4d5a38d9b
+   curl -L https://bioarchive.galaxyproject.org/systemPipeRdata_2.14.4.tar.gz
+    % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
+                                   Dload  Upload  Total   Spent   Left   Speed
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  Downloading https://bioconductor.org/packages/3.22/bioc/src/contrib/Archive/systemPipeRdata/systemPipeRdata_2.14.4.tar.gz
-  WARNING: Error: HTTP 404 NOT FOUND for url <https://bioconductor.org/packages/3.22/bioc/src/contrib/Archive/systemPipeRdata/systemPipeRdata_2.14.4.tar.gz>
-  Elapsed: 00:00.067809
+    0      0   0      0   0      0      0      0                              0
+  100    153 100    153   0      0    339      0                              0
+  100    153 100    153   0      0    339      0                              0
+  100    153 100    153   0      0    339      0                              0
+   [[ 0 == 0 ]]
+   uname -s
+   [[ Linux == \L\i\n\u\x ]]
+   md5sum -c
+  md5sum: WARNING: 1 computed checksum did NOT match
+   for URL in '${URLS[@]}'
+   echo '"https://depot.galaxyproject.org/software/bioconductor-systempiperdata/bioconductor-systempiperdata_2.14.4_src_all.tar.gz"'
+   tr -d '"'
+   URL=https://depot.galaxyproject.org/software/bioconductor-systempiperdata/bioconductor-systempiperdata_2.14.4_src_all.tar.gz
+   echo 9d556124a89abebfa6375fc4d5a38d9b
+   tr -d '"'
+   MD5=9d556124a89abebfa6375fc4d5a38d9b
+   curl -L https://depot.galaxyproject.org/software/bioconductor-systempiperdata/bioconductor-systempiperdata_2.14.4_src_all.tar.gz
+    % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
+                                   Dload  Upload  Total   Spent   Left   Speed
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  Downloading https://bioarchive.galaxyproject.org/systemPipeRdata_2.14.4.tar.gz
-  WARNING: Error: HTTP 404 NOT FOUND for url <https://bioarchive.galaxyproject.org/systemPipeRdata_2.14.4.tar.gz>
-  Elapsed: 00:00.472451
+    0      0   0      0   0      0      0      0                              0
+  100    153 100    153   0      0    366      0                              0
+  100    153 100    153   0      0    366      0                              0
+  100    153 100    153   0      0    365      0                              0
+   [[ 0 == 0 ]]
+   uname -s
+   [[ Linux == \L\i\n\u\x ]]
+   md5sum -c
+  md5sum: WARNING: 1 computed checksum did NOT match
+   [[ 0 != 1 ]]
+   echo 'ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 9d556124a89abebfa6375fc4d5a38d9b:'
+   printf '%s\n' '"https://bioconductor.org/packages/3.22/data/experiment/src/contrib/systemPipeRdata_2.14.4.tar.gz"' '"https://bioarchive.galaxyproject.org/systemPipeRdata_2.14.4.tar.gz"' '"https://depot.galaxyproject.org/software/bioconductor-systempiperdata/bioconductor-systempiperdata_2.14.4_src_all.tar.gz"'
+   exit 1
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  Downloading https://depot.galaxyproject.org/software/bioconductor-systempiperdata/bioconductor-systempiperdata_2.14.4_src_all.tar.gz
-  WARNING: Error: HTTP 404 NOT FOUND for url <https://depot.galaxyproject.org/software/bioconductor-systempiperdata/bioconductor-systempiperdata_2.14.4_src_all.tar.gz>
-  Elapsed: 00:00.616878
+  return code: 1
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
+  kwargs:
+  {}
+
+  : <exception str() failed>
+
+  During handling of the above exception, another exception occurred:
+
   Traceback (most recent call last):
     File "/opt/conda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
@@ -86,19 +84,21 @@ log: |2-
     File "/opt/conda/lib/python3.12/site-packages/conda_build/api.py", line 211, in build
       return build_tree(
              ^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3669, in build_tree
-      packages_from_this = build(
-                           ^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2461, in build
-      try_download(m, no_download_source=False, raise_error=True)
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/render.py", line 835, in try_download
-      source.provide(metadata)
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/source.py", line 1041, in provide
-      unpack(
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/source.py", line 173, in unpack
-      src_path, unhashed_fn = download_to_cache(
-                              ^^^^^^^^^^^^^^^^^^
-    File "/opt/conda/lib/python3.12/site-packages/conda_build/source.py", line 120, in download_to_cache
-      raise RuntimeError(f"Could not download {url}")
-  RuntimeError: Could not download https://depot.galaxyproject.org/software/bioconductor-systempiperdata/bioconductor-systempiperdata_2.14.4_src_all.tar.gz
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3684, in build_tree
+      test(pkg, config=metadata.config.copy(), stats=stats)
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 3436, in test
+      environ.create_env(
+    File "/opt/conda/lib/python3.12/site-packages/conda_build/environ.py", line 1063, in create_env
+      "too short in" in str(exc)
+                        ^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda/__init__.py", line 132, in __str__
+      return "\n".join(str(e) for e in self.errors)  "\n"
+             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda/__init__.py", line 132, in <genexpr>
+      return "\n".join(str(e) for e in self.errors)  "\n"
+                       ^^^^^^
+    File "/opt/conda/lib/python3.12/site-packages/conda/__init__.py", line 85, in __str__
+      return str(self.message) % self._kwargs
+             ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
+  ValueError: unsupported format character 'T' (0x54) at index 5440
 # Last 100 lines of the build log.
