[ci skip] add build failure record for recipe recipes/tower-cli

diff --git a/recipes/tower-cli/build_failure.osx-64.yaml b/recipes/tower-cli/build_failure.osx-64.yaml
--- a/recipes/tower-cli/build_failure.osx-64.yaml
+++ b/recipes/tower-cli/build_failure.osx-64.yaml
@@ -1,6 +1,7 @@
-recipe_sha: 158bfe7e9af2442a106cc1be3a979ded969fac06f09a6f96fd933c632876ba41  # The commit at which this recipe failed to build.
+recipe_sha: 55b6c884858fe97907d8ef6e7c8de46a8f13b88ba398296c3ebd065be756ecc1  # The commit at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |-
+  /Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/cli/main_build.py:390: UserWarning: RECIPE_PATH received is a file (recipes/tower-cli/meta.yaml).
   It should be a path to a folder.
   Forcing conda-build to use the recipe file.
     warnings.warn(
@@ -11,15 +12,13 @@ log: |-
   INFO:conda_build.variants:Adding in variants from internal_defaults
   Adding in variants from internal_defaults
   INFO:conda_build.variants:Adding in variants from /Users/adam.talbot/mambaforge/envs/bioconda/conda_build_config.yaml
+  INFO:conda_build.variants:Adding in variants from /Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
   Adding in variants from /Users/adam.talbot/mambaforge/envs/bioconda/conda_build_config.yaml
   Adding in variants from /Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
-  INFO:conda_build.variants:Adding in variants from /Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
   Attempting to finalize metadata for tower-cli
   INFO:conda_build.metadata:Attempting to finalize metadata for tower-cli
-  conda-forge/osx-64                                          Using cache
-  conda-forge/noarch                                          Using cache
-  bioconda/osx-64                                             Using cache
-  bioconda/noarch                                             Using cache
+  warning  libmamba Cache file "/Users/adam.talbot/mambaforge/envs/bioconda/pkgs/cache/31ce02e0.json" was modified by another program
+  warning  libmamba Cache file "/Users/adam.talbot/mambaforge/envs/bioconda/pkgs/cache/09cdf8bf.json" was modified by another program
   Reloading output folder: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld
   Reloading output folder: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld
   BUILD START: ['tower-cli-0.9.1-h527b516_0.tar.bz2']
@@ -28,77 +27,36 @@ log: |-
 
   ## Package Plan ##
 
+    environment location: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702038601689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+
+
   INFO:conda_build.source:Source cache directory is: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/src_cache
-  INFO:conda_build.source:Downloading source to cache: tw-osx-x86_64
-    environment location: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-
-
-  INFO:conda_build.source:Downloading https://github.com/seqeralabs/tower-cli/releases/download/v0.9.1/tw-osx-x86_64
+  INFO:conda_build.source:Found source in cache: tw
   Source cache directory is: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/src_cache
-  Downloading source to cache: tw-osx-x86_64
-  Downloading https://github.com/seqeralabs/tower-cli/releases/download/v0.9.1/tw-osx-x86_64
-  Success
-  INFO:conda_build.source:Success
+  Found source in cache: tw
+   OUTDIR=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702038601689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/share/tower-cli-0.9.1-0
+  /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702038601689/work/conda_build.sh: line 7: outdir: unbound variable
   Extracting download
-  INFO:conda_build.build:Packaging tower-cli
   Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
-  source tree in: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work
-  export PREFIX=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
-  export SRC_DIR=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work
-
-  Resource usage statistics from building tower-cli:
-     Process count: 2
-     CPU time: Sys=0:00:00.0, User=0:00:00.0
-     Memory: 6.7M
-     Disk usage: 123.6K
-     Time elapsed: 0:00:02.4
-
-
-  Packaging tower-cli
-  INFO:conda_build.build:Packaging tower-cli-0.9.1-h527b516_0
-  Packaging tower-cli-0.9.1-h527b516_0
-  number of files: 1
-
-  /var/folders/bl/mbfv_v454691rk74_cpk7m840000gn/T/tmp50wsngic/tower-cli-0.9.1-h527b516_0.tar.bz2: C1115 Found invalid license "MPL-2.0" in info/index.json
-     INFO: sysroot: '/System/Library/Frameworks/' files: '['vmnet.framework/Versions/Current', 'vmnet.framework/Versions/A/_CodeSignature/CodeResources', 'vmnet.framework/Versions/A/Resources/version.plist', 'vmnet.framework/Versions/A/Resources/InfoPlist.loctable']'
-     INFO: sysroot: '/usr/lib/' files: '['zsh/5.9/zsh/zselect.so', 'zsh/5.9/zsh/zpty.so', 'zsh/5.9/zsh/zprof.so', 'zsh/5.9/zsh/zleparameter.so']'
-     INFO: sysroot: '/opt/X11/' files: '[]'
-  INFO:conda_build.utils:Renaming work directory '/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work' to '/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work_moved_tower-cli-0.9.1-h527b516_0_osx-64'
-     INFO (tower-cli,bin/tw): Needed DSO /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices found in $SYSROOT
-     INFO (tower-cli,bin/tw): Needed DSO /System/Library/Frameworks/libSystem.B.dylib found in $SYSROOT
-     INFO (tower-cli,bin/tw): Needed DSO /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation found in $SYSROOT
-  INFO:conda_build.utils:shutil.move(work)=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work, dest=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work_moved_tower-cli-0.9.1-h527b516_0_osx-64)
-     INFO (tower-cli,bin/tw): Needed DSO /System/Library/Frameworks/libz.1.dylib found in $SYSROOT
-     INFO (tower-cli,bin/tw): Needed DSO /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork found in $SYSROOT
-     INFO (tower-cli,bin/tw): Needed DSO /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation found in $SYSROOT
-     INFO (tower-cli,bin/tw): Needed DSO /System/Library/Frameworks/libobjc.A.dylib found in $SYSROOT
-  Fixing permissions
-  INFO :: Time taken to mark (prefix)
-          0 replacements in 0 files was 0.22 seconds
-  Package verification results:
-  -----------------------------
-  TEST START: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/osx-64/tower-cli-0.9.1-h527b516_0.tar.bz2
-  Renaming work directory '/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work' to '/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work_moved_tower-cli-0.9.1-h527b516_0_osx-64'
-  shutil.move(work)=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work, dest=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/work_moved_tower-cli-0.9.1-h527b516_0_osx-64)
-  Reloading output folder: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld
-
-  ## Package Plan ##
-
-    environment location: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-
-
-  The following NEW packages will be INSTALLED:
-
-      tower-cli: 0.9.1-h527b516_0 local
-
-  Preparing transaction: ...working... done
-  Verifying transaction: ...working... done
-  Executing transaction: ...working... done
-   tw --help
-  /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/test_tmp/run_test.sh: line 7: 42960 Killed: 9               tw --help
-  Tests failed for tower-cli-0.9.1-h527b516_0.tar.bz2 - moving package to /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/broken
-  WARNING:conda_build.build:Tests failed for tower-cli-0.9.1-h527b516_0.tar.bz2 - moving package to /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/broken
-  export PREFIX=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export SRC_DIR=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702036881533/test_tmp
-  TESTS FAILED: tower-cli-0.9.1-h527b516_0.tar.bz2
+  source tree in: /Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702038601689/work
+  export PREFIX=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702038601689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
+  export SRC_DIR=/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702038601689/work
+  Traceback (most recent call last):
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/bin/conda-mambabuild", line 10, in <module>
+      sys.exit(main())
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 256, in main
+      call_conda_build(action, config)
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
+      result = api.build(
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
+      return build_tree(
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
+      packages_from_this = build(metadata, stats,
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/build.py", line 2198, in build
+      utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/utils.py", line 451, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/Users/adam.talbot/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
+      raise subprocess.CalledProcessError(proc.returncode, _args)
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/adam.talbot/mambaforge/envs/bioconda/conda-bld/tower-cli_1702038601689/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
