[ci skip] add build failure record for recipe recipes/curves

diff --git a/recipes/curves/build_failure.osx-64.yaml b/recipes/curves/build_failure.osx-64.yaml
--- a/recipes/curves/build_failure.osx-64.yaml
+++ b/recipes/curves/build_failure.osx-64.yaml
@@ -1,4 +1,4 @@
-recipe_sha: f9e37f4dc60ce03fbff3caec5aba65713f48eee5420fd8f7e88350476a413150  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 8ed3ed2a1646f5cf5fa1b3b367f9bc209eb8e2ad2941bb3f9b785ee7baa7b0ad  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |-
   Downloading http://curvesplus.bsc.es/static/app/canal.f
@@ -13,38 +13,38 @@ log: |-
   make: *** [Makefile:79: getdate.o] Error 1
   Extracting download
   Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/curves_1718382559413/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/curves_1718386465597/work
   Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
       sys.exit(execute())
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
       api.build(
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/curves_1718382559413/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/curves_1718382559413/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/curves_1718382559413/work
-  INFO: activate-gfortran_osx-64.sh made the following environmental changes:
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
       return build_tree(
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/curves_1718386465597/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/curves_1718386465597/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/curves_1718386465597/work
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
-      packages_from_this = build(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
-      utils.check_call_env(
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
+  INFO: activate-gfortran_osx-64.sh made the following environmental changes:
   DEBUG_FFLAGS=-march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/curves-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
+      packages_from_this = build(
   DEBUG_FORTRANFLAGS=-march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/curves-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
   F77=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran
   F90=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran
   F95=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran
   FC=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran
   FC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran
-      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
+      utils.check_call_env(
   FFLAGS=-march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/curves-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
   FORTRANFLAGS=-march=core2 -mtune=haswell -ftree-vectorize -fPIC -fstack-protector -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/curves-3.0.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
   GFORTRAN=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran
+  INFO: activate_clang_osx-64.sh made the following environmental changes:
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/curves_1718382559413/work/conda_build.sh']' returned non-zero exit status 2.
-  INFO: activate_clang_osx-64.sh made the following environmental changes:
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/curves_1718386465597/work/conda_build.sh']' returned non-zero exit status 2.
   AR=x86_64-apple-darwin13.4.0-ar
   AS=x86_64-apple-darwin13.4.0-as
   CC=x86_64-apple-darwin13.4.0-clang
