[ci skip] add build failure record for recipe recipes/bioconductor-glad

diff --git a/recipes/bioconductor-glad/build_failure.linux-64.yaml b/recipes/bioconductor-glad/build_failure.linux-64.yaml
--- a/recipes/bioconductor-glad/build_failure.linux-64.yaml
+++ b/recipes/bioconductor-glad/build_failure.linux-64.yaml
@@ -1,19 +1,19 @@
-recipe_sha: 6ac4699abe47c1cfa22281a849d364de42a698d94af4800533d7990dd0ed8cb2  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: e33d1b81f75f812368de35323e56fa3eb3edeebb4a132419ef896c01a9c1147e  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
     description: 'Analysis of array CGH data : detection of breakpoints in genomic profiles
       and assignment of a status (gain, normal or loss) to each chromosomal regions
       identified.'
-    license_file: /opt/conda/conda-bld/bioconductor-glad_1770652176319/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/share/licenses/GPL-2
+    license_file: /opt/conda/conda-bld/bioconductor-glad_1770674585710/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/share/licenses/GPL-2
   extra:
     final: true
     copy_test_source_files: true
 
 
-  source tree in: /opt/conda/conda-bld/bioconductor-glad_1770652176319/work
-  export PREFIX=/opt/conda/conda-bld/bioconductor-glad_1770652176319/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
-  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-glad_1770652176319/_build_env
-  export SRC_DIR=/opt/conda/conda-bld/bioconductor-glad_1770652176319/work
+  source tree in: /opt/conda/conda-bld/bioconductor-glad_1770674585710/work
+  export PREFIX=/opt/conda/conda-bld/bioconductor-glad_1770674585710/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
+  export BUILD_PREFIX=/opt/conda/conda-bld/bioconductor-glad_1770674585710/_build_env
+  export SRC_DIR=/opt/conda/conda-bld/bioconductor-glad_1770674585710/work
   INFO: activate-binutils_linux-64.sh made the following environmental changes:
   ADDR2LINE=x86_64-conda-linux-gnu-addr2line
   AR=x86_64-conda-linux-gnu-ar
@@ -66,14 +66,14 @@ log: |2-
   GXX=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-g
   During startup - Warning message:
   Setting LC_TIME failed, using "C"
-  * installing to library /opt/conda/conda-bld/bioconductor-glad_1770652176319/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library
+  * installing to library /opt/conda/conda-bld/bioconductor-glad_1770674585710/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library
   * installing *source* package GLAD ...
   ** this is package GLAD version 2.74.0
   ** package GLAD successfully unpacked and MD5 sums checked
   ** using staged installation
   configure: error: cannot find sources (GLAD) in . or ..
   ERROR: configuration failed for package GLAD
-  * removing /opt/conda/conda-bld/bioconductor-glad_1770652176319/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/GLAD
+  * removing /opt/conda/conda-bld/bioconductor-glad_1770674585710/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/R/library/GLAD
   Traceback (most recent call last):
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2570, in build
       utils.check_call_env(
@@ -82,7 +82,7 @@ log: |2-
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-glad_1770652176319/work/conda_build.sh']' returned non-zero exit status 1.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-glad_1770674585710/work/conda_build.sh']' returned non-zero exit status 1.
 
   The above exception was the direct cause of the following exception:
 
@@ -100,5 +100,5 @@ log: |2-
                            ^^^^^^
     File "/opt/conda/lib/python3.12/site-packages/conda_build/build.py", line 2578, in build
       raise BuildScriptException(str(exc), caused_by=exc) from exc
-  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-glad_1770652176319/work/conda_build.sh']' returned non-zero exit status 1.
+  conda_build.exceptions.BuildScriptException: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/bioconductor-glad_1770674585710/work/conda_build.sh']' returned non-zero exit status 1.
 # Last 100 lines of the build log.
