[ci skip] Add build failure record for recipe recipes/baitfisher

diff --git a/recipes/baitfisher/build_failure.osx-64.yaml b/recipes/baitfisher/build_failure.osx-64.yaml
--- a/recipes/baitfisher/build_failure.osx-64.yaml
+++ b/recipes/baitfisher/build_failure.osx-64.yaml
@@ -1,22 +1,22 @@
-commit_sha: 40f07fe2cc37a11d0f7945633a51aa793d0b532f  # The commit at which this recipe failed to build.
+commit_sha: f507a86712ade3ccdb240e983b850717c47566f1  # The commit at which this recipe failed to build.
 skiplist: true # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |-
   /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/cli/main_build.py:390: UserWarning: RECIPE_PATH received is a file (recipes/baitfisher/meta.yaml).
   It should be a path to a folder.
-  Forcing conda-build to use the recipe file.
-    warnings.warn(
   Updating build index: /opt/mambaforge/envs/bioconda/conda-bld
 
+  Forcing conda-build to use the recipe file.
+    warnings.warn(
   No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.21
   WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.21
-  INFO:conda_build.variants:Adding in variants from internal_defaults
-  INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/conda_build_config.yaml
   Adding in variants from internal_defaults
   Adding in variants from /opt/mambaforge/envs/bioconda/conda_build_config.yaml
-  INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
   Adding in variants from /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
-  INFO:conda_build.metadata:Attempting to finalize metadata for baitfisher
+  INFO:conda_build.variants:Adding in variants from internal_defaults
+  INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/conda_build_config.yaml
+  INFO:conda_build.variants:Adding in variants from /opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/bioconda_utils-conda_build_config.yaml
   Attempting to finalize metadata for baitfisher
+  INFO:conda_build.metadata:Attempting to finalize metadata for baitfisher
   conda-forge/osx-64                                          Using cache
   conda-forge/noarch                                          Using cache
   bioconda/osx-64                                             Using cache
@@ -29,7 +29,7 @@ log: |-
 
   ## Package Plan ##
 
-    environment location: /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
+    environment location: /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
 
 
   The following NEW packages will be INSTALLED:
@@ -44,7 +44,7 @@ log: |-
 
   ## Package Plan ##
 
-    environment location: /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_build_env
+    environment location: /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_build_env
 
 
   The following NEW packages will be INSTALLED:
@@ -86,10 +86,10 @@ log: |-
   Success
   INFO:conda_build.source:Success
   Extracting download
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/work
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/work
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/work
   INFO: activate_clang_osx-64.sh made the following environmental changes:
   +AR=x86_64-apple-darwin13.4.0-ar
   +AS=x86_64-apple-darwin13.4.0-as
@@ -142,39 +142,39 @@ log: |-
   clang-15: warning: -Wl,-pie: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-dead_strip_dylibs: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
+  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
+  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
   x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/baitfisher-1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -std=c++03 -I . -O3 -c bait-fisher.cpp -o bait-fisher.o
   clang-15: warning: -Wl,-pie: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-dead_strip_dylibs: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
+  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
+  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
   x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/baitfisher-1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -std=c++03 -I . -O3 -c Csequence_cluster_and_center_sequence.cpp -o Csequence_cluster_and_center_sequence.o
   clang-15: warning: -Wl,-pie: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-dead_strip_dylibs: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
+  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
+  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
   x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/baitfisher-1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -std=c++03 -I . -O3 -c mydir-unix.cpp -o mydir-unix.o
   clang-15: warning: -Wl,-pie: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-dead_strip_dylibs: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
+  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
+  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
   x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/baitfisher-1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -std=c++03 -I . -O3 -lstdc++ bait-fisher-helper.o bait-fisher.o Csequence_cluster_and_center_sequence.o mydir-unix.o -o BaitFisher-v1.2.7
   x86_64-apple-darwin13.4.0-clang++ -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/baitfisher-1.0 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib -std=c++03 -I . -O3 -c bait-filter.cpp -o bait-filter.o
   clang-15: warning: -Wl,-pie: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-headerpad_max_install_names: 'linker' input unused [-Wunused-command-line-argument]
   clang-15: warning: -Wl,-dead_strip_dylibs: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
-  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
+  clang-15: warning: -Wl,-rpath,/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib: 'linker' input unused [-Wunused-command-line-argument]
+  clang-15: warning: argument unused during compilation: '-L/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib' [-Wunused-command-line-argument]
   In file included from bait-filter.cpp:30:
   In file included from ./CBaitRecord.h:34:
   ./CBlastParser.h:542:33: error: no matching function for call to 'make_pair'
       bh_map.insert(bh_map.end(), std::make_pair<faststring, CBlastHit*>(p->get_query_seq_name(), p));
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-  /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/_build_env/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: 1st argument ('const faststring') would lose const qualifier
+  /opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/_build_env/bin/../include/c++/v1/__utility/pair.h:542:1: note: candidate function template not viable: 1st argument ('const faststring') would lose const qualifier
   make_pair(_T1&& __t1, _T2&& __t2)
   ^
   1 error generated.
@@ -196,4 +196,4 @@ log: |-
       return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
     File "/opt/mambaforge/envs/bioconda/lib/python3.8/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
       raise subprocess.CalledProcessError(proc.returncode, _args)
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685180058028/work/conda_build.sh']' returned non-zero exit status 2.
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/baitfisher_1685181556789/work/conda_build.sh']' returned non-zero exit status 2.
