[ci skip] add build failure record for recipe recipes/bioconductor-methylclockdata

diff --git a/recipes/bioconductor-methylclockdata/build_failure.linux-64.yaml b/recipes/bioconductor-methylclockdata/build_failure.linux-64.yaml
--- a/recipes/bioconductor-methylclockdata/build_failure.linux-64.yaml
+++ b/recipes/bioconductor-methylclockdata/build_failure.linux-64.yaml
@@ -1,84 +1,84 @@
-recipe_sha: c74c6950df4b1abcde61aabfa8dd40e89e4a681e3cfc703a664f355264c1d01e  # The commit at which this recipe failed to build.
+recipe_sha: 02e46aa71b83c3dc7c1c47188eebb0345b5f86bfffd2214099c7138fcb997f8e  # The commit at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
-log: |2-
-      xorg-renderproto:                    0.11.1-h7f98852_1002       conda-forge
-      xorg-xextproto:                      7.3.0-h0b41bf4_1003        conda-forge
-      xorg-xproto:                         7.0.31-h7f98852_1007       conda-forge
-      xz:                                  5.2.6-h166bdaf_0           conda-forge
-      yaml:                                0.2.5-h7f98852_2           conda-forge
-      yq:                                  3.2.2-pyhd8ed1ab_0         conda-forge
-      zlib:                                1.2.13-hd590300_5          conda-forge
-      zstd:                                1.5.2-hfc55251_7           conda-forge
-
-  Preparing transaction: ...working... done
-  Verifying transaction: ...working... done
-  Executing transaction: ...working... done
-  [34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
-  [?25l[2K[0G[] 0.0s
-  opt/conda/conda-bl..    [2K[1A[2K[0Gopt/conda/conda-bld/linux-64
-  opt/conda/conda-bld/noarch                         127.0 B @ 679.1kB/s  0.0s
-  [?25h[34mReloading output folder: [0m[34m/opt/conda/[0m[34mconda-bld[0m
-  [?25l[2K[0G[] 0.0s
-  [2K[1A[2K[0Gopt/conda/conda-bld/linux-64                       129.0 B @   2.8MB/s  0.0s
-  opt/conda/conda-bld/noarch                         127.0 B @   4.5MB/s  0.0s
-  [?25h
-  ## Package Plan ##
-
-    environment location: /opt/conda/conda-bld/bioconductor-methylclockdata_1689624321245/_build_env
+log: |-
+  ==> script output <==
+  stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum null:
 
 
-  Source cache directory is: /opt/conda/conda-bld/src_cache
-  INFO:conda_build.source:Source cache directory is: /opt/conda/conda-bld/src_cache
-  Downloading source to cache: methylclockData_1.8.0_52774d1396.tar.gz
-  INFO:conda_build.source:Downloading source to cache: methylclockData_1.8.0_52774d1396.tar.gz
-  Downloading https://bioconductor.org/packages/3.17/data/experiment/src/contrib/methylclockData_1.8.0.tar.gz
-  INFO:conda_build.source:Downloading https://bioconductor.org/packages/3.17/data/experiment/src/contrib/methylclockData_1.8.0.tar.gz
-  Error: HTTP 404 NOT FOUND for url <https://bioconductor.org/packages/3.17/data/experiment/src/contrib/methylclockData_1.8.0.tar.gz>
-  Elapsed: 00:00.227134
+  stderr:  dirname -- /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/installBiocDataPackage.sh
+   SCRIPT_DIR=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages
+   json=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+   yq '."methylclockdata-1.8.1".fn' /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+   FN=null
+   IFS=
+   read -r value
+   yq '."methylclockdata-1.8.1".urls[]' /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+  jq: error (at <stdin>:1): Cannot iterate over null (null)
+   yq '."methylclockdata-1.8.1".md5' /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+   MD5=null
+   STAGING=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share/methylclockdata-1.8.1
+   mkdir -p /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share/methylclockdata-1.8.1
+   TARBALL=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share/methylclockdata-1.8.1/null
+   SUCCESS=0
+   [[ 0 != 1 ]]
+   echo 'ERROR: post-link.sh was unable to download any of the following URLs with the md5sum null:'
+   printf '{}\n'
+   exit 1
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://bioconductor.org/packages/3.17/data/experiment/src/contrib/methylclockData_1.8.0.tar.gz>
-  Elapsed: 00:00.227134
+  return code: 1
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  Downloading https://bioconductor.org/packages/3.17/bioc/src/contrib/Archive/methylclockData/methylclockData_1.8.0.tar.gz
-  INFO:conda_build.source:Downloading https://bioconductor.org/packages/3.17/bioc/src/contrib/Archive/methylclockData/methylclockData_1.8.0.tar.gz
-  Error: HTTP 404 NOT FOUND for url <https://bioconductor.org/packages/3.17/bioc/src/contrib/Archive/methylclockData/methylclockData_1.8.0.tar.gz>
-  Elapsed: 00:00.262594
+  ()
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://bioconductor.org/packages/3.17/bioc/src/contrib/Archive/methylclockData/methylclockData_1.8.0.tar.gz>
-  Elapsed: 00:00.262594
+  Traceback (most recent call last):
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 1058, in create_env
+      execute_actions(actions, index)
+    File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 84, in decorated
+      return f(*args, **kwds)
+    File "/opt/conda/lib/python3.8/site-packages/conda/plan.py", line 322, in execute_actions
+      execute_instructions(plan, index, verbose)
+    File "/opt/conda/lib/python3.8/site-packages/conda/plan.py", line 532, in execute_instructions
+      cmd(state, arg)
+    File "/opt/conda/lib/python3.8/site-packages/conda/instructions.py", line 73, in UNLINKLINKTRANSACTION_CMD
+      unlink_link_transaction.execute()
+    File "/opt/conda/lib/python3.8/site-packages/conda/core/link.py", line 283, in execute
+      self._execute(tuple(chain(*chain(*zip(*self.prefix_action_groups.values())))))
+    File "/opt/conda/lib/python3.8/site-packages/conda/core/link.py", line 756, in _execute
+      raise CondaMultiError(
+  conda.CondaMultiError: post-link script failed for package local::bioconductor-methylclockdata-1.8.1-r43hdfd78af_0
+  location of failed script: /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/.bioconductor-methylclockdata-post-link.sh
+  ==> script messages <==
+  <None>
+  ==> script output <==
+  stdout: ERROR: post-link.sh was unable to download any of the following URLs with the md5sum null:
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  Downloading https://bioarchive.galaxyproject.org/methylclockData_1.8.0.tar.gz
-  INFO:conda_build.source:Downloading https://bioarchive.galaxyproject.org/methylclockData_1.8.0.tar.gz
-  Error: HTTP 404 NOT FOUND for url <https://bioarchive.galaxyproject.org/methylclockData_1.8.0.tar.gz>
-  Elapsed: 00:00.546842
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://bioarchive.galaxyproject.org/methylclockData_1.8.0.tar.gz>
-  Elapsed: 00:00.546842
+  stderr:  dirname -- /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/installBiocDataPackage.sh
+   SCRIPT_DIR=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages
+   json=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+   yq '."methylclockdata-1.8.1".fn' /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+   FN=null
+   IFS=
+   read -r value
+   yq '."methylclockdata-1.8.1".urls[]' /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+  jq: error (at <stdin>:1): Cannot iterate over null (null)
+   yq '."methylclockdata-1.8.1".md5' /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/../share/bioconductor-data-packages/dataURLs.json
+   MD5=null
+   STAGING=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share/methylclockdata-1.8.1
+   mkdir -p /opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share/methylclockdata-1.8.1
+   TARBALL=/opt/conda/conda-bld/bioconductor-methylclockdata_1689631705216/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share/methylclockdata-1.8.1/null
+   SUCCESS=0
+   [[ 0 != 1 ]]
+   echo 'ERROR: post-link.sh was unable to download any of the following URLs with the md5sum null:'
+   printf '{}\n'
+   exit 1
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  Downloading https://depot.galaxyproject.org/software/bioconductor-methylclockdata/bioconductor-methylclockdata_1.8.0_src_all.tar.gz
-  INFO:conda_build.source:Downloading https://depot.galaxyproject.org/software/bioconductor-methylclockdata/bioconductor-methylclockdata_1.8.0_src_all.tar.gz
-  Error: HTTP 404 NOT FOUND for url <https://depot.galaxyproject.org/software/bioconductor-methylclockdata/bioconductor-methylclockdata_1.8.0_src_all.tar.gz>
-  Elapsed: 00:00.676211
+  return code: 1
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
-  WARNING:conda_build.source:Error: HTTP 404 NOT FOUND for url <https://depot.galaxyproject.org/software/bioconductor-methylclockdata/bioconductor-methylclockdata_1.8.0_src_all.tar.gz>
-  Elapsed: 00:00.676211
+  ()
 
-  An HTTP error occurred when trying to retrieve this URL.
-  HTTP errors are often intermittent, and a simple retry will get you on your way.
+
+  During handling of the above exception, another exception occurred:
+
   Traceback (most recent call last):
     File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
       sys.exit(main())
@@ -88,17 +88,17 @@ log: |2-
       result = api.build(
     File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 180, in build
       return build_tree(
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3078, in build_tree
-      packages_from_this = build(metadata, stats,
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2125, in build
-      try_download(m, no_download_source=False, raise_error=True)
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 650, in try_download
-      source.provide(metadata)
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/source.py", line 871, in provide
-      unpack(source_dict, src_dir, metadata.config.src_cache, recipe_path=metadata.path,
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/source.py", line 146, in unpack
-      src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)
-    File "/opt/conda/lib/python3.8/site-packages/conda_build/source.py", line 102, in download_to_cache
-      raise RuntimeError("Could not download %s" % url)
-  RuntimeError: Could not download https://depot.galaxyproject.org/software/bioconductor-methylclockdata/bioconductor-methylclockdata_1.8.0_src_all.tar.gz
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3089, in build_tree
+      test(pkg, config=metadata.config.copy(), stats=stats)
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2879, in test
+      environ.create_env(metadata.config.test_prefix, actions, config=metadata.config,
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 1116, in create_env
+      create_env(
+    File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 1052, in create_env
+      display_actions(actions, index)
+    File "/opt/conda/lib/python3.8/site-packages/conda/exports.py", line 204, in display_actions
+      actions['LINK'] = [index[d] for d in actions['LINK']]
+    File "/opt/conda/lib/python3.8/site-packages/conda/exports.py", line 204, in <listcomp>
+      actions['LINK'] = [index[d] for d in actions['LINK']]
+  KeyError: PackageRecord(_hash=-847717417810609494, name='_libgcc_mutex', version='0.1', build='conda_forge', build_number=0, channel=Channel("conda-forge/linux-64"), subdir='linux-64', fn='_libgcc_mutex-0.1-conda_forge.tar.bz2', md5='d7c89558ba9fa0495403155b64376d81', url='https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2', sha256='fe51de6107f9edc7aa4f786a70f4a883943bc9d39b3bb7307c04c41410990726', arch=None, platform=None, depends=(), license='None', timestamp=1578324546.067, size=2562)
 # Last 100 lines of the build log.
