[ci skip] add build failure record for recipe recipes/pyprophet

diff --git a/recipes/pyprophet/build_failure.osx-64.yaml b/recipes/pyprophet/build_failure.osx-64.yaml
--- a/recipes/pyprophet/build_failure.osx-64.yaml
+++ b/recipes/pyprophet/build_failure.osx-64.yaml
@@ -1,4 +1,4 @@
-recipe_sha: 3ef1bea91e023de8ce4724982c0064b86ebeb6df1b3bb8049987abb0d6a585ea  # The hash of the recipe's meta.yaml at which this recipe failed to build.
+recipe_sha: 6602b267201208b9666efefd13f5bca891ab10e934fd108360b1f8b62947f6ec  # The hash of the recipe's meta.yaml at which this recipe failed to build.
 skiplist: false # Set to true to skiplist this recipe so that it will be ignored as long as its latest commit is the one given above.
 log: |2-
         Error compiling Cython file:
@@ -17,12 +17,12 @@ log: |2-
         Traceback (most recent call last):
           File "<string>", line 2, in <module>
           File "<pip-setuptools-caller>", line 34, in <module>
-          File "/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/work/setup.py", line 18, in <module>
+          File "/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/work/setup.py", line 18, in <module>
             ext_modules = cythonize(ext_modules)
                           ^^^^^^^^^^^^^^^^^^^^^^
-          File "/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
+          File "/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
             cythonize_one(*args)
-          File "/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
+          File "/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
             raise CompileError(None, pyx_file)
         Cython.Compiler.Errors.CompileError: pyprophet/_optimized.pyx
         [end of output]
@@ -35,43 +35,42 @@ log: |2-
 
   note: This is an issue with the package mentioned above, not pip.
   hint: See above for details.
-  Traceback (most recent call last):
   Extracting download
-  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/work
+  source tree in: /opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/work
+  Traceback (most recent call last):
     File "/opt/mambaforge/envs/bioconda/bin/conda-build", line 11, in <module>
+  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
+  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/_build_env
+  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/work
+  INFO: activate_clang_osx-64.sh made the following environmental changes:
       sys.exit(execute())
+  AR=x86_64-apple-darwin13.4.0-ar
+  AS=x86_64-apple-darwin13.4.0-as
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 590, in execute
+  CC=x86_64-apple-darwin13.4.0-clang
+  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
       api.build(
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/api.py", line 250, in build
       return build_tree(
-  export PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
     File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 3638, in build_tree
-      packages_from_this = build(
-  export BUILD_PREFIX=/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/_build_env
-  export SRC_DIR=/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/work
-  INFO: activate_clang_osx-64.sh made the following environmental changes:
-  AR=x86_64-apple-darwin13.4.0-ar
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
-      utils.check_call_env(
-  AS=x86_64-apple-darwin13.4.0-as
-  CC=x86_64-apple-darwin13.4.0-clang
-  CC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
-      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
-    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
-      raise subprocess.CalledProcessError(proc.returncode, _args)
   CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pyprophet-2.2.5 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
   CHECKSYMS=x86_64-apple-darwin13.4.0-checksyms
   CLANG=x86_64-apple-darwin13.4.0-clang
-  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717706923332/work/conda_build.sh']' returned non-zero exit status 1.
+      packages_from_this = build(
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/build.py", line 2506, in build
+      utils.check_call_env(
   CMAKE_ARGS=-DCMAKE_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_CXX_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_C_COMPILER_AR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ar -DCMAKE_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_CXX_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_C_COMPILER_RANLIB=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ranlib -DCMAKE_LINKER=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ld -DCMAKE_STRIP=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-strip -DCMAKE_INSTALL_NAME_TOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-install_name_tool -DCMAKE_LIBTOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-libtool -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_SYSROOT=/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_FIND_APPBUNDLE=LAST -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_PROGRAM_PATH=$BUILD_PREFIX/bin;$PREFIX/bin
   CMAKE_PREFIX_PATH=:$PREFIX
   CONDA_TOOLCHAIN_BUILD=x86_64-apple-darwin13.4.0
   CONDA_TOOLCHAIN_HOST=x86_64-apple-darwin13.4.0
   CPPFLAGS=-D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9
   DEBUG_CFLAGS=-march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/pyprophet-2.2.5 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 405, in check_call_env
+      return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
+    File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/conda_build/utils.py", line 381, in _func_defaulting_env_to_os_environ
   HOST=x86_64-apple-darwin13.4.0
   INSTALL_NAME_TOOL=x86_64-apple-darwin13.4.0-install_name_tool
+      raise subprocess.CalledProcessError(proc.returncode, _args)
   LD=x86_64-apple-darwin13.4.0-ld
   LDFLAGS=-Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib
   LDFLAGS_LD=-headerpad_max_install_names -dead_strip_dylibs -rpath $PREFIX/lib -L$PREFIX/lib
@@ -79,6 +78,7 @@ log: |2-
   LIPO=x86_64-apple-darwin13.4.0-lipo
   MESON_ARGS=--buildtype release --prefix=$PREFIX -Dlibdir=lib
   NM=x86_64-apple-darwin13.4.0-nm
+  subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/mambaforge/envs/bioconda/conda-bld/pyprophet_1717781251565/work/conda_build.sh']' returned non-zero exit status 1.
   NMEDIT=x86_64-apple-darwin13.4.0-nmedit
   OBJC=x86_64-apple-darwin13.4.0-clang
   OBJC_FOR_BUILD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
